# Generated by Django 3.2.8 on 2021-11-02 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO maps_region (
                    id,
                    name,
                    country,
                    geom
                )
                SELECT
                    id,
                    name,
                    country,
                    geom
                FROM
                    inventories_region;
                    
                SELECT setval(pg_get_serial_sequence('"maps_region"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "maps_region";
            """, reverse_sql="""
                INSERT INTO inventories_region (
                    id,
                    name,
                    country,
                    geom
                )
                SELECT
                    id,
                    name,
                    country,
                    geom
                FROM
                    maps_region;
            """),
        migrations.RunSQL("""
                    INSERT INTO maps_catchment (
                        id,
                        name,
                        owner_id,
                        region_id,
                        description,
                        type,
                        geom
                    )
                    SELECT
                        id,
                        name,
                        owner_id,
                        region_id,
                        description,
                        type,
                        geom
                    FROM
                        inventories_catchment;
                    SELECT setval(pg_get_serial_sequence('"maps_catchment"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "maps_catchment";
                """, reverse_sql="""
                    INSERT INTO inventories_catchment (
                        id,
                        name,
                        owner_id,
                        region_id,
                        description,
                        type,
                        geom
                    )
                    SELECT
                        id,
                        name,
                        owner_id,
                        region_id,
                        description,
                        type,
                        geom
                    FROM
                        maps_catchment;
                """),
        migrations.RunSQL("""
                    INSERT INTO maps_sfbsite (
                        id,
                        name,
                        owner_id,
                        geom
                    )
                    SELECT
                        id,
                        name,
                        owner_id,
                        geom
                    FROM
                        inventories_sfbsite;
                    
                    SELECT setval(pg_get_serial_sequence('"maps_sfbsite"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "maps_sfbsite";
                """, reverse_sql="""
                    INSERT INTO inventories_sfbsite (
                        id,
                        name,
                        owner_id,
                        geom
                    )
                    SELECT
                        id,
                        name,
                        owner_id,
                        geom
                    FROM
                        maps_sfbsite;
                """),
        migrations.RunSQL("""
                    INSERT INTO maps_geodataset (
                        id,
                        name,
                        preview,
                        publish,
                        description,
                        region_id,
                        model_name
                    )
                    SELECT
                        id,
                        name,
                        preview,
                        publish,
                        description,
                        region_id,
                        model_name
                    FROM
                        inventories_geodataset;
                    SELECT setval(pg_get_serial_sequence('"maps_geodataset"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "maps_geodataset";
                """, reverse_sql="""
                    INSERT INTO inventories_geodataset (
                        id,
                        name,
                        preview,
                        publish,
                        description,
                        region_id,
                        model_name
                    )
                    SELECT
                        id,
                        name,
                        preview,
                        publish,
                        description,
                        region_id,
                        model_name
                    FROM
                        maps_geodataset;
                """),
        migrations.RunSQL("""
                        INSERT INTO maps_geodataset_sources (
                            id,
                            geodataset_id,
                            source_id
                        )
                        SELECT
                            id,
                            geodataset_id,
                            source_id
                        FROM
                            inventories_geodataset_sources;
                        SELECT setval(pg_get_serial_sequence('"maps_geodataset_sources"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "maps_geodataset_sources";
                    """, reverse_sql="""
                        INSERT INTO inventories_geodataset_sources (
                            id,
                            geodataset_id,
                            source_id
                        )
                        SELECT
                            id,
                            geodataset_id,
                            source_id
                        FROM
                            maps_geodataset_sources;
                    """)
    ]
