# Generated by Django 3.2.10 on 2022-01-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LauRegion',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.region')),
                ('cntr_code', models.CharField(blank=True, max_length=2, null=True)),
                ('lau_id', models.CharField(blank=True, max_length=13, null=True)),
                ('lau_name', models.CharField(blank=True, max_length=113, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('nuts_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lau_children', to='maps.nutsregion')),
            ],
            options={
                'abstract': False,
            },
            bases=('maps.region',),
        ),
    ]
