# Generated by Django 3.2.8 on 2021-11-09 13:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20211102_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapsNutsregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('nuts_id', models.CharField(blank=True, max_length=5, null=True)),
                ('levl_code', models.IntegerField(blank=True, null=True)),
                ('cntr_code', models.CharField(blank=True, max_length=2, null=True)),
                ('name_latn', models.CharField(blank=True, max_length=70, null=True)),
                ('nuts_name', models.CharField(blank=True, max_length=106, null=True)),
                ('mount_type', models.IntegerField(blank=True, null=True)),
                ('urbn_type', models.IntegerField(blank=True, null=True)),
                ('coast_type', models.IntegerField(blank=True, null=True)),
                ('fid', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'maps_nutsregion',
                'managed': False,
            },
        ),
    ]
