# Generated by Django 3.2.10 on 2022-02-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('maps', '0002_lauregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='type',
            field=models.CharField(
                choices=[('administrative', 'administrative'), ('custom', 'custom'), ('nuts', 'nuts'), ('lau', 'lau')],
                default='custom', max_length=14),
        ),
    ]
