# Generated by Django 3.2.10 on 2022-01-21 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('maps', '0002_lauregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LauRegionTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('gisco_id', models.CharField(blank=True, max_length=16, null=True)),
                ('cntr_code', models.CharField(blank=True, max_length=2, null=True)),
                ('lau_id', models.CharField(blank=True, max_length=13, null=True)),
                ('lau_name', models.CharField(blank=True, max_length=113, null=True)),
                ('pop_2020', models.IntegerField(blank=True, null=True)),
                ('pop_dens_2', models.FloatField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fid', models.CharField(blank=True, max_length=16, null=True)),
                ('nuts_parent_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
