# Generated by Django 5.2.4 on 2026-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_alter_attribute_publication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="type",
            field=models.CharField(
                choices=[
                    ("administrative", "administrative"),
                    ("custom", "custom"),
                    ("nuts", "nuts"),
                    ("lau", "lau"),
                ],
                default="custom",
                max_length=14,
            ),
        ),
    ]
