# Generated by Django 5.2.4 on 2026-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_region_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='geodataset',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='mapconfiguration',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='maplayerconfiguration',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='maplayerstyle',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='regionattributetextvalue',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='regionattributevalue',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
    ]
