# Generated by Django 3.2.10 on 2022-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20220408_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionattributevalue',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
