# Generated by Django 3.2.8 on 2021-11-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_geopolygon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapsnutsregion',
            options={},
        ),
    ]
