# Generated by Django 5.2.4 on 2026-02-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0004_region_type_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodataset",
            name="display_fields",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="geodataset",
            name="filter_fields",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="geodataset",
            name="geometry_field",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="geodataset",
            name="table_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
