# Generated by Django 5.2.4 on 2026-03-26 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import utils.object_management.models


def copy_text_attributes_to_categorical(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Attribute = apps.get_model("maps", "Attribute")
    CategoricalAttribute = apps.get_model("maps", "CategoricalAttribute")
    RegionAttributeTextValue = apps.get_model("maps", "RegionAttributeTextValue")

    categorical_attribute_ids_by_attribute_id = {}
    text_values = RegionAttributeTextValue.objects.using(db_alias).all()

    for text_value in text_values.iterator():
        attribute_id = text_value.attribute_id
        if attribute_id not in categorical_attribute_ids_by_attribute_id:
            attribute = Attribute.objects.using(db_alias).get(pk=attribute_id)
            categorical_attribute = CategoricalAttribute.objects.using(db_alias).create(
                name=attribute.name,
                description=attribute.description,
                owner_id=attribute.owner_id,
                publication_status=attribute.publication_status,
                submitted_at=attribute.submitted_at,
                approved_at=attribute.approved_at,
                approved_by_id=attribute.approved_by_id,
                created_at=attribute.created_at,
                lastmodified_at=attribute.lastmodified_at,
                created_by_id=attribute.created_by_id,
                lastmodified_by_id=attribute.lastmodified_by_id,
            )
            categorical_attribute_ids_by_attribute_id[attribute_id] = (
                categorical_attribute.pk
            )

        text_value.categorical_attribute_id = categorical_attribute_ids_by_attribute_id[
            attribute_id
        ]
        text_value.save(update_fields=["categorical_attribute"])


def copy_categorical_attributes_to_text_attributes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Attribute = apps.get_model("maps", "Attribute")
    CategoricalAttribute = apps.get_model("maps", "CategoricalAttribute")
    RegionAttributeTextValue = apps.get_model("maps", "RegionAttributeTextValue")

    attribute_ids_by_categorical_attribute_id = {}
    text_values = RegionAttributeTextValue.objects.using(db_alias).all()

    for text_value in text_values.iterator():
        categorical_attribute_id = text_value.categorical_attribute_id
        if categorical_attribute_id not in attribute_ids_by_categorical_attribute_id:
            categorical_attribute = CategoricalAttribute.objects.using(db_alias).get(
                pk=categorical_attribute_id
            )
            attribute = Attribute.objects.using(db_alias).create(
                name=categorical_attribute.name,
                description=categorical_attribute.description,
                unit="",
                owner_id=categorical_attribute.owner_id,
                publication_status=categorical_attribute.publication_status,
                submitted_at=categorical_attribute.submitted_at,
                approved_at=categorical_attribute.approved_at,
                approved_by_id=categorical_attribute.approved_by_id,
                created_at=categorical_attribute.created_at,
                lastmodified_at=categorical_attribute.lastmodified_at,
                created_by_id=categorical_attribute.created_by_id,
                lastmodified_by_id=categorical_attribute.lastmodified_by_id,
            )
            attribute_ids_by_categorical_attribute_id[categorical_attribute_id] = (
                attribute.pk
            )

        text_value.attribute_id = attribute_ids_by_categorical_attribute_id[
            categorical_attribute_id
        ]
        text_value.save(update_fields=["attribute"])


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0005_alter_attribute_publication_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoricalAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last modified at",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                            ("archived", "Archived"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=utils.object_management.models.get_default_owner_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="regionattributetextvalue",
            name="categorical_attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="maps.categoricalattribute",
            ),
        ),
        migrations.RunPython(
            copy_text_attributes_to_categorical,
            copy_categorical_attributes_to_text_attributes,
        ),
        migrations.RemoveField(
            model_name="regionattributetextvalue",
            name="attribute",
        ),
        migrations.AlterField(
            model_name="regionattributetextvalue",
            name="categorical_attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="maps.categoricalattribute",
            ),
        ),
    ]
