# Generated by Django 3.2.8 on 2021-11-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_mapsnutsregion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapsnutsregion',
            old_name='geom',
            new_name='geom_old',
        ),
        migrations.AlterModelTable(
            name='mapsnutsregion',
            table=None,
        ),
    ]
