# Generated by Django 3.2.10 on 2022-09-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from utils.models import get_default_owner_pk


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0005_alter_regionattributevalue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='owner',
            field=models.ForeignKey(default=get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='owner',
            field=models.ForeignKey(default=get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geodataset',
            name='owner',
            field=models.ForeignKey(default=get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='owner',
            field=models.ForeignKey(default=get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regionattributetextvalue',
            name='owner',
            field=models.ForeignKey(default=get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regionattributevalue',
            name='owner',
            field=models.ForeignKey(default=get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sfbsite',
            name='owner',
            field=models.ForeignKey(default=get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
