# Generated by Django 3.2.8 on 2021-11-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20211109_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapsNutsregion',
            new_name='Nutsregion',
        ),
    ]
