# Generated by Django 6.0.3 on 2026-03-26 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0006_split_categorical_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={},
        ),
    ]
