# Generated by Django 3.2.10 on 2022-11-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20220924_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maps.catchment', verbose_name='parent'),
        ),
    ]
