# Generated by Django 6.0.3 on 2026-03-26 11:59

import django.db.models.deletion
from django.db import migrations, models


def backfill_region_attribute_value_units(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RegionAttributeValue = apps.get_model("maps", "RegionAttributeValue")
    Unit = apps.get_model("properties", "Unit")

    unit_ids_by_owner_and_name = {}
    values = (
        RegionAttributeValue.objects.using(db_alias)
        .select_related("attribute")
        .filter(unit__isnull=True)
    )

    for value in values.iterator():
        attribute = value.attribute
        unit_label = (attribute.unit or "").strip()
        if not unit_label:
            continue

        cache_key = (attribute.owner_id, unit_label)
        if cache_key not in unit_ids_by_owner_and_name:
            unit, _ = Unit.objects.using(db_alias).get_or_create(
                owner_id=attribute.owner_id,
                name=unit_label,
                defaults={
                    "symbol": unit_label if len(unit_label) <= 63 else "",
                    "publication_status": attribute.publication_status,
                },
            )
            unit_ids_by_owner_and_name[cache_key] = unit.pk

        value.unit_id = unit_ids_by_owner_and_name[cache_key]
        value.save(update_fields=["unit"])


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0007_alter_attribute_options"),
        ("properties", "0006_merge_20260217_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionattributevalue",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.unit",
            ),
        ),
        migrations.RunPython(
            backfill_region_attribute_value_units,
            migrations.RunPython.noop,
        ),
    ]
