# Generated by Django 3.2.8 on 2021-11-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_rename_mapsnutsregion_nutsregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutsregion',
            name='borders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maps.geopolygon'),
        ),
    ]
