# Generated by Django 4.0.10 on 2023-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('maps', '0008_alter_attribute_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='preview',
            field=models.ImageField(default='img/generic_map.png', upload_to='images/geodatasets/'),
        ),
    ]
