# Generated by Django 3.2.8 on 2021-11-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_nutsregion_borders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutsregion',
            name='geom_old',
        ),
    ]
