# Generated by Django 3.2.8 on 2021-11-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_remove_nutsregion_geom_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='model_name',
            field=models.CharField(choices=[('HamburgRoadsideTrees', 'HamburgRoadsideTrees'), ('HamburgGreenAreas', 'HamburgGreenAreas'), ('NantesGreenhouses', 'NantesGreenhouses'), ('NutsRegionOld', 'NutsRegionOld')], max_length=56, null=True),
        ),
    ]
