# Generated by Django 4.2.6 on 2023-10-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0015_alter_author_created_by_alter_author_lastmodified_by_and_more'),
        ('maps', '0009_alter_geodataset_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataset',
            name='resources',
            field=models.ManyToManyField(related_name='resource_to_geodatasets', to='bibliography.source'),
        ),
        migrations.AlterField(
            model_name='geodataset',
            name='sources',
            field=models.ManyToManyField(related_name='geodatasets', to='bibliography.source'),
        ),
    ]
