# Generated by Django 6.0.3 on 2026-04-01 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0010_regionattributevalue_regionproperty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regionproperty",
            options={},
        ),
    ]
