# Generated by Django 4.2.8 on 2024-03-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_remove_scenario_site'),
        ('maps', '0011_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SFBSite',
        ),
    ]
