# Generated by Django 3.2.8 on 2021-11-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20211111_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='borders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maps.geopolygon'),
        ),
    ]
