# Generated by Django 4.2.8 on 2024-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_delete_sfbsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='composed_of',
            field=models.ManyToManyField(blank=True, related_name='composing_regions', to='maps.region'),
        ),
    ]
