# Generated by Django 6.0.3 on 2026-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0012_geodataset_runtime_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geodatasetcolumnpolicy",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="geodatasetruntimeconfiguration",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
