# Generated by Django 3.2.8 on 2021-11-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_region_borders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='geom',
        ),
    ]
