# Generated by Django 5.1.1 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_attribute_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='catchment',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='geodataset',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='georeferencedcatchment',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='georeferencednutsregion',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='georeferencedregion',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='lauregion',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='nutsregion',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='regionattributetextvalue',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='regionattributevalue',
            options={'ordering': ['name', 'id']},
        ),
    ]
