# Generated by Django 3.2.8 on 2021-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_remove_region_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopolygon',
            name='fid',
            field=models.BigIntegerField(null=True),
        ),
    ]
