# Generated by Django 4.2.8 on 2024-07-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_attribute_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='catchment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='geodataset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='georeferencedcatchment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='georeferencednutsregion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='georeferencedregion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lauregion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='nutsregion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='regionattributetextvalue',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='regionattributevalue',
            options={'ordering': ['name']},
        ),
    ]
