# Generated by Django 5.1.1 on 2024-11-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('maps', '0015_alter_attribute_options_alter_catchment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='preview',
            field=models.ImageField(default='generic_map.png', upload_to='maps_geodataset/'),
        ),
    ]
