# Generated by Django 6.0.5 on 2026-07-27 16:29

import django.db.models.deletion
from django.db import migrations, models

# All 2,010 pre-existing rows were audited against the GISCO code lists and match
# NUTS 2021 exactly (identical codes, levels and Latin names; zero differences).
INITIAL_VINTAGE_YEAR = 2021


def seed_initial_vintage(apps, schema_editor):
    NutsVintage = apps.get_model("maps", "NutsVintage")
    NutsRegion = apps.get_model("maps", "NutsRegion")

    duplicates = (
        NutsRegion.objects.values("nuts_id")
        .annotate(count=models.Count("pk"))
        .filter(count__gt=1, nuts_id__isnull=False)
        .values_list("nuts_id", flat=True)
    )
    duplicates = list(duplicates[:10])
    if duplicates:
        raise RuntimeError(
            "Cannot enforce unique (nuts_id, version): duplicate nuts_id values "
            f"exist, e.g. {duplicates}. Deduplicate before migrating."
        )

    vintage, _ = NutsVintage.objects.get_or_create(
        year=INITIAL_VINTAGE_YEAR,
        defaults={"is_current": True, "source_release": "GISCO NUTS 2021"},
    )
    if not NutsVintage.objects.filter(is_current=True).exists():
        vintage.is_current = True
        vintage.save(update_fields=["is_current"])
    NutsRegion.objects.filter(version__isnull=True).update(version=vintage)


def unseed_initial_vintage(apps, schema_editor):
    NutsRegion = apps.get_model("maps", "NutsRegion")
    NutsVintage = apps.get_model("maps", "NutsVintage")
    NutsRegion.objects.update(version=None)
    NutsVintage.objects.filter(year=INITIAL_VINTAGE_YEAR).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0015_geodatasetcolumnpolicy_is_popup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutsregion",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="NutsVintage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("is_current", models.BooleanField(default=False)),
                ("source_release", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-year"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="unique_current_nuts_vintage",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="nutsregion",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regions",
                to="maps.nutsvintage",
            ),
        ),
        migrations.RunPython(seed_initial_vintage, unseed_initial_vintage),
        migrations.AlterField(
            model_name="nutsregion",
            name="version",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regions",
                to="maps.nutsvintage",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutsregion",
            constraint=models.UniqueConstraint(
                fields=("nuts_id", "version"), name="unique_nuts_id_per_version"
            ),
        ),
    ]
