# Generated by Django 3.2.8 on 2021-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_geopolygon_fid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geopolygon',
            name='id',
        ),
        migrations.AlterField(
            model_name='geopolygon',
            name='fid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
