# Generated by Django 5.1.1 on 2024-11-16 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('maps', '0016_alter_geodataset_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='catchment',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='geodataset',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='location',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='region',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='regionattributetextvalue',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='regionattributevalue',
            name='visible_to_groups',
        ),
    ]
