# Generated by Django 6.0.5 on 2026-08-04 10:16

import hashlib

import django.contrib.gis.db.models.fields
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import utils.object_management.models


def backfill_catchment_revisions(apps, schema_editor):
    Catchment = apps.get_model("maps", "Catchment")
    CatchmentRevision = apps.get_model("maps", "CatchmentRevision")
    database = schema_editor.connection.alias
    through = CatchmentRevision.members.through
    catchments = (
        Catchment.objects.using(database)
        .filter(region__borders__geom__isnull=False)
        .select_related("region__borders")
        .prefetch_related("region__composed_of")
        .order_by("pk")
    )

    # Geometry payloads can be large. Bound migration memory by materializing
    # and inserting a small primary-key window at a time.
    last_pk = 0
    while True:
        batch = list(catchments.filter(pk__gt=last_pk)[:200])
        if not batch:
            break

        revisions = []
        for catchment in batch:
            geom = catchment.region.borders.geom
            revisions.append(
                CatchmentRevision(
                    catchment_id=catchment.pk,
                    name=f"{catchment.name or 'Catchment'} — initial boundary",
                    description=(
                        "Initial immutable snapshot migrated from the legacy catchment "
                        "geometry. Its lower effective bound is unknown."
                    ),
                    geom=geom,
                    geom_hash=hashlib.sha256(bytes(geom.ewkb)).hexdigest(),
                    change_reason="initial",
                    owner_id=catchment.owner_id,
                    publication_status="published",
                    created_by_id=catchment.created_by_id,
                    lastmodified_by_id=catchment.lastmodified_by_id,
                )
            )

        CatchmentRevision.objects.using(database).bulk_create(revisions, batch_size=200)

        member_links = []
        for revision, catchment in zip(revisions, batch, strict=True):
            member_links.extend(
                through(catchmentrevision_id=revision.pk, region_id=member.pk)
                for member in catchment.region.composed_of.all()
            )
        through.objects.using(database).bulk_create(
            member_links, batch_size=1000, ignore_conflicts=True
        )
        last_pk = batch[-1].pk


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0010_author_contact_details"),
        ("maps", "0016_alter_nutsregion_options_nutsvintage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="CatchmentRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last modified at",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                            ("archived", "Archived"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("geom_hash", models.CharField(editable=False, max_length=64)),
                (
                    "change_reason",
                    models.CharField(
                        choices=[
                            ("initial", "Initial snapshot"),
                            ("addition", "Territory added"),
                            ("removal", "Territory removed"),
                            ("transfer", "Territory transferred"),
                            ("split", "Catchment split"),
                            ("merge", "Catchments merged"),
                            ("administrative", "Administrative boundary revision"),
                            ("correction", "Data correction"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catchment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="maps.catchment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="catchment_revisions", to="maps.region"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=utils.object_management.models.get_default_owner_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "predecessors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="successors",
                        to="maps.catchmentrevision",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(blank=True, to="bibliography.source"),
                ),
            ],
            options={
                "ordering": ["catchment_id", "effective_from", "id"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["catchment", "effective_from", "effective_to"],
                        name="maps_catchm_catchme_ea3be9_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_from__isnull", True),
                            ("effective_to__isnull", True),
                            ("effective_from__lt", models.F("effective_to")),
                            _connector="OR",
                        ),
                        name="catchment_revision_effective_period_valid",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(
                            ("publication_status__in", ("published", "archived"))
                        ),
                        expressions=[
                            ("catchment", "="),
                            (
                                models.Func(
                                    models.F("effective_from"),
                                    models.F("effective_to"),
                                    function="DATERANGE",
                                    output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                                ),
                                "&&",
                            ),
                        ],
                        name="catchment_revision_no_public_period_overlap",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_catchment_revisions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
