# Generated by Django 3.2.8 on 2021-11-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20211111_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nutsregion',
            new_name='NutsRegionOld',
        ),
    ]
