# Generated by Django 6.0.8 on 2026-09-22 11:52

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def _resolve_unit_label(Unit, label, owner_id):
    """Match a legacy free-text unit label to a Unit by name or symbol."""
    normalized = (label or "").strip()
    if not normalized:
        return None

    filters = Q(name=normalized) | Q(symbol=normalized)
    if owner_id is not None:
        unit = Unit.objects.filter(owner_id=owner_id).filter(filters).first()
        if unit is not None:
            return unit

    return Unit.objects.filter(filters).first()


def _get_or_create_unit(Unit, User, label, owner_id):
    label = (label or "").strip()
    if not label:
        return None
    unit = _resolve_unit_label(Unit, label, owner_id)
    if unit is not None:
        return unit
    username = getattr(settings, "DEFAULT_OWNER_USERNAME", "flexibi")
    owner, _ = User.objects.get_or_create(
        username=username, defaults={"is_active": True}
    )
    unit, _ = Unit.objects.get_or_create(
        owner_id=owner_id or owner.pk,
        name=label,
        defaults={"symbol": label if len(label) <= 63 else ""},
    )
    return unit


def migrate_units_to_allowed_units(apps, schema_editor):
    """Resolve legacy ``RegionProperty.unit`` labels into structured units.

    1. Populate ``RegionProperty.allowed_units`` from the char label,
       creating ``Unit`` rows for labels that cannot be resolved.
    2. Backfill ``RegionAttributeValue.unit`` FKs that previously relied on
       the property's char label.
    """
    RegionProperty = apps.get_model("maps", "RegionProperty")
    RegionAttributeValue = apps.get_model("maps", "RegionAttributeValue")
    Unit = apps.get_model("properties", "Unit")
    User = apps.get_model("auth", "User")

    unit_cache = {}
    for prop in RegionProperty.objects.exclude(unit=""):
        unit = _get_or_create_unit(Unit, User, prop.unit, prop.owner_id)
        if unit is None:
            continue
        prop.allowed_units.add(unit)
        unit_cache[prop.pk] = unit

    for value in RegionAttributeValue.objects.filter(unit__isnull=True).iterator():
        unit = unit_cache.get(value.property_id)
        if unit is None:
            label = (
                RegionProperty.objects.filter(pk=value.property_id)
                .values_list("unit", flat=True)
                .first()
            )
            if label and label.strip():
                unit = _get_or_create_unit(Unit, User, label.strip(), None)
                unit_cache[value.property_id] = unit
        if unit is not None:
            RegionAttributeValue.objects.filter(pk=value.pk).update(unit=unit)


def reverse_migrate_units(apps, schema_editor):
    """Restore ``RegionProperty.unit`` labels from the first allowed unit."""
    RegionProperty = apps.get_model("maps", "RegionProperty")
    for prop in RegionProperty.objects.all():
        unit = prop.allowed_units.first()
        if unit is not None:
            prop.unit = unit.name[:127]
            prop.save(update_fields=["unit"])


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0017_catchment_revisions"),
        ("properties", "0010_remove_property_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionproperty",
            name="allowed_units",
            field=models.ManyToManyField(
                blank=True,
                help_text="Units that are acceptable for this property.",
                to="properties.unit",
            ),
        ),
        migrations.RunPython(
            migrate_units_to_allowed_units,
            reverse_migrate_units,
        ),
        migrations.RemoveField(
            model_name="regionproperty",
            name="unit",
        ),
    ]
