# Generated by Django 3.2.8 on 2021-11-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_rename_nutsregion_nutsregionold'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutsRegion',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.region')),
                ('nuts_id', models.CharField(blank=True, max_length=5, null=True)),
                ('levl_code', models.IntegerField(blank=True, null=True)),
                ('cntr_code', models.CharField(blank=True, max_length=2, null=True)),
                ('name_latn', models.CharField(blank=True, max_length=70, null=True)),
                ('nuts_name', models.CharField(blank=True, max_length=106, null=True)),
                ('mount_type', models.IntegerField(blank=True, null=True)),
                ('urbn_type', models.IntegerField(blank=True, null=True)),
                ('coast_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('maps.region',),
        ),
    ]
