# Generated by Django 6.0.8 on 2026-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0018_remove_regionproperty_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="name_en",
            field=models.CharField(blank=True, max_length=113, null=True),
        ),
    ]
