# Generated by Django 5.1.1 on 2024-11-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_mapconfiguration_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='map_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='geodatasets', to='maps.mapconfiguration'),
        ),
        migrations.AlterField(
            model_name='geodataset',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geodatasets', to='maps.region'),
        ),
    ]
