# Generated by Django 3.2.8 on 2021-11-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_nutsregion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NutsRegionOld',
        ),
    ]
