# Generated by Django 5.1.1 on 2024-11-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_remove_attribute_visible_to_groups_and_more'),
        ('maps', '0020_alter_maplayerconfiguration_api_basename_and_more'),
    ]

    operations = [
    ]
