# Generated by Django 5.1.1 on 2024-11-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_merge_20241126_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapconfiguration',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='maplayerconfiguration',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='maplayerstyle',
            name='visible_to_groups',
        ),
    ]
