# Generated by Django 5.1.7 on 2025-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_remove_mapconfiguration_visible_to_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataset',
            name='display_fields',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='geodataset',
            name='filter_fields',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='geodataset',
            name='geometry_field',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='geodataset',
            name='table_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
