# Generated by Django 3.2.8 on 2021-11-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_auto_20211111_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopolygon',
            name='fid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
