# Generated by Django 3.2.8 on 2021-11-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_alter_geopolygon_fid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catchment',
            name='regions',
        ),
        migrations.AddField(
            model_name='catchment',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.region'),
        ),
    ]
