# Generated by Django 3.2.8 on 2021-11-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_auto_20211112_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catchment',
            name='geom',
        ),
    ]
