# Generated by Django 3.2.8 on 2021-11-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0026_remove_catchment_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoreferencedCatchment',
            fields=[
                ('catchment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='maps.catchment')),
                ('geopolygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.geopolygon')),
            ],
            options={
                'abstract': False,
            },
            bases=('maps.geopolygon', 'maps.catchment'),
        ),
        migrations.CreateModel(
            name='GeoreferencedNutsRegion',
            fields=[
                ('nutsregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='maps.nutsregion')),
                ('geopolygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.geopolygon')),
            ],
            options={
                'abstract': False,
            },
            bases=('maps.geopolygon', 'maps.nutsregion'),
        ),
    ]
