# Generated by Django 3.2.8 on 2021-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_georeferencedcatchment_georeferencednutsregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='model_name',
            field=models.CharField(choices=[('HamburgRoadsideTrees', 'HamburgRoadsideTrees'), ('HamburgGreenAreas', 'HamburgGreenAreas'), ('NantesGreenhouses', 'NantesGreenhouses'), ('NutsRegion', 'NutsRegion'), ('WasteCollection', 'WasteCollection')], max_length=56, null=True),
        ),
    ]
