# Generated by Django 3.2.8 on 2021-11-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_alter_geodataset_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutsregion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maps.nutsregion'),
        ),
    ]
