# Generated by Django 3.2.8 on 2021-11-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0029_nutsregion_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutsregion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='maps.nutsregion'),
        ),
    ]
