# Generated by Django 3.2.8 on 2021-11-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0030_alter_nutsregion_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='parent_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_catchments', to='maps.region'),
        ),
    ]
