# Generated by Django 6.0.3 on 2026-04-07 12:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HamburgRoadsideTrees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("baumid", models.IntegerField(blank=True, null=True)),
                ("gattung", models.CharField(blank=True, max_length=63, null=True)),
                (
                    "gattung_latein",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "gattung_deutsch",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                ("art", models.CharField(blank=True, max_length=63, null=True)),
                ("art_latein", models.CharField(blank=True, max_length=63, null=True)),
                ("art_deutsch", models.CharField(blank=True, max_length=63, null=True)),
                (
                    "sorte_latein",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "sorte_deutsch",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                ("pflanzjahr", models.IntegerField(blank=True, null=True)),
                ("pflanzjahr_portal", models.IntegerField(blank=True, null=True)),
                ("kronendurchmesser", models.IntegerField(blank=True, null=True)),
                ("stammumfang", models.IntegerField(blank=True, null=True)),
                ("strasse", models.CharField(blank=True, max_length=63, null=True)),
                ("hausnummer", models.CharField(blank=True, max_length=63, null=True)),
                ("ortsteil_nr", models.CharField(blank=True, max_length=63, null=True)),
                ("stadtteil", models.CharField(blank=True, max_length=63, null=True)),
                ("bezirk", models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                "verbose_name": "Hamburg Roadside Tree",
                "verbose_name_plural": "Hamburg Roadside Trees",
                "db_table": "roadside_trees_hamburgroadsidetrees",
                "ordering": ["baumid"],
                "indexes": [
                    models.Index(
                        fields=["baumid"], name="flexibi_ham_baumid_4f523a_idx"
                    ),
                    models.Index(
                        fields=["gattung_deutsch"],
                        name="flexibi_ham_gattung_7a939c_idx",
                    ),
                    models.Index(
                        fields=["pflanzjahr"], name="flexibi_ham_pflanzj_0ac23c_idx"
                    ),
                    models.Index(
                        fields=["stammumfang"], name="flexibi_ham_stammum_f1ca86_idx"
                    ),
                    models.Index(
                        fields=["bezirk"], name="flexibi_ham_bezirk_e41bc8_idx"
                    ),
                ],
            },
        ),
    ]
