from sources.contracts import (
    SourceDomainExplorerCard,
    SourceDomainPlugin,
    SourceDomainPublicMount,
)

plugin = SourceDomainPlugin(
    slug="waste_collection",
    verbose_name="Waste Collection",
    app_config="sources.waste_collection.apps.WasteCollectionConfig",
    urlconf="sources.waste_collection.urls",
    capabilities=(
        "api",
        "exports",
        "forms",
        "html_views",
        "signals",
        "tasks",
        "templates",
    ),
    published_count_getter="sources.waste_collection.selectors.published_collection_count",
    public_mount=SourceDomainPublicMount(
        mount_path="waste_collection/",
        urlconf="sources.waste_collection.urls",
    ),
    sitemap_items=(
        "/waste_collection/",
        "/waste_collection/collectors/",
        "/waste_collection/collectors/create/",
        "/waste_collection/collectors/create/modal/",
        "/waste_collection/collectors/options/",
        "/waste_collection/collectors/autocomplete/",
        "/waste_collection/collectionsystems/",
        "/waste_collection/collectionsystems/create/",
        "/waste_collection/collectionsystems/create/modal/",
        "/waste_collection/collectionsystems/options/",
        "/waste_collection/wastecategories/",
        "/waste_collection/wastecategories/create/",
        "/waste_collection/wastecategories/create/modal/",
        "/waste_collection/wastecategories/options/",
        "/waste_collection/wastecomponents/",
        "/waste_collection/wastecomponents/create/",
        "/waste_collection/wastecomponents/create/modal/",
        "/waste_collection/frequencies/",
        "/waste_collection/frequencies/autocomplete/",
        "/waste_collection/frequencies/create/",
        "/waste_collection/frequencies/options/",
        "/waste_collection/properties/create/",
        "/waste_collection/properties/aggregated/create/",
        "/waste_collection/flyers/",
        "/waste_collection/flyers/create/",
        "/waste_collection/flyers/create/modal/",
        "/waste_collection/flyers/list/check_urls/",
        "/waste_collection/collections/",
        "/waste_collection/collections/create/",
        "/waste_collection/collections/autocomplete/",
        "/waste_collection/collections/map/",
        "/waste_collection/catchment_selection/",
        "/waste_collection/collections/export/",
    ),
    explorer_card=SourceDomainExplorerCard(
        title="Household Waste Collection",
        description=(
            "Collection system parameters, waste streams, frequencies, and container "
            "types that determine biowaste volumes from households."
        ),
        url_name="collection-list",
        image_path="img/waste_collection_cover_card.png",
        image_alt="Household waste collection cover image",
        icon_class="fas fa-fw fa-recycle",
        order=10,
    ),
)
