# Generated by Django 3.2.8 on 2021-12-03 09:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyBaseObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('heated', models.BooleanField(blank=True, null=True)),
                ('lighted', models.BooleanField(blank=True, null=True)),
                ('high_wire', models.BooleanField(blank=True, null=True)),
                ('above_ground', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GreenhouseGrowthCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(default=0.0)),
                ('standard_deviation', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NantesGreenhouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id_exp', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_exp', models.CharField(blank=True, max_length=255, null=True)),
                ('id_serre', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('surface_ha', models.FloatField(blank=True, null=True)),
                ('nb_cycles', models.IntegerField(blank=True, null=True)),
                ('culture_1', models.CharField(blank=True, max_length=255, null=True)),
                ('start_cycle_1', models.CharField(blank=True, max_length=255, null=True)),
                ('end_cycle_1', models.CharField(blank=True, max_length=255, null=True)),
                ('culture_2', models.CharField(blank=True, max_length=255, null=True)),
                ('start_cycle_2', models.CharField(blank=True, max_length=255, null=True)),
                ('end_cycle_2', models.CharField(blank=True, max_length=255, null=True)),
                ('culture_3', models.CharField(blank=True, max_length=255, null=True)),
                ('start_cycle_3', models.CharField(blank=True, max_length=20, null=True)),
                ('end_cycle_3', models.CharField(blank=True, max_length=255, null=True)),
                ('layer', models.CharField(blank=True, max_length=255, null=True)),
                ('heated', models.BooleanField(blank=True, null=True)),
                ('lighted', models.BooleanField(blank=True, null=True)),
                ('high_wire', models.BooleanField(blank=True, null=True)),
                ('above_ground', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthTimeStepSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='flexibi_nantes.greenhousegrowthcycle')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to=settings.AUTH_USER_MODEL)),
                ('timestep',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributions.timestep')),
            ],
        ),
    ]
