# Generated by Django 3.0.7 on 2020-11-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_nantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='cycles',
            field=models.IntegerField(null=True),
        ),
    ]
