# Generated by Django 3.2.10 on 2022-03-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flexibi_nantes', '0001_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthshare',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialcomponent'),
        ),
        migrations.AddField(
            model_name='growthshare',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='growthshare',
            name='timestepset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexibi_nantes.growthtimestepset'),
        ),
        migrations.AddField(
            model_name='greenhousegrowthcycle',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexibi_nantes.culture'),
        ),
        migrations.AddField(
            model_name='greenhousegrowthcycle',
            name='greenhouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexibi_nantes.greenhouse'),
        ),
        migrations.AddField(
            model_name='greenhousegrowthcycle',
            name='group_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.composition'),
        ),
        migrations.AddField(
            model_name='greenhousegrowthcycle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='culture',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='culture',
            name='residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.sampleseries'),
        ),
        migrations.AddField(
            model_name='casestudybaseobjects',
            name='reference_distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='distributions.temporaldistribution'),
        ),
    ]
