# Generated by Django 3.0.7 on 2021-02-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('material_manager', '0001_initial'),
        ('flexibi_nantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhousegrowthcycle',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='material_manager.MaterialComponent'),
        ),
        migrations.AlterField(
            model_name='greenhousegrowthcycle',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='material_manager.Material'),
        ),
    ]
