# Generated by Django 3.0.7 on 2020-11-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexibi_nantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousegrowthcycle',
            name='cycle_number',
            field=models.IntegerField(default=1),
        ),
    ]
