# Generated by Django 3.0.7 on 2021-02-21 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0002_auto_20210218_1640'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexibi_nantes', '0002_auto_20210218_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                            to=settings.AUTH_USER_MODEL)),
                ('residue',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Material')),
            ],
        ),
    ]
