# Generated by Django 3.0.7 on 2020-11-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0005_inventoryalgorithm_source_module'),
        ('flexibi_nantes', '0002_greenhouse_cycles'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='feedstock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.Material'),
        ),
    ]
