# Generated by Django 3.0.7 on 2020-11-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0005_inventoryalgorithm_source_module'),
        ('flexibi_nantes', '0003_greenhouse_feedstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhouse',
            name='feedstock',
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='cycle1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='scenario_builder.Material'),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='cycle2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='scenario_builder.Material'),
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='cycle3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='scenario_builder.Material'),
        ),
    ]
