# Generated by Django 5.1.1 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexibi_nantes', '0003_culture_created_at_culture_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['name', 'id']},
        ),
    ]
