# Generated by Django 3.0.7 on 2021-02-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('material_manager', '0002_auto_20210218_1640'),
        ('flexibi_nantes', '0004_auto_20210221_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthtimestepset',
            name='group_settings',
        ),
        migrations.AddField(
            model_name='greenhousegrowthcycle',
            name='group_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='material_manager.MaterialComponentGroupSettings'),
        ),
        migrations.AddField(
            model_name='growthtimestepset',
            name='growth_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='flexibi_nantes.GreenhouseGrowthCycle'),
        ),
    ]
