from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexibi_nantes', '0004_alter_culture_publication_status_and_more'),
        ('greenhouses', '0001_move_legacy_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='casestudybaseobjects',
                            name='reference_distribution',
                        ),
                        migrations.RemoveField(
                            model_name='culture',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='culture',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='culture',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='culture',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='culture',
                            name='residue',
                        ),
                        migrations.RemoveField(
                            model_name='greenhousegrowthcycle',
                            name='culture',
                        ),
                        migrations.RemoveField(
                            model_name='greenhouse',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='greenhouse',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='greenhouse',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='greenhouse',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='greenhousegrowthcycle',
                            name='greenhouse',
                        ),
                        migrations.RemoveField(
                            model_name='greenhousegrowthcycle',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='greenhousegrowthcycle',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='greenhousegrowthcycle',
                            name='group_settings',
                        ),
                        migrations.RemoveField(
                            model_name='greenhousegrowthcycle',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='greenhousegrowthcycle',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='growthtimestepset',
                            name='growth_cycle',
                        ),
                        migrations.RemoveField(
                            model_name='growthshare',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='growthshare',
                            name='component',
                        ),
                        migrations.RemoveField(
                            model_name='growthshare',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='growthshare',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='growthshare',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='growthshare',
                            name='timestepset',
                        ),
                        migrations.RemoveField(
                            model_name='growthtimestepset',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='growthtimestepset',
                            name='timestep',
                        ),
                        migrations.DeleteModel(
                            name='NantesGreenhouses',
                        ),
                        migrations.DeleteModel(
                            name='CaseStudyBaseObjects',
                        ),
                        migrations.DeleteModel(
                            name='Culture',
                        ),
                        migrations.DeleteModel(
                            name='Greenhouse',
                        ),
                        migrations.DeleteModel(
                            name='GreenhouseGrowthCycle',
                        ),
                        migrations.DeleteModel(
                            name='GrowthShare',
                        ),
                        migrations.DeleteModel(
                            name='GrowthTimeStepSet',
                        ),
            ],
        )
    ]
