# Generated by Django 3.0.7 on 2020-11-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0006_auto_20201113_1553'),
        ('flexibi_nantes', '0004_auto_20201113_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='cycle2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='scenario_builder.Material'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='cycle3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='scenario_builder.Material'),
        ),
    ]
