# Generated by Django 3.0.7 on 2020-11-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0006_auto_20201113_1553'),
        ('flexibi_nantes', '0005_auto_20201113_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenhouse',
            name='seasonal_distribution',
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='seasonal_distributions',
            field=models.ManyToManyField(to='scenario_builder.SeasonalDistribution'),
        ),
    ]
