# Generated by Django 3.0.7 on 2021-02-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_nantes', '0005_auto_20210221_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
