# Generated by Django 3.0.7 on 2021-02-22 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexibi_nantes', '0006_greenhouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousegrowthcycle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
