# Generated by Django 3.0.7 on 2020-11-13 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_nantes', '0006_auto_20201113_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenhouse',
            old_name='cycles',
            new_name='nb_cycles',
        ),
    ]
