# Generated by Django 3.0.7 on 2020-11-13 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_nantes', '0007_auto_20201113_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greenhouse',
            old_name='cycle1',
            new_name='culture_1',
        ),
        migrations.RenameField(
            model_name='greenhouse',
            old_name='cycle2',
            new_name='culture_2',
        ),
        migrations.RenameField(
            model_name='greenhouse',
            old_name='cycle3',
            new_name='culture_3',
        ),
    ]
