# Generated by Django 3.0.7 on 2021-02-22 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_nantes', '0007_greenhousegrowthcycle_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthshare',
            old_name='timestep_set',
            new_name='timestepset',
        ),
    ]
