# Generated by Django 3.0.7 on 2020-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_nantes', '0008_auto_20201113_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='culture_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='culture_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='culture_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
