# Generated by Django 3.0.7 on 2021-02-22 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_nantes', '0009_culture_feedstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='residue',
        ),
    ]
