# Generated by Django 3.0.7 on 2021-03-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_dst', '0001_initial'),
        ('flexibi_nantes', '0011_auto_20210222_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyBaseObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                             to='flexibi_dst.TemporalDistribution')),
            ],
        ),
    ]
