# Generated by Django 3.2.8 on 2021-10-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('distributions', '0002_auto_20211029_1313'),
        ('flexibi_nantes', '0012_casestudybaseobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudybaseobjects',
            name='reference_distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='distributions.temporaldistribution'),
        ),
        migrations.AlterField(
            model_name='growthtimestepset',
            name='timestep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributions.timestep'),
        ),
    ]
