# Generated by Django 3.2.10 on 2022-03-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenceUsers',
        ),
    ]
