# Generated by Django 6.0.3 on 2026-04-08 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("greenhouses", "0003_rename_greenhouses_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="greenhousegrowthcycle",
                    new_name="greenhouses_publica_69a27c_idx",
                    old_name="flexibi_nan_publica_d66165_idx",
                ),
                migrations.RenameIndex(
                    model_name="growthshare",
                    new_name="greenhouses_publica_459799_idx",
                    old_name="flexibi_nan_publica_3516d7_idx",
                ),
            ],
        ),
        migrations.AlterModelTable(
            name="casestudybaseobjects",
            table=None,
        ),
        migrations.AlterModelTable(
            name="culture",
            table=None,
        ),
        migrations.AlterModelTable(
            name="greenhouse",
            table=None,
        ),
        migrations.AlterModelTable(
            name="greenhousegrowthcycle",
            table=None,
        ),
        migrations.AlterModelTable(
            name="growthshare",
            table=None,
        ),
        migrations.AlterModelTable(
            name="growthtimestepset",
            table=None,
        ),
        migrations.AlterModelTable(
            name="nantesgreenhouses",
            table=None,
        ),
    ]
