version: '3.3'

services:
  db:
    image: "postgis/postgis:12-master"
    ports:
      - "5433:5432"
    volumes:
      - flexibi_db/:/var/lib/postgresql/data/
    env_file:
      - flexibi_dst/settings/.env
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - flexibi_dst/settings/.env
    links:
      - db
    profiles: ["dev"]
  celery:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: celery --app=flexibi_dst worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./:/app
    env_file:
      - flexibi_dst/settings/.env
    depends_on:
      - web
      - redis
    profiles: [ "dev" ]
  redis:
    image: redis:5-alpine
    profiles: ["dev"]
  db_admin:
    build:
      context: ./docker/db_admin/
    env_file:
      - flexibi_dst/settings/.env
    depends_on:
      - db
    profiles: ["db_admin"]
#  dashboard:
#    build: .
#    command: flower -A flexibi_dst --port=5555 --broker=redis://redis:6379/0
#    ports:
#      - 5555:5555
#    env_file:
#      - flexibi_dst/settings/.env
#    depends_on:
#      - web
#      - redis
#      - celery

volumes:
  flexibi_db:
