version: '3.3'

services:
  db:
    image: "postgis/postgis:12-master"
    ports:
      - "5433:5432"
    volumes:
      - flexibi_db/:/var/lib/postgresql/data/
    env_file:
      - flexibi_dst/settings/.env
  web:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - flexibi_dst/settings/.env
    links:
      - db
  celery:
    build: .
    command: celery worker --app=flexibi_dst --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./:/app
    env_file:
      - flexibi_dst/settings/.env
    depends_on:
      - web
      - redis
  redis:
    image: redis:5-alpine
  dashboard:
    build: .
    command: flower -A flexibi_dst --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - flexibi_dst/settings/.env
    depends_on:
      - web
      - redis
      - celery

volumes:
  flexibi_db:
