version: '3.3'

services:
  db:
    image: "postgis/postgis:12-master"
    ports:
      - "5433:5432"
    volumes:
      - brit_db/:/var/lib/postgresql/data/
    env_file:
      - brit/settings/.env
  web:
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - brit/settings/.env
    links:
      - db
  celery:
    build:
      context: .
    command: celery --app=brit worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./:/app
    env_file:
      - brit/settings/.env
    depends_on:
      - web
      - redis
  redis:
    image: redis:5-alpine
  db_admin:
    build:
      context: ./docker/db_admin/
    env_file:
      - brit/settings/.env
    depends_on:
      - db
    profiles: [ "db_admin" ]
#  dashboard:
#    build: .
#    command: flower -A brit --port=5555 --broker=redis://redis:6379/0
#    ports:
#      - 5555:5555
#    env_file:
#      - brit/settings/.env
#    depends_on:
#      - web
#      - redis
#      - celery

volumes:
  brit_db:
