site_name: BRIT Documentation

nav:
  - Home: 01_user_guide/README.md
  - User Guide:
      - Overview: 01_user_guide/README.md
      - How-Tos: 01_user_guide/howtos.md
  - Developer Guide:
      - Overview: 02_developer_guide/README.md
      - Guidelines: 02_developer_guide/guidelines.md
      - Style Guide: 02_developer_guide/style_guide.md
      - Applications: 02_developer_guide/applications.md
      - API: 02_developer_guide/api.md
      - Architecture:
          - Overview: 02_developer_guide/architecture.md
          - Data Flow: 02_developer_guide/architecture/data_flow.md
          - Deployment: 02_developer_guide/architecture/deployment.md
  - Operations:
      - Overview: 03_operations/README.md
      - Operations Guide: 03_operations/operations.md
  - Design Decisions:
      - Overview: 04_design_decisions/README.md

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.superfences

plugins:
  - search

# Development server settings
dev_addr: localhost:8001
