# Generated by Django 4.2.8 on 2024-07-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_publication_status_unit_publication_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name']},
        ),
    ]
