# Generated by Django 5.2.4 on 2026-02-04 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_property_publication_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={},
        ),
    ]
