# Generated by Django 5.1.1 on 2024-11-16 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0003_alter_property_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='visible_to_groups',
        ),
    ]
