# Generated by Django 5.2.4 on 2026-02-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_alter_property_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="symbol",
            field=models.CharField(
                blank=True,
                help_text="Pint-compatible unit symbol (e.g. kg, mg/L, percent).",
                max_length=63,
            ),
        ),
    ]
