# Generated by Django 5.1.1 on 2024-12-13 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0004_remove_property_visible_to_groups_and_more'),
        ('soilcom', '0032_remove_aggregatedcollectionpropertyvalue_visible_to_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='PropertyUnit',
        ),
    ]
