# Generated by Django 5.2.4 on 2026-02-17 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_alter_property_publication_status_and_more"),
        ("properties", "0005_unit_symbol"),
    ]

    operations = []
