# Generated by Django 6.0.4 on 2026-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_alter_property_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=63),
        ),
    ]
