# Generated by Django 6.0.8 on 2026-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_collection_point_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="unit",
        ),
    ]
