# Generated by Django 6.0.8 on 2026-09-22 11:52

from django.conf import settings
from django.db import migrations
from django.db.models import Q


def resolve_or_create_unit(Unit, User, label, owner_id):
    """Match a legacy free-text unit label to a Unit by name or symbol,
    scoped to the owner first, creating a Unit for the owner if none exists."""
    normalized = (label or "").strip()
    if not normalized:
        return None

    filters = Q(name=normalized) | Q(symbol=normalized)
    if owner_id is not None:
        unit = Unit.objects.filter(owner_id=owner_id).filter(filters).first()
        if unit is not None:
            return unit
    unit = Unit.objects.filter(filters).first()
    if unit is not None:
        return unit

    if owner_id is None:
        username = getattr(settings, "DEFAULT_OWNER_USERNAME", "flexibi")
        owner, _ = User.objects.get_or_create(
            username=username, defaults={"is_active": True}
        )
        owner_id = owner.pk
    unit, _ = Unit.objects.get_or_create(
        owner_id=owner_id,
        name=normalized,
        defaults={"symbol": normalized if len(normalized) <= 63 else ""},
    )
    return unit


def backfill_allowed_units_from_legacy_label(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    Unit = apps.get_model("properties", "Unit")
    User = apps.get_model("auth", "User")

    for prop in Property.objects.exclude(unit="").filter(allowed_units__isnull=True):
        unit = resolve_or_create_unit(Unit, User, prop.unit, prop.owner_id)
        if unit is not None:
            prop.allowed_units.add(unit)


def restore_legacy_label_from_allowed_units(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    for prop in Property.objects.filter(unit=""):
        unit = prop.allowed_units.first()
        if unit is not None:
            prop.unit = unit.name[:63]
            prop.save(update_fields=["unit"])


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_collection_point_property"),
    ]

    operations = [
        migrations.RunPython(
            backfill_allowed_units_from_legacy_label,
            restore_legacy_label_from_allowed_units,
        ),
        migrations.RemoveField(
            model_name="property",
            name="unit",
        ),
    ]
