# Generated by Django 3.0.7 on 2021-02-17 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions', '0001_initial'),
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_feedstock', models.BooleanField(default=False)),
                ('stan_flow_id', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(code='invalid_stan_id', message='STAN id must have 5 digits.s', regex='^[0-9]{5}?')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='MaterialComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'component',
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='MaterialComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'material_component_group',
                'verbose_name_plural': 'groups',
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='MaterialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Customization', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponentShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(default=0.0)),
                ('standard_deviation', models.FloatField(default=0.0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialComponent')),
                ('composition_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.CompositionSet')),
                ('owner', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponentGroupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fractions_of', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                                   to='materials.MaterialComponent')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='materials.MaterialComponentGroup')),
                ('material_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                        to='materials.MaterialSettings')),
                ('owner', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE,
                                            to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(to='bibliography.LiteratureSource')),
                ('temporal_distributions', models.ManyToManyField(to='distributions.TemporalDistribution')),
            ],
        ),
        migrations.AddField(
            model_name='compositionset',
            name='group_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialComponentGroupSettings'),
        ),
        migrations.AddField(
            model_name='compositionset',
            name='owner',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compositionset',
            name='timestep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='distributions.Timestep'),
        ),
        migrations.CreateModel(
            name='BaseObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                     to='materials.MaterialComponent')),
                ('base_distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                        to='distributions.TemporalDistribution')),
                ('base_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                 to='materials.MaterialComponentGroup')),
                ('base_timestep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                    to='distributions.Timestep')),
            ],
        ),
    ]
