# Generated by Django 3.0.7 on 2021-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='is_feedstock',
            field=models.BooleanField(default=True),
        ),
    ]
