# Generated by Django 3.2.10 on 2022-03-30 10:29
import re

from django.db import migrations

from users.models import get_default_owner


def create_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    owner = User.objects.get(username=get_default_owner().username)
    MaterialComponentGroup = apps.get_model('materials', 'MaterialComponentGroup')
    group, _ = MaterialComponentGroup.objects.get_or_create(name='Total Material', owner=owner)
    MaterialComponent = apps.get_model('materials', 'MaterialComponent')
    component, _ = MaterialComponent.objects.get_or_create(name='Fresh Matter (FM)', owner=owner)
    other, _ = MaterialComponent.objects.get_or_create(name='Other', owner=owner)

    Group = apps.get_model('auth', 'Group')

    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model('auth', 'Permission')

    models = [
        'MaterialCategory', 'Material', 'MaterialComponent', 'MaterialComponentGroup', 'SampleSeries',
        'MaterialProperty', 'MaterialPropertyValue', 'Sample', 'Composition', 'Weightshare'
    ]
    permission_prefixes = ['add', 'view', 'change', 'delete']

    editors, _ = Group.objects.get_or_create(name='editors')
    for model in models:
        model_class = apps.get_model('materials', model)
        content_type = ContentType.objects.get_for_model(model_class, for_concrete_model=False)
        verbose_name = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", str(model_class.__name__)).lower()

        for prefix in permission_prefixes:
            codename = f'{prefix}_{model_class._meta.model_name}'
            name = f'Can {prefix} {verbose_name}'
            permission, _ = Permission.objects.get_or_create(
                codename=codename,
                content_type=content_type,
                defaults={'name': name})
            editors.permissions.add(permission)




class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0001_initial_data')
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
