# Generated by Django 3.2.10 on 2022-04-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialcomponentgroup',
            options={},
        ),
    ]
