# Generated by Django 3.2.10 on 2022-09-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import brit.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0003_auto_20220421_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basematerial',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='composition',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialcomponentgroup',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialproperty',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialpropertyvalue',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampleseries',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weightshare',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
