# Generated by Django 5.2.4 on 2026-02-06 15:36

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import utils.object_management.models
import utils.properties.models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0003_alter_author_publication_status_and_more"),
        ("materials", "0003_alter_analyticalmethod_publication_status_and_more"),
        ("properties", "0004_alter_property_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialproperty",
            options={},
        ),
        migrations.AddField(
            model_name="basematerial",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="Short abbreviation or acronym for this material/component.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="basematerial",
            name="basis_component",
            field=models.ForeignKey(
                blank=True,
                help_text="Basis component for this component (e.g. Dry Matter). Only used for components.",
                limit_choices_to={"type": "component"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_components",
                to="materials.basematerial",
            ),
        ),
        migrations.AddField(
            model_name="basematerial",
            name="component_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single component"),
                    ("aggregate", "Aggregate component"),
                ],
                default="single",
                help_text="Only used for material components: single components versus aggregate groups.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="materialproperty",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="materialproperty",
            name="aggregation_kind",
            field=models.CharField(
                choices=[
                    ("mass_related", "Mass-related"),
                    ("non_mass_related", "Non mass-related"),
                ],
                default="non_mass_related",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="materialproperty",
            name="allowed_units",
            field=models.ManyToManyField(
                blank=True,
                help_text="Units that are acceptable for this property.",
                to="properties.unit",
            ),
        ),
        migrations.AddField(
            model_name="materialproperty",
            name="default_basis_component",
            field=models.ForeignKey(
                blank=True,
                help_text="Mass basis component used to normalize this property (e.g. Dry Matter).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_basis_properties",
                to="materials.materialcomponent",
            ),
        ),
        migrations.AddField(
            model_name="materialpropertyvalue",
            name="analytical_method",
            field=models.ForeignKey(
                blank=True,
                help_text="Analytical method used for this measurement.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="materials.analyticalmethod",
            ),
        ),
        migrations.AddField(
            model_name="materialpropertyvalue",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sources or references for this measurement.",
                to="bibliography.source",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="analysis_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when the analysis was performed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="analysis_laboratory",
            field=models.CharField(
                blank=True,
                help_text="Laboratory where the analysis was performed.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="analysis_objective",
            field=models.TextField(
                blank=True, help_text="Objective or purpose of the analysis."
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="lab_accreditation",
            field=models.CharField(
                blank=True,
                help_text="Laboratory accreditation information.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="standalone",
            field=models.BooleanField(
                default=False,
                help_text="True if this sample is not part of a sample series.",
            ),
        ),
        migrations.AlterField(
            model_name="materialpropertyvalue",
            name="average",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name="materialpropertyvalue",
            name="standard_deviation",
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.CreateModel(
            name="ComponentMeasurement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last modified at",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("review", "Under Review"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                            ("archived", "Archived"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "average",
                    models.DecimalField(
                        decimal_places=10, default=Decimal("0.0"), max_digits=20
                    ),
                ),
                (
                    "standard_deviation",
                    models.DecimalField(
                        decimal_places=10, default=Decimal("0.0"), max_digits=20
                    ),
                ),
                (
                    "sample_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of samples/replicates (n) used for the measurement.",
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Additional comments about the measurement.",
                    ),
                ),
                (
                    "analytical_method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Analytical method used for this measurement.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="materials.analyticalmethod",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "basis_component",
                    models.ForeignKey(
                        blank=True,
                        help_text="Basis component for the measurement (e.g. Dry Matter).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basis_component_measurements",
                        to="materials.materialcomponent",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_measurements",
                        to="materials.materialcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Grouping domain for the measurement (e.g. chemical elements).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_measurements",
                        to="materials.materialcomponentgroup",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=utils.object_management.models.get_default_owner_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        help_text="The sample these measurements belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_measurements",
                        to="materials.sample",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sources or references for this measurement.",
                        to="bibliography.source",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        default=utils.properties.models.get_default_unit_pk,
                        help_text="Unit for the measured value (e.g. %, g/kg).",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["component__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialPropertyGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last modified at",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("review", "Under Review"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                            ("archived", "Archived"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=utils.object_management.models.get_default_owner_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "owner")},
            },
        ),
        migrations.AddField(
            model_name="materialproperty",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Aggregation domain used to avoid double-counting overlapping measurements.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="materials.materialpropertygroup",
            ),
        ),
    ]
