# Generated by Django 3.2.10 on 2022-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20220924_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleseries',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
