# Generated by Django 3.0.7 on 2021-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20210510_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsettings',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
