# Generated by Django 5.2.4 on 2026-02-06 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0003_alter_author_publication_status_and_more"),
        ("materials", "0004_alter_materialproperty_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialpropertyvalue",
            options={},
        ),
        migrations.RemoveField(
            model_name="materialpropertyvalue",
            name="description",
        ),
        migrations.RemoveField(
            model_name="materialpropertyvalue",
            name="name",
        ),
        migrations.AddIndex(
            model_name="materialpropertyvalue",
            index=models.Index(
                fields=["publication_status"], name="materials_m_publica_588a3d_idx"
            ),
        ),
    ]
