# Generated by Django 5.2.4 on 2026-02-13 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.properties.models


def ensure_default_unit(apps, schema_editor):
    """Create the default owner user and 'No unit' Unit if they don't exist yet."""
    User = apps.get_model("auth", "User")
    Unit = apps.get_model("properties", "Unit")
    username = getattr(settings, "DEFAULT_OWNER_USERNAME", "flexibi")
    user, _ = User.objects.get_or_create(
        username=username, defaults={"is_active": True}
    )
    unit_name = getattr(settings, "DEFAULT_NO_UNIT_NAME", "No unit")
    Unit.objects.get_or_create(name=unit_name, owner=user)


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0005_remove_materialpropertyvalue_name_description"),
        ("properties", "0005_unit_symbol"),
    ]

    operations = [
        migrations.RunPython(ensure_default_unit, migrations.RunPython.noop),
        migrations.AddField(
            model_name="materialpropertyvalue",
            name="unit",
            field=models.ForeignKey(
                default=utils.properties.models.get_default_unit_pk,
                help_text="Unit for the measured value.",
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.unit",
            ),
        ),
    ]
