# Generated by Django 5.2.4 on 2026-02-17 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0005_alter_analyticalmethod_publication_status_and_more"),
        ("materials", "0006_materialpropertyvalue_unit"),
    ]

    operations = []
