# Generated by Django 4.0.10 on 2023-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0006_alter_basematerial_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/material_samples/'),
        ),
        migrations.AlterField(
            model_name='sampleseries',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/material_sample_series/'),
        ),
    ]
