# Generated by Django 3.2.8 on 2021-10-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('distributions', '0001_initial'),
        ('materials', '0007_auto_20211020_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseobjects',
            name='base_distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='distributions.temporaldistribution'),
        ),
        migrations.AlterField(
            model_name='baseobjects',
            name='base_timestep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='distributions.timestep'),
        ),
        migrations.AlterField(
            model_name='compositionset',
            name='timestep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='distributions.timestep'),
        ),
        migrations.AlterField(
            model_name='materialcomponentgroupsettings',
            name='temporal_distributions',
            field=models.ManyToManyField(to='distributions.TemporalDistribution'),
        ),
    ]
