# Generated by Django 6.0.3 on 2026-03-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0007_merge_20260217_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="basematerial",
            name="comparable_component",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical component this raw term should be compared as. Only used for components.",
                limit_choices_to={"type": "component"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comparable_variants",
                to="materials.basematerial",
            ),
        ),
    ]
