# Generated by Django 4.2.8 on 2024-03-26 15:57

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_basematerial_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='fractions_of',
            field=models.ForeignKey(default=materials.models.get_default_component_pk, on_delete=django.db.models.deletion.PROTECT, to='materials.materialcomponent'),
        ),
    ]
