# Generated by Django 3.2.8 on 2021-11-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20211108_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialgroup',
            options={'verbose_name': 'Material Group'},
        ),
    ]
