# Generated by Django 4.2.8 on 2024-07-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_composition_fractions_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='materialproperty',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='materialpropertyvalue',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sampleseries',
            options={'ordering': ['name']},
        ),
    ]
