# Generated by Django 5.1.1 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_composition_fractions_of'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='materialproperty',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='materialpropertyvalue',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sampleseries',
            options={'ordering': ['name', 'id']},
        ),
    ]
