# Generated by Django 6.0.3 on 2026-03-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0009_materialproperty_comparable_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialpropertyvalue",
            name="basis_component",
            field=models.ForeignKey(
                blank=True,
                help_text="Basis component for the property value (e.g. Dry Matter).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="basis_property_values",
                to="materials.materialcomponent",
            ),
        ),
    ]
