# Generated by Django 3.2.8 on 2021-11-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_alter_materialgroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material'},
        ),
    ]
