# Generated by Django 6.0.3 on 2026-04-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0009_rename_source_bibtex_fields"),
        ("materials", "0011_make_standard_deviation_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticalmethod",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="References for this analytical method.",
                to="bibliography.source",
            ),
        ),
        migrations.AlterField(
            model_name="componentmeasurement",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="References for this measurement.",
                to="bibliography.source",
            ),
        ),
        migrations.AlterField(
            model_name="materialpropertyvalue",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="References for this measurement.",
                to="bibliography.source",
            ),
        ),
    ]
