# Generated by Django 3.2.8 on 2021-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_alter_material_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='materials.MaterialGroup'),
        ),
    ]
