# Generated by Django 5.1.1 on 2024-11-29 09:13

import django.db.models.deletion
import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0009_remove_period_visible_to_groups_and_more'),
        ('materials', '0013_remove_basematerial_visible_to_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='preview',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sampleseries',
            old_name='preview',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='taken_at',
        ),
        migrations.AddField(
            model_name='sample',
            name='datetime',
            field=models.DateTimeField(blank=True, help_text='Choose 00:00 if time is unknown.', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.CharField(blank=True, help_text='Name of town, address or coordinates', max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='material',
            field=models.ForeignKey(default=materials.models.get_default_material_pk, help_text='If no option fits, please choose "Other" and specify the material in the description.', on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='series',
            field=models.ForeignKey(blank=True, help_text='If this sample belongs to a sample series or campaign, select it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='materials.sampleseries'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='timestep',
            field=models.ForeignKey(blank=True, help_text='If the sample represents a specific time step in a series, select it here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='distributions.timestep'),
        ),
        migrations.AlterField(
            model_name='sampleseries',
            name='material',
            field=models.ForeignKey(default=materials.models.get_default_material_pk, on_delete=django.db.models.deletion.PROTECT, related_name='sample_series', to='materials.material'),
        ),
    ]
