# Generated by Django 5.1.1 on 2024-12-12 16:57

import django.db.models.deletion
import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_rename_preview_sample_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcomponent',
            options={'ordering': ['name'], 'verbose_name': 'component'},
        ),
        migrations.AlterField(
            model_name='composition',
            name='fractions_of',
            field=models.ForeignKey(default=materials.models.get_default_component_pk, help_text='The component that the weight fractions of this composition are fractions of. Must be a component that is already defined.', on_delete=django.db.models.deletion.PROTECT, to='materials.materialcomponent'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='group',
            field=models.ForeignKey(help_text='The group of components that this composition is part of. Typically determined by type of analysis.', on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='materials.materialcomponentgroup'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='sample',
            field=models.ForeignKey(help_text='The sample that this composition is part of.', on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='materials.sample'),
        ),
    ]
