# Generated by Django 6.0.4 on 2026-04-29 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0015_alter_materialcategory_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeightShare",
        ),
    ]
