# Generated by Django 6.0.4 on 2026-04-30 00:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0016_delete_weightshare"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="basematerial",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("type"),
                condition=models.Q(("publication_status", "published")),
                name="materials_basematerial_unique_published_name_type",
            ),
        ),
    ]
