# Generated by Django 6.0.4 on 2026-05-06 14:41

from django.db import migrations, models


def clear_materialproperty_unit_field(apps, schema_editor):
    """
    Blank out the legacy unit text field on all MaterialProperty rows.
    The structured allowed_units M2M relation is now the authoritative source;
    the char field is redundant and will be removed in a future migration.
    """
    MaterialProperty = apps.get_model("materials", "MaterialProperty")
    MaterialProperty.objects.all().update(unit="")


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0018_materialproperty_configure_allowed_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialproperty",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=63),
        ),
        migrations.RunPython(
            clear_materialproperty_unit_field,
            migrations.RunPython.noop,
        ),
    ]
