# Generated by Django 6.0.8 on 2026-09-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0020_sample_image_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="analysis_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the laboratory analysis was performed. Choose 00:00 if the time is unknown.",
                null=True,
                verbose_name="analysis date/time",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="When the sample was taken. Choose 00:00 if the time is unknown.",
                null=True,
                verbose_name="sampling date/time",
            ),
        ),
    ]
