# Generated by Django 6.0.8 on 2026-09-11 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0022_sample_datetime_precision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basematerial",
            name="component_kind",
        ),
    ]
