# Generated by Django 6.0.8 on 2026-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0025_alter_basematerial_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="basematerial",
            name="is_aggregate",
            field=models.BooleanField(
                default=False,
                help_text="Component totals its sibling components within a component group (e.g. 'Total (with halides)'). Aggregates are excluded from normalized compositions. Only used for components.",
            ),
        ),
    ]
