# Generated by Django 6.0.8 on 2026-09-22 11:52

from importlib import import_module

from django.db import migrations

resolve_or_create_unit = import_module(
    "utils.properties.migrations.0010_remove_property_unit"
).resolve_or_create_unit


def backfill_allowed_units_from_legacy_label(apps, schema_editor):
    MaterialProperty = apps.get_model("materials", "MaterialProperty")
    Unit = apps.get_model("properties", "Unit")
    User = apps.get_model("auth", "User")

    for prop in MaterialProperty.objects.exclude(unit="").filter(
        allowed_units__isnull=True
    ):
        unit = resolve_or_create_unit(Unit, User, prop.unit, prop.owner_id)
        if unit is not None:
            prop.allowed_units.add(unit)


def restore_legacy_label_from_allowed_units(apps, schema_editor):
    MaterialProperty = apps.get_model("materials", "MaterialProperty")
    for prop in MaterialProperty.objects.filter(unit=""):
        unit = prop.allowed_units.first()
        if unit is not None:
            prop.unit = unit.name[:63]
            prop.save(update_fields=["unit"])


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0027_materialcomponentgroup_is_compositional"),
        ("properties", "0010_remove_property_unit"),
    ]

    operations = [
        migrations.RunPython(
            backfill_allowed_units_from_legacy_label,
            restore_legacy_label_from_allowed_units,
        ),
        migrations.RemoveField(
            model_name="materialproperty",
            name="unit",
        ),
    ]
