# Generated by Django 6.0.8 on 2026-09-22 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import utils.object_management.models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0012_source_type_vocabulary"),
        ("materials", "0027_materialcomponentgroup_is_compositional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="series",
            field=models.ForeignKey(
                blank=True,
                help_text="Temporal series for samples of the same material at defined timesteps.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples",
                to="materials.sampleseries",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="standalone",
            field=models.BooleanField(
                default=False,
                help_text="True if this sample is not part of a temporal sample series. Standalone samples may still belong to sample groups.",
            ),
        ),
        migrations.CreateModel(
            name="SampleGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "lastmodified_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Last modified at",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                            ("archived", "Archived"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("study", "Study"),
                            ("experiment", "Experiment"),
                            ("sampling_campaign", "Sampling campaign"),
                            ("analysis", "Analysis"),
                            ("other", "Other"),
                        ],
                        default="study",
                        max_length=32,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lastmodified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_lastmodified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=utils.object_management.models.get_default_owner_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sample_groups",
                        to="bibliography.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "sample groups",
                "ordering": ["name", "id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Studies, experiments, campaigns, or analyses that relate this sample to other samples without implying a temporal series.",
                related_name="samples",
                to="materials.samplegroup",
            ),
        ),
    ]
