# Generated by Django 6.0.8 on 2026-09-22 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0027_materialcomponentgroup_is_compositional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialproperty",
            name="unit",
        ),
    ]
