# Generated by Django 6.0.8 on 2026-09-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0027_materialcomponentgroup_is_compositional"),
    ]

    operations = [
        migrations.AddField(
            model_name="basematerial",
            name="complement_component",
            field=models.ForeignKey(
                blank=True,
                help_text="Component that makes up the remainder to 100% on this component's basis (e.g. Organic Matter complements Total Ash on Dry Matter). Only used for components.",
                limit_choices_to={"type": "component"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="complements",
                to="materials.basematerial",
            ),
        ),
    ]
