# Generated by Django 6.0.8 on 2026-09-22 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0028_remove_materialproperty_unit"),
        ("materials", "0028_samplegroup_sample_sample_groups"),
    ]

    operations = []
