# Generated by Django 6.0.8 on 2026-10-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0019_region_name_en"),
        ("materials", "0029_merge_20260922_1559"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic region the sample was taken in. The free-text location field and the site field can hold finer detail.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples",
                to="maps.region",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Precise sampling site (address or coordinates) when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples",
                to="maps.location",
                verbose_name="sampling site",
            ),
        ),
    ]
