# Generated by Django 3.0.7 on 2021-01-03 14:12

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Custom Catchment', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('administrative', 'administrative'), ('custom', 'custom')],
                                          default='custom', max_length=14)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeoDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(choices=[('HamburgRoadsideTrees', 'HamburgRoadsideTrees'),
                                                         ('HamburgGreenAreas', 'HamburgGreenAreas'),
                                                         ('NantesGreenhouses', 'NantesGreenhouses')], max_length=56,
                                                null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('source_module', models.CharField(max_length=255, null=True)),
                ('function_name', models.CharField(max_length=56, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False,
                                                verbose_name='Default for this combination of geodataset and feedstock')),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAlgorithmParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_name', models.CharField(max_length=56)),
                ('short_name', models.CharField(max_length=28, validators=[
                    django.core.validators.RegexValidator(code='invalid_parameter_name',
                                                          message='Invalid parameter short_name. Do not use spaceor special characters.',
                                                          regex='^\\w{1,28}$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('inventory_algorithm', models.ManyToManyField(to='scenario_builder.InventoryAlgorithm')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAlgorithmParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('standard_deviation', models.FloatField(null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('default', models.BooleanField(default=False)),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='scenario_builder.InventoryAlgorithmParameter')),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('abbreviation', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_feedstock', models.BooleanField(default=False)),
                ('stan_flow_id', models.CharField(max_length=5, validators=[
                    django.core.validators.RegexValidator(code='invalid_stan_id',
                                                          message='STAN id must have 5 digits.s',
                                                          regex='^[0-9]{5}?')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponentGroupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic', models.BooleanField(default=False)),
                ('fractions_of', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                                   to='scenario_builder.MaterialComponent')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='scenario_builder.MaterialComponentGroup')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='scenario_builder.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('country', models.CharField(max_length=56)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Custom Scenario', max_length=56)),
                ('description', models.TextField(blank=True, null=True)),
                ('evaluation_running', models.BooleanField(default=False)),
                ('evaluated', models.BooleanField(default=False)),
                ('catchment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='scenario_builder.Catchment')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='scenario_builder.Region')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesteps', models.IntegerField(default=12)),
                ('cycles', models.IntegerField(default=1)),
                ('start_stop',
                 django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1, 12],
                                                           size=None)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(),
                                                                     default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                                                                     size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SFBSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Changed'), (2, 'Running'), (3, 'Finished')], default=1)),
                ('scenario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='scenario_builder.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioInventoryConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedstock',
                 models.ForeignKey(limit_choices_to={'is_feedstock': True}, on_delete=django.db.models.deletion.CASCADE,
                                   to='scenario_builder.Material')),
                ('geodataset',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.GeoDataset')),
                ('inventory_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          to='scenario_builder.InventoryAlgorithm')),
                ('inventory_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                          to='scenario_builder.InventoryAlgorithmParameter')),
                ('inventory_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      to='scenario_builder.InventoryAlgorithmParameterValue')),
                ('scenario',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.SFBSite'),
        ),
        migrations.CreateModel(
            name='MaterialComponentShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(blank=True, null=True)),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='scenario_builder.MaterialComponent')),
                ('distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='scenario_builder.SeasonalDistribution')),
                ('group_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='scenario_builder.MaterialComponentGroupSettings')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='scenario_builder.LiteratureSource')),
            ],
        ),
        migrations.AddField(
            model_name='materialcomponentgroupsettings',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.Scenario'),
        ),
        migrations.AddField(
            model_name='inventoryalgorithm',
            name='feedstock',
            field=models.ManyToManyField(limit_choices_to={'is_feedstock': True}, to='scenario_builder.Material'),
        ),
        migrations.AddField(
            model_name='inventoryalgorithm',
            name='geodataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.GeoDataset'),
        ),
        migrations.AddField(
            model_name='geodataset',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Region'),
        ),
        migrations.AddField(
            model_name='catchment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Region'),
        ),
    ]
