# Generated by Django 3.0.3 on 2020-05-13 10:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseScenarioResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('algorithm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='scenario_builder.InventoryAlgorithm')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='scenario_builder.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryResultPointLayer',
            fields=[
                ('basescenarioresult_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='scenario_builder.BaseScenarioResult')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('average', models.FloatField(null=True)),
                ('standard_deviation', models.FloatField(null=True)),
            ],
            bases=('scenario_builder.basescenarioresult',),
        ),
    ]
