# Generated by Django 3.0.3 on 2020-05-27 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='model_name',
            field=models.CharField(
                choices=[('HamburgRoadsideTrees', 'HamburgRoadsideTrees'), ('HamburgGreenAreas', 'HamburgGreenAreas')],
                max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryalgorithmparameter',
            name='short_name',
            field=models.CharField(max_length=28, validators=[
                django.core.validators.RegexValidator(code='invalid_parameter_name',
                                                      message='Invalid parameter short_name. Do not use spaceor special characters.',
                                                      regex='^\\w{1,28}$')]),
        ),
    ]
