# Generated by Django 3.0.7 on 2021-01-03 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='evaluated',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='evaluation_running',
        ),
    ]
