# Generated by Django 3.0.3 on 2020-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
