# Generated by Django 3.0.7 on 2020-11-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='model_name',
            field=models.CharField(
                choices=[('HamburgRoadsideTrees', 'HamburgRoadsideTrees'), ('HamburgGreenAreas', 'HamburgGreenAreas'),
                         ('NantesGreenhouses', 'NantesGreenhouses')], max_length=56, null=True),
        ),
        migrations.RemoveField(
            model_name='inventoryalgorithmparametervalue',
            name='parameter',
        ),
        migrations.AddField(
            model_name='inventoryalgorithmparametervalue',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.InventoryAlgorithmParameter'),
        ),
    ]
