# Generated by Django 3.0.7 on 2021-03-02 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioinventoryconfiguration',
            name='inventory_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.InventoryAlgorithmParameter'),
        ),
        migrations.AlterField(
            model_name='scenarioinventoryconfiguration',
            name='inventory_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.InventoryAlgorithmParameterValue'),
        ),
    ]
