# Generated by Django 3.0.7 on 2020-11-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0002_auto_20201105_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesteps', models.IntegerField(null=True)),
                ('cycles', models.IntegerField(null=True)),
            ],
        ),
    ]
