# Generated by Django 3.0.7 on 2021-01-26 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0002_auto_20210103_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='stan_flow_id',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[
                django.core.validators.RegexValidator(code='invalid_stan_id', message='STAN id must have 5 digits.s',
                                                      regex='^[0-9]{5}?')]),
        ),
    ]
