# Generated by Django 3.0.3 on 2020-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0002_auto_20200318_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchment',
            name='type',
            field=models.CharField(choices=[('A', 'administrative'), ('C', 'custom')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='description',
            field=models.TextField(),
        ),
    ]
