# Generated by Django 3.0.7 on 2021-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0002_auto_20210302_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryalgorithmparametervalue',
            name='standard_deviation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
