# Generated by Django 3.0.3 on 2020-06-05 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0002_auto_20200527_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='feedstocks',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='use_default_configuration',
        ),
    ]
