# Generated by Django 3.0.3 on 2020-03-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0003_auto_20200318_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='type',
            field=models.CharField(choices=[('administrative', 'administrative'), ('custom', 'custom')], default='custom', max_length=14),
        ),
    ]
