# Generated by Django 3.0.7 on 2020-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0004_auto_20201110_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryalgorithm',
            name='source_module',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
