# Generated by Django 3.0.7 on 2021-01-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0004_temporaldistribution_timestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestep',
            name='distribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.TemporalDistribution'),
            preserve_default=False,
        ),
    ]
