# Generated by Django 3.0.7 on 2021-01-26 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0005_timestep_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponentgroupsettings',
            name='temporal_distribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.TemporalDistribution'),
        ),
        migrations.AddField(
            model_name='materialcomponentshare',
            name='timestep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.Timestep'),
        ),
        migrations.AlterField(
            model_name='timestep',
            name='distribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.TemporalDistribution'),
        ),
    ]
