# Generated by Django 3.0.7 on 2021-05-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0005_inventoryamountshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryamountshare',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Scenario'),
        ),
    ]
