# Generated by Django 3.0.7 on 2020-11-13 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0005_inventoryalgorithm_source_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaldistribution',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.MaterialComponent'),
        ),
        migrations.AddField(
            model_name='seasonaldistribution',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.Material'),
        ),
    ]
