# Generated by Django 3.0.7 on 2020-06-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0006_auto_20200628_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='name',
            field=models.CharField(default='Custom Catchment', max_length=256),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='region',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Region'),
        ),
        migrations.AlterField(
            model_name='catchment',
            name='type',
            field=models.CharField(choices=[('administrative', 'administrative'), ('custom', 'custom')], default='custom', max_length=14),
        ),
    ]
