# Generated by Django 3.0.7 on 2021-10-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_auto_20211007_1350'),
        ('scenario_builder', '0006_inventoryamountshare_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataset',
            name='preview',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='geodataset',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
