# Generated by Django 3.0.7 on 2021-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0006_auto_20210126_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='average',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='standard_deviation',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
