# Generated by Django 3.0.7 on 2020-11-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0006_auto_20201113_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponentgroup',
            name='fractions_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.MaterialComponent'),
        ),
        migrations.AddField(
            model_name='materialcomponentgroup',
            name='static',
            field=models.BooleanField(default=True),
        ),
    ]
