# Generated by Django 3.0.7 on 2020-06-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0007_auto_20200628_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Region'),
        ),
    ]
