# Generated by Django 3.0.7 on 2020-11-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0007_auto_20201116_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonaldistribution',
            old_name='component',
            new_name='component_old',
        ),
        migrations.RenameField(
            model_name='seasonaldistribution',
            old_name='material',
            new_name='material_old',
        ),
    ]
