# Generated by Django 3.0.7 on 2021-02-01 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0007_auto_20210201_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponentshare',
            name='distribution',
        ),
    ]
