# Generated by Django 3.0.7 on 2020-11-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0008_auto_20201123_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonaldistribution',
            name='component_old',
        ),
        migrations.RemoveField(
            model_name='seasonaldistribution',
            name='material_old',
        ),
    ]
