# Generated by Django 3.0.7 on 2020-06-28 12:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0008_auto_20200628_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default='MULTIPOLYGON EMPTY', srid=4326),
        ),
    ]
