# Generated by Django 3.0.7 on 2021-02-04 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0008_remove_materialcomponentshare_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='dynamic',
        ),
    ]
