# Generated by Django 3.0.7 on 2021-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0008_geodataset_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataset',
            name='preview',
            field=models.ImageField(default='img/generic_map.png', upload_to='images'),
        ),
    ]
