# Generated by Django 3.0.7 on 2020-11-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0009_auto_20201123_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaldistribution',
            name='timesteps',
            field=models.IntegerField(default=12),
        ),
    ]
