# Generated by Django 3.0.7 on 2021-02-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0009_remove_materialcomponentgroupsettings_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponentgroupsettings',
            name='temporal_distributions',
            field=models.ManyToManyField(related_name='tempdist', to='scenario_builder.TemporalDistribution'),
        ),
    ]
