# Generated by Django 3.0.7 on 2020-06-28 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0009_auto_20200628_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
