# Generated by Django 3.0.7 on 2020-11-23 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_builder', '0010_auto_20201123_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaldistribution',
            name='cycles',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seasonaldistribution',
            name='start_stop',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1, 12], size=None),
        ),
        migrations.AlterField(
            model_name='seasonaldistribution',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], size=None),
        ),
    ]
