# Generated by Django 3.0.7 on 2021-02-04 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0010_materialcomponentgroupsettings_temporal_distributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='temporal_distribution',
        ),
    ]
