# Generated by Django 3.0.7 on 2021-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0011_remove_materialcomponentgroupsettings_temporal_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomponentgroupsettings',
            name='temporal_distributions',
            field=models.ManyToManyField(to='scenario_builder.TemporalDistribution'),
        ),
    ]
