# Generated by Django 3.0.7 on 2020-07-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0012_auto_20200629_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='materialcomponent',
            name='groups',
            field=models.ManyToManyField(to='scenario_builder.MaterialComponentGroup'),
        ),
    ]
