# Generated by Django 3.0.7 on 2020-12-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0012_materialcomponentgroupshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponentgroupshare',
            name='average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='materialcomponentgroupshare',
            name='standard_deviation',
            field=models.FloatField(null=True),
        ),
    ]
