# Generated by Django 3.0.7 on 2021-02-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0012_auto_20210204_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='group_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.MaterialComponentGroupSettings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.LiteratureSource'),
        ),
    ]
