# Generated by Django 3.0.7 on 2021-02-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0013_auto_20210205_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.MaterialComponent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='standard_deviation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='materialcomponentshare',
            name='timestep',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.Timestep'),
            preserve_default=False,
        ),
    ]
