# Generated by Django 3.0.7 on 2020-12-01 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0013_auto_20201201_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponentgroupshare',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.Scenario'),
        ),
        migrations.AddField(
            model_name='materialcomponentgroupshare',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.LiteratureSource'),
        ),
    ]
