# Generated by Django 3.0.7 on 2020-12-01 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0014_auto_20201201_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponent',
            name='fraction_of',
        ),
    ]
