# Generated by Django 3.0.7 on 2021-02-05 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenario_builder', '0015_materialcomponentgroupsettings_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Material')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenario',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Scenario')),
            ],
        ),
    ]
