# Generated by Django 3.0.7 on 2020-12-01 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0015_remove_materialcomponent_fraction_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponent',
            name='groups',
        ),
    ]
