# Generated by Django 3.0.7 on 2021-02-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0016_materialsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponentgroupsettings',
            name='material_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.MaterialSettings'),
        ),
    ]
