# Generated by Django 3.0.7 on 2020-12-01 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0016_remove_materialcomponent_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponent',
            name='average',
        ),
        migrations.RemoveField(
            model_name='materialcomponent',
            name='literature_source',
        ),
        migrations.RemoveField(
            model_name='materialcomponent',
            name='standard_deviation',
        ),
    ]
