# Generated by Django 3.0.7 on 2021-02-06 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0017_materialcomponentgroupsettings_material_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='scenario',
        ),
    ]
