# Generated by Django 3.0.7 on 2020-12-02 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0017_auto_20201201_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponent',
            name='material',
        ),
    ]
