# Generated by Django 3.0.7 on 2020-10-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0017_auto_20201010_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponent',
            name='fraction_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.MaterialComponent'),
        ),
    ]
