# Generated by Django 3.0.7 on 2020-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0018_materialcomponent_fraction_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abbreviation', models.CharField(max_length=50)),
            ],
        ),
    ]
