# Generated by Django 3.0.7 on 2021-02-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('material_manager', '0001_initial'),
        ('layer_manager', '0002_auto_20210206_1229'),
        ('flexibi_nantes', '0002_auto_20210206_1229'),
        ('scenario_builder', '0018_auto_20210206_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='materialcomponent',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='materialcomponentgroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='fractions_of',
        ),
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='group',
        ),
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='material_settings',
        ),
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='materialcomponentgroupsettings',
            name='temporal_distributions',
        ),
        migrations.RemoveField(
            model_name='materialcomponentshare',
            name='component',
        ),
        migrations.RemoveField(
            model_name='materialcomponentshare',
            name='group_settings',
        ),
        migrations.RemoveField(
            model_name='materialcomponentshare',
            name='source',
        ),
        migrations.RemoveField(
            model_name='materialcomponentshare',
            name='timestep',
        ),
        migrations.RemoveField(
            model_name='materialsettings',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialsettings',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='materialsettings',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='temporaldistribution',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='timestep',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='timestep',
            name='owner',
        ),
        migrations.AlterField(
            model_name='inventoryalgorithm',
            name='feedstock',
            field=models.ManyToManyField(limit_choices_to={'is_feedstock': True}, to='material_manager.Material'),
        ),
        migrations.AlterField(
            model_name='scenarioinventoryconfiguration',
            name='feedstock',
            field=models.ForeignKey(limit_choices_to={'is_feedstock': True},
                                    on_delete=django.db.models.deletion.CASCADE, to='material_manager.Material'),
        ),
        migrations.DeleteModel(
            name='LiteratureSource',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialComponent',
        ),
        migrations.DeleteModel(
            name='MaterialComponentGroup',
        ),
        migrations.DeleteModel(
            name='MaterialComponentGroupSettings',
        ),
        migrations.DeleteModel(
            name='MaterialComponentShare',
        ),
        migrations.DeleteModel(
            name='MaterialSettings',
        ),
        migrations.DeleteModel(
            name='TemporalDistribution',
        ),
        migrations.DeleteModel(
            name='Timestep',
        ),
    ]
