# Generated by Django 3.0.7 on 2020-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0019_literaturesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturesource',
            name='authors',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='literaturesource',
            name='abbreviation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='literaturesource',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
