# Generated by Django 3.0.7 on 2020-10-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0020_auto_20201012_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomponent',
            name='literature_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.LiteratureSource'),
        ),
    ]
