# Generated by Django 3.0.7 on 2020-10-12 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0021_materialcomponent_literature_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponent',
            name='source',
        ),
    ]
