# Generated by Django 3.0.7 on 2020-10-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0022_remove_materialcomponent_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryalgorithmparametervalue',
            name='parameter',
        ),
        migrations.AddField(
            model_name='inventoryalgorithmparametervalue',
            name='parameter',
            field=models.ManyToManyField(to='scenario_builder.InventoryAlgorithmParameter'),
        ),
    ]
