# Generated by Django 3.0.7 on 2020-10-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0023_auto_20201012_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryalgorithmparameter',
            name='inventory_algorithm',
        ),
        migrations.AddField(
            model_name='inventoryalgorithmparameter',
            name='inventory_algorithm',
            field=models.ManyToManyField(to='scenario_builder.InventoryAlgorithm'),
        ),
    ]
