# Generated by Django 3.0.7 on 2020-10-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0024_auto_20201012_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryalgorithm',
            name='feedstock',
        ),
        migrations.AddField(
            model_name='inventoryalgorithm',
            name='feedstock',
            field=models.ManyToManyField(limit_choices_to={'is_feedstock': True}, to='scenario_builder.Material'),
        ),
    ]
