# Generated by Django 3.0.7 on 2020-10-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0025_auto_20201012_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
