# Generated by Django 3.0.7 on 2020-10-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0026_scenario_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.IntegerField(choices=[(1, 'Changed'), (2, 'Running'), (3, 'Finished')], default=1),
        ),
    ]
