# Generated by Django 5.2.4 on 2025-11-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0003_alter_author_publication_status_and_more'),
        ('maps', '0003_alter_attribute_publication_status_and_more'),
        ('soilcom', '0004_alter_collection_min_bin_size_and_required_bin_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoreferencedCollector',
            fields=[
                ('collector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='soilcom.collector')),
                ('geopolygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.geopolygon')),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
            bases=('maps.geopolygon', 'soilcom.collector'),
        ),
        migrations.AddField(
            model_name='aggregatedcollectionpropertyvalue',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Sources or references for this property value.', to='bibliography.source'),
        ),
        migrations.AddField(
            model_name='collectionpropertyvalue',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Sources or references for this property value.', to='bibliography.source'),
        ),
    ]
