# Generated by Django 5.2.4 on 2026-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soilcom", "0005_georeferencedcollector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionpropertyvalue",
            name="is_derived",
            field=models.BooleanField(
                default=False,
                help_text="True when this value was computed from another property (e.g. total ↔ specific via population).",
            ),
        ),
    ]
