# Generated by Django 5.2.4 on 2026-02-24 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soilcom", "0008_merge_20260217_0951"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="required_bin_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Minimum total bin capacity that must be supplied per reference unit (see field below).",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Minimum required specific bin capacity (L/reference unit)",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="required_bin_capacity_reference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person", "per person"),
                    ("household", "per household"),
                    ("property", "per property"),
                    ("not_specified", "not specified"),
                ],
                default=None,
                help_text="Defines the unit (person, household, property) for which the required bin capacity applies. Leave blank if not specified.",
                max_length=16,
                null=True,
                verbose_name="Reference unit for minimum required specific bin capacity",
            ),
        ),
    ]
