from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0012_remove_wastestream_model'),
        ('waste_collection', '0001_move_legacy_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='collections',
                        ),
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='property',
                        ),
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='sources',
                        ),
                        migrations.RemoveField(
                            model_name='aggregatedcollectionpropertyvalue',
                            name='unit',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='allowed_materials',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='catchment',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='collection_system',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='collector',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='fee_system',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='flyers',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='forbidden_materials',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='frequency',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='predecessors',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='samples',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='sorting_method',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='sources',
                        ),
                        migrations.RemoveField(
                            model_name='collection',
                            name='waste_category',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='collection',
                        ),
                        migrations.RemoveField(
                            model_name='georeferencedwastecollection',
                            name='collection_ptr',
                        ),
                        migrations.RemoveField(
                            model_name='collectioncountoptions',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectioncountoptions',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectioncountoptions',
                            name='frequency',
                        ),
                        migrations.RemoveField(
                            model_name='collectioncountoptions',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectioncountoptions',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='collectioncountoptions',
                            name='season',
                        ),
                        migrations.RemoveField(
                            model_name='collectionfrequency',
                            name='seasons',
                        ),
                        migrations.RemoveField(
                            model_name='collectionfrequency',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionfrequency',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionfrequency',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionfrequency',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='property',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='sources',
                        ),
                        migrations.RemoveField(
                            model_name='collectionpropertyvalue',
                            name='unit',
                        ),
                        migrations.RemoveField(
                            model_name='collectionsystem',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionsystem',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionsystem',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='collectionsystem',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='collector',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='collector',
                            name='catchment',
                        ),
                        migrations.RemoveField(
                            model_name='collector',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='collector',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='collector',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='georeferencedcollector',
                            name='collector_ptr',
                        ),
                        migrations.RemoveField(
                            model_name='feesystem',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='feesystem',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='feesystem',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='feesystem',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='georeferencedcollector',
                            name='geopolygon_ptr',
                        ),
                        migrations.RemoveField(
                            model_name='georeferencedwastecollection',
                            name='geopolygon_ptr',
                        ),
                        migrations.RemoveField(
                            model_name='sortingmethod',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='sortingmethod',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='sortingmethod',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='sortingmethod',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='wastecategory',
                            name='approved_by',
                        ),
                        migrations.RemoveField(
                            model_name='wastecategory',
                            name='created_by',
                        ),
                        migrations.RemoveField(
                            model_name='wastecategory',
                            name='lastmodified_by',
                        ),
                        migrations.RemoveField(
                            model_name='wastecategory',
                            name='owner',
                        ),
                        migrations.DeleteModel(
                            name='CollectionCatchment',
                        ),
                        migrations.DeleteModel(
                            name='CollectionSeason',
                        ),
                        migrations.DeleteModel(
                            name='WasteComponent',
                        ),
                        migrations.DeleteModel(
                            name='WasteFlyer',
                        ),
                        migrations.DeleteModel(
                            name='AggregatedCollectionPropertyValue',
                        ),
                        migrations.DeleteModel(
                            name='Collection',
                        ),
                        migrations.DeleteModel(
                            name='CollectionCountOptions',
                        ),
                        migrations.DeleteModel(
                            name='CollectionFrequency',
                        ),
                        migrations.DeleteModel(
                            name='CollectionPropertyValue',
                        ),
                        migrations.DeleteModel(
                            name='CollectionSystem',
                        ),
                        migrations.DeleteModel(
                            name='Collector',
                        ),
                        migrations.DeleteModel(
                            name='FeeSystem',
                        ),
                        migrations.DeleteModel(
                            name='GeoreferencedCollector',
                        ),
                        migrations.DeleteModel(
                            name='GeoreferencedWasteCollection',
                        ),
                        migrations.DeleteModel(
                            name='SortingMethod',
                        ),
                        migrations.DeleteModel(
                            name='WasteCategory',
                        ),
            ],
        )
    ]
