# Generated by Django 3.2.10 on 2022-03-30 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('distributions', '0001_initial'),
        ('users', '0001_initial_data')
    ]

    operations = [
    ]
