# Generated by Django 3.2.10 on 2022-03-30 10:24

from django.db import migrations

from users.models import get_default_owner


def create_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    owner = User.objects.get(username=get_default_owner().username)

    TemporalDistribution = apps.get_model('distributions', 'TemporalDistribution')
    distribution, _ = TemporalDistribution.objects.get_or_create(name='Average', owner=owner)
    Timestep = apps.get_model('distributions', 'Timestep')
    timestep, _ = Timestep.objects.get_or_create(name='Average', distribution=distribution, owner=owner)

    months, _ = TemporalDistribution.objects.get_or_create(name='Months of the year', owner=owner)
    for month in ('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October',
                  'November', 'December'):
        Timestep.objects.get_or_create(distribution=months, name=month, owner=owner)


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
        ('users', '0001_initial_data')
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
