# Generated by Django 3.2.10 on 2022-09-24 14:35

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import brit.models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaldistribution',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='temporaldistribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='distributions_temporaldistribution_created',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='temporaldistribution',
            name='lastmodified_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now,
                                       verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='temporaldistribution',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='distributions_temporaldistribution_lastmodified',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='temporaldistribution',
            name='visible_to_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='timestep',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='timestep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='distributions_timestep_created', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='timestep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timestep',
            name='lastmodified_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now,
                                       verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='timestep',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='distributions_timestep_lastmodified', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='timestep',
            name='visible_to_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='temporaldistribution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='temporaldistribution',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timestep',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timestep',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
