# Generated by Django 5.2.4 on 2026-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0003_alter_period_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='temporaldistribution',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='timestep',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
    ]
