from django.urls import path

from . import views

urlpatterns = [
    path('collectors/', views.CollectorListView.as_view(), name='collector_list'),
    path('collectors/create/', views.CollectorCreateView.as_view(), name='collector_create'),
    path('collectors/create/modal/', views.CollectorModalCreateView.as_view(), name='collector_create_modal'),
    path('collectors/<int:pk>/', views.CollectorDetailView.as_view(), name='collector_detail'),
    path('collectors/<int:pk>/modal/', views.CollectorModalDetailView.as_view(), name='collector_detail_modal'),
    path('collectors/<int:pk>/update/', views.CollectorUpdateView.as_view(), name='collector_update'),
    path('collectors/<int:pk>/update/modal/', views.CollectorModalUpdateView.as_view(), name='collector_update_modal'),
    path('collectors/<int:pk>/delete/modal/', views.CollectorModalDeleteView.as_view(), name='collector_delete_modal'),
    path('collection_systems/', views.CollectionSystemListView.as_view(), name='collection_system_list'),
    path('collection_systems/create/', views.CollectionSystemCreateView.as_view(), name='collection_system_create'),
    path('collection_systems/create/modal/', views.CollectionSystemModalCreateView.as_view(), name='collection_system_create_modal'),
    path('collection_systems/<int:pk>/', views.CollectionSystemDetailView.as_view(), name='collection_system_detail'),
    path('collection_systems/<int:pk>/modal/', views.CollectionSystemModalDetailView.as_view(), name='collection_system_detail_modal'),
    path('collection_systems/<int:pk>/update/', views.CollectionSystemUpdateView.as_view(), name='collection_system_update'),
    path('collection_systems/<int:pk>/update/modal/', views.CollectionSystemModalUpdateView.as_view(), name='collection_system_update_modal'),
    path('collection_systems/<int:pk>/delete/modal/', views.CollectionSystemModalDeleteView.as_view(), name='collection_system_delete_modal'),
    path('waste_categories/', views.WasteCategoryListView.as_view(), name='waste_category_list'),
    path('waste_categories/create/', views.WasteCategoryCreateView.as_view(), name='waste_category_create'),
    path('waste_categories/create/modal/', views.WasteCategoryModalCreateView.as_view(), name='waste_category_create_modal'),
    path('waste_categories/<int:pk>/', views.WasteCategoryDetailView.as_view(), name='waste_category_detail'),
    path('waste_categories/<int:pk>/modal/', views.WasteCategoryModalDetailView.as_view(), name='waste_category_detail_modal'),
    path('waste_categories/<int:pk>/update/', views.WasteCategoryUpdateView.as_view(), name='waste_category_update'),
    path('waste_categories/<int:pk>/update/modal/', views.WasteCategoryModalUpdateView.as_view(), name='waste_category_update_modal'),
    path('waste_categories/<int:pk>/delete/modal/', views.WasteCategoryModalDeleteView.as_view(), name='waste_category_delete_modal'),
    path('waste_streams/', views.WasteStreamListView.as_view(), name='waste_stream_list'),
    path('waste_streams/create/', views.WasteStreamCreateView.as_view(), name='waste_stream_create'),
    path('waste_streams/create/modal/', views.WasteStreamModalCreateView.as_view(), name='waste_stream_create_modal'),
    path('waste_streams/<int:pk>/', views.WasteStreamDetailView.as_view(), name='waste_stream_detail'),
    path('waste_streams/<int:pk>/modal/', views.WasteStreamModalDetailView.as_view(), name='waste_stream_detail_modal'),
    path('waste_streams/<int:pk>/update/', views.WasteStreamUpdateView.as_view(), name='waste_stream_update'),
    path('waste_streams/<int:pk>/update/modal/', views.WasteStreamModalUpdateView.as_view(), name='waste_stream_update_modal'),
    path('waste_streams/<int:pk>/delete/modal/', views.WasteStreamModalDeleteView.as_view(), name='waste_stream_delete_modal'),
]
