# Generated by Django 5.1.7 on 2025-04-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_app_feature', 'Can access the app feature')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
