# Generated by Django 5.2.4 on 2026-02-08 12:47

import django.db.models.deletion
import django.utils.timezone
import utils.object_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_alter_author_publication_status_and_more'),
        ('materials', '0005_alter_analyticalmethod_publication_status_and_more'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('publication_status', models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owner', models.ForeignKey(default=utils.object_management.models.get_default_owner_pk, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process Category',
                'verbose_name_plural': 'Process Categories',
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('publication_status', models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, help_text='One-line summary shown in cards and lists.')),
                ('mechanism', models.CharField(blank=True, help_text='Dominant reaction mechanism (e.g. Partial Oxidation).', max_length=255)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum operating temperature in °C.', max_digits=8, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum operating temperature in °C.', max_digits=8, null=True)),
                ('yield_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum yield in percent.', max_digits=5, null=True)),
                ('yield_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum yield in percent.', max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='processes/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='High-level category (e.g. Thermochemical, Biochemical).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_types', to='processes.processcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('input_materials', models.ManyToManyField(blank=True, help_text='Materials that can serve as feedstock for this process.', related_name='as_process_input', to='materials.material')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('output_materials', models.ManyToManyField(blank=True, help_text='Materials produced by this process.', related_name='as_process_output', to='materials.material')),
                ('owner', models.ForeignKey(default=utils.object_management.models.get_default_owner_pk, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sources', models.ManyToManyField(blank=True, help_text='Literature references for this process type.', to='bibliography.source')),
            ],
            options={
                'verbose_name': 'Process Type',
                'verbose_name_plural': 'Process Types',
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.DeleteModel(
            name='AppPermission',
        ),
    ]
