# Generated by Django 5.2.4 on 2025-10-04 15:00

import processes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_refine_process_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processmaterial',
            new_name='processes_p_process_807014_idx',
            old_name='processmat_process_r_0d0e2b_idx',
        ),
        migrations.RenameIndex(
            model_name='processoperatingparameter',
            new_name='processes_p_process_ebf597_idx',
            old_name='processoper_process_p_98f0f0_idx',
        ),
        migrations.AlterField(
            model_name='processinforesource',
            name='url',
            field=models.CharField(blank=True, help_text='Target URL for internal or external resources.', max_length=1023, validators=[processes.models.validate_internal_or_external_url]),
        ),
        migrations.AlterField(
            model_name='processlink',
            name='url',
            field=models.CharField(help_text='Relative or absolute URL to navigate to.', max_length=1023, validators=[processes.models.validate_internal_or_external_url]),
        ),
    ]
