# Generated by Django 5.2.4 on 2025-10-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_rename_processmat_process_r_0d0e2b_idx_processes_p_process_807014_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['name', 'id'], 'permissions': [('can_moderate_process', 'Can moderate processes')]},
        ),
        migrations.AlterModelOptions(
            name='processcategory',
            options={'permissions': [('can_moderate_processcategory', 'Can moderate process categories')], 'verbose_name': 'Process category', 'verbose_name_plural': 'Process categories'},
        ),
    ]
