# Generated by Django 5.2.4 on 2026-03-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0005_add_moderation_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("review", "Review"),
                    ("published", "Published"),
                    ("declined", "Declined"),
                    ("archived", "Archived"),
                ],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="processcategory",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("review", "Review"),
                    ("published", "Published"),
                    ("declined", "Declined"),
                    ("archived", "Archived"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
