# Generated by Django 6.0.4 on 2026-05-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0009_rename_source_bibtex_fields"),
        ("processes", "0006_alter_process_publication_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="process",
            options={
                "ordering": ["name", "id"],
                "permissions": [("can_moderate_process", "Can moderate processes")],
                "verbose_name_plural": "Processes",
            },
        ),
        migrations.AddField(
            model_name="process",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Author or contributor shown on the process detail page.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processes",
                to="bibliography.author",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="author_institution",
            field=models.CharField(
                blank=True,
                help_text="Institutional affiliation for the process author.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email address for the process author.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="process_technology",
            field=models.TextField(
                blank=True,
                help_text="Technology description, equipment, and process conditions.",
            ),
        ),
    ]
