# Generated by Django 6.0.4 on 2026-05-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0007_alter_process_options_process_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="supplementary_document",
            field=models.FileField(
                blank=True,
                help_text="Optional supplementary PDF document, such as a process flow sheet.",
                null=True,
                upload_to="processes/supplementary_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
