# Generated by Django 6.0.4 on 2026-05-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0008_process_supplementary_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="processcategory",
            name="supplementary_document",
            field=models.FileField(
                blank=True,
                help_text="Optional supplementary PDF document with combined information for related processes.",
                null=True,
                upload_to="processes/category_supplementary_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
