# Generated by Django 6.0.3 on 2026-04-23 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SortingMethod",
            new_name="BinConfiguration",
        ),
        migrations.AlterModelOptions(
            name="binconfiguration",
            options={"ordering": ["name", "id"], "verbose_name": "bin configuration"},
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="sorting_method",
            new_name="bin_configuration",
        ),
        migrations.AlterField(
            model_name="collection",
            name="bin_configuration",
            field=models.ForeignKey(
                blank=True,
                help_text="How waste fractions are separated at the household level.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collections",
                to="waste_collection.binconfiguration",
                verbose_name="Bin configuration",
            ),
        ),
    ]
