# Generated by Django 6.0.3 on 2026-03-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_collection", "0002_update_content_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="required_bin_capacity_reference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person", "per person"),
                    ("person_week", "per person & week"),
                    ("household", "per household"),
                    ("property", "per property"),
                    ("not_specified", "not specified"),
                ],
                default=None,
                help_text="Defines the unit (person, household, property) for which the required bin capacity applies. Leave blank if not specified.",
                max_length=16,
                null=True,
                verbose_name="Reference unit for minimum required specific bin capacity",
            ),
        ),
    ]
