# Generated by Django 6.0.3 on 2026-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0009_rename_source_bibtex_fields"),
        ("materials", "0010_materialpropertyvalue_basis_component"),
        ("waste_collection", "0003_alter_collection_required_bin_capacity_reference"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="collectioncountoptions",
                    new_name="waste_colle_publica_23ad95_idx",
                    old_name="soilcom_col_publica_c5f9a3_idx",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="aggregatedcollectionpropertyvalue",
            name="collections",
            field=models.ManyToManyField(
                db_table="waste_collection_aggregatedcollectionpropertyvalue_collections",
                to="waste_collection.collection",
            ),
        ),
        migrations.AlterField(
            model_name="aggregatedcollectionpropertyvalue",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                db_table="waste_collection_aggregatedcollectionpropertyvalue_sources",
                help_text="Sources or references for this property value.",
                to="bibliography.source",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="allowed_materials",
            field=models.ManyToManyField(
                blank=True,
                db_table="waste_collection_collection_allowed_materials",
                related_name="allowed_in_collections",
                to="materials.material",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="flyers",
            field=models.ManyToManyField(
                db_table="waste_collection_collection_flyers",
                related_name="collections",
                to="waste_collection.wasteflyer",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="forbidden_materials",
            field=models.ManyToManyField(
                blank=True,
                db_table="waste_collection_collection_forbidden_materials",
                related_name="forbidden_in_collections",
                to="materials.material",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="predecessors",
            field=models.ManyToManyField(
                blank=True,
                db_table="waste_collection_collection_predecessors",
                related_name="successors",
                to="waste_collection.collection",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="samples",
            field=models.ManyToManyField(
                db_table="waste_collection_collection_samples",
                related_name="collections",
                to="materials.sample",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="sources",
            field=models.ManyToManyField(
                db_table="waste_collection_collection_sources",
                to="bibliography.source",
            ),
        ),
        migrations.AlterField(
            model_name="collectionpropertyvalue",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                db_table="waste_collection_collectionpropertyvalue_sources",
                help_text="Sources or references for this property value.",
                to="bibliography.source",
            ),
        ),
        migrations.AlterModelTable(
            name="aggregatedcollectionpropertyvalue",
            table="waste_collection_aggregatedcollectionpropertyvalue",
        ),
        migrations.AlterModelTable(
            name="collection",
            table="waste_collection_collection",
        ),
        migrations.AlterModelTable(
            name="collectioncountoptions",
            table="waste_collection_collectioncountoptions",
        ),
        migrations.AlterModelTable(
            name="collectionfrequency",
            table="waste_collection_collectionfrequency",
        ),
        migrations.AlterModelTable(
            name="collectionpropertyvalue",
            table="waste_collection_collectionpropertyvalue",
        ),
        migrations.AlterModelTable(
            name="collectionsystem",
            table="waste_collection_collectionsystem",
        ),
        migrations.AlterModelTable(
            name="collector",
            table="waste_collection_collector",
        ),
        migrations.AlterModelTable(
            name="feesystem",
            table="waste_collection_feesystem",
        ),
        migrations.AlterModelTable(
            name="sortingmethod",
            table="waste_collection_sortingmethod",
        ),
        migrations.AlterModelTable(
            name="wastecategory",
            table="waste_collection_wastecategory",
        ),
    ]
