# Generated by Django 6.0.4 on 2026-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_collection", "0003_fix_sweden_2024_valid_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="access_control",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether access to the collection point or bin is controlled (e.g. by chip, key card, or lock). True = access-controlled; False = no access control; blank = not specified.",
                null=True,
                verbose_name="Access control",
            ),
        ),
    ]
