# Generated by Django 6.0.4 on 2026-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_collection", "0004_add_access_control_to_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="access_control",
        ),
        migrations.AddField(
            model_name="collection",
            name="access_control_bp",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether access to the bring-point (BP) collection infrastructure is controlled (e.g. by chip, key card, or lock). True = access-controlled; False = no access control; blank = not specified.",
                null=True,
                verbose_name="Access control (BP)",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="access_control_pap",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether access to the door-to-door (PAP) container is controlled (e.g. by chip, key card, or lock). True = access-controlled; False = no access control; blank = not specified.",
                null=True,
                verbose_name="Access control (PAP)",
            ),
        ),
    ]
