# Generated by Django 6.0.3 on 2026-04-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0009_rename_source_bibtex_fields"),
        ("materials", "0010_materialpropertyvalue_basis_component"),
        (
            "waste_collection",
            "0004_rename_soilcom_col_publica_c5f9a3_idx_waste_colle_publica_23ad95_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aggregatedcollectionpropertyvalue",
            name="collections",
            field=models.ManyToManyField(to="waste_collection.collection"),
        ),
        migrations.AlterField(
            model_name="aggregatedcollectionpropertyvalue",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sources or references for this property value.",
                to="bibliography.source",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="allowed_materials",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_in_collections",
                to="materials.material",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="flyers",
            field=models.ManyToManyField(
                related_name="collections",
                to="waste_collection.wasteflyer",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="forbidden_materials",
            field=models.ManyToManyField(
                blank=True,
                related_name="forbidden_in_collections",
                to="materials.material",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="predecessors",
            field=models.ManyToManyField(
                blank=True,
                related_name="successors",
                to="waste_collection.collection",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="samples",
            field=models.ManyToManyField(
                related_name="collections",
                to="materials.sample",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="sources",
            field=models.ManyToManyField(to="bibliography.source"),
        ),
        migrations.AlterField(
            model_name="collectionpropertyvalue",
            name="sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sources or references for this property value.",
                to="bibliography.source",
            ),
        ),
        migrations.AlterModelTable(
            name="aggregatedcollectionpropertyvalue",
            table=None,
        ),
        migrations.AlterModelTable(
            name="collection",
            table=None,
        ),
        migrations.AlterModelTable(
            name="collectioncountoptions",
            table=None,
        ),
        migrations.AlterModelTable(
            name="collectionfrequency",
            table=None,
        ),
        migrations.AlterModelTable(
            name="collectionpropertyvalue",
            table=None,
        ),
        migrations.AlterModelTable(
            name="collectionsystem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="collector",
            table=None,
        ),
        migrations.AlterModelTable(
            name="feesystem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="sortingmethod",
            table=None,
        ),
        migrations.AlterModelTable(
            name="wastecategory",
            table=None,
        ),
    ]
