from django.urls import include, path

from .router import router
from .views import (
    BiowasteCollectionAmountMapView,
    BiowasteCollectionCountMapView,
    BiowasteFeeSystemMapView,
    BiowasteFrequencyMapView,
    CollectionSupportMapView,
    CollectionSystemMapView,
    CombinedCollectionCountMapView,
    CombinedFeeSystemMapView,
    CombinedFrequencyMapView,
    ConnectionRateMapView,
    FoodWasteCategoryMapView,
    GreenWasteCollectionAmountMapView,
    GreenWasteCollectionSystemCountMapView,
    OrgaLevelMapView,
    PaperBagsMapView,
    PlasticBagsMapView,
    PopulationDensityMapView,
    ResidualCollectionAmountMapView,
    ResidualCollectionCountMapView,
    ResidualFeeSystemMapView,
    ResidualFrequencyMapView,
    WasteAtlasOverviewView,
    WasteRatioMapView,
)

urlpatterns = [
    path("", include(router.urls)),
    path(
        "map/",
        WasteAtlasOverviewView.as_view(),
        name="waste-atlas-overview",
    ),
    path(
        "map/orga-level/",
        OrgaLevelMapView.as_view(),
        name="waste-atlas-orga-level-map",
    ),
    path(
        "map/collection-system/",
        CollectionSystemMapView.as_view(),
        name="waste-atlas-collection-system-map",
    ),
    path(
        "map/green-waste-collection-system-count/",
        GreenWasteCollectionSystemCountMapView.as_view(),
        name="waste-atlas-green-waste-collection-system-count-map",
    ),
    path(
        "map/connection-rate/",
        ConnectionRateMapView.as_view(),
        name="waste-atlas-connection-rate-map",
    ),
    path(
        "map/food-waste-category/",
        FoodWasteCategoryMapView.as_view(),
        name="waste-atlas-food-waste-category-map",
    ),
    path(
        "map/paper-bags/",
        PaperBagsMapView.as_view(),
        name="waste-atlas-paper-bags-map",
    ),
    path(
        "map/plastic-bags/",
        PlasticBagsMapView.as_view(),
        name="waste-atlas-plastic-bags-map",
    ),
    path(
        "map/collection-support/",
        CollectionSupportMapView.as_view(),
        name="waste-atlas-collection-support-map",
    ),
    path(
        "map/residual-frequency/",
        ResidualFrequencyMapView.as_view(),
        name="waste-atlas-residual-frequency-map",
    ),
    path(
        "map/biowaste-frequency/",
        BiowasteFrequencyMapView.as_view(),
        name="waste-atlas-biowaste-frequency-map",
    ),
    path(
        "map/combined-frequency/",
        CombinedFrequencyMapView.as_view(),
        name="waste-atlas-combined-frequency-map",
    ),
    path(
        "map/residual-collection-count/",
        ResidualCollectionCountMapView.as_view(),
        name="waste-atlas-residual-collection-count-map",
    ),
    path(
        "map/biowaste-collection-count/",
        BiowasteCollectionCountMapView.as_view(),
        name="waste-atlas-biowaste-collection-count-map",
    ),
    path(
        "map/combined-collection-count/",
        CombinedCollectionCountMapView.as_view(),
        name="waste-atlas-combined-collection-count-map",
    ),
    path(
        "map/residual-fee-system/",
        ResidualFeeSystemMapView.as_view(),
        name="waste-atlas-residual-fee-system-map",
    ),
    path(
        "map/biowaste-fee-system/",
        BiowasteFeeSystemMapView.as_view(),
        name="waste-atlas-biowaste-fee-system-map",
    ),
    path(
        "map/combined-fee-system/",
        CombinedFeeSystemMapView.as_view(),
        name="waste-atlas-combined-fee-system-map",
    ),
    path(
        "map/residual-collection-amount/",
        ResidualCollectionAmountMapView.as_view(),
        name="waste-atlas-residual-collection-amount-map",
    ),
    path(
        "map/biowaste-collection-amount/",
        BiowasteCollectionAmountMapView.as_view(),
        name="waste-atlas-biowaste-collection-amount-map",
    ),
    path(
        "map/green-waste-collection-amount/",
        GreenWasteCollectionAmountMapView.as_view(),
        name="waste-atlas-green-waste-collection-amount-map",
    ),
    path(
        "map/waste-ratio/",
        WasteRatioMapView.as_view(),
        name="waste-atlas-waste-ratio-map",
    ),
    path(
        "map/population-density/",
        PopulationDensityMapView.as_view(),
        name="waste-atlas-population-density-map",
    ),
]
