#!/bin/bash
dropdb --if-exists -h db -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -w "$POSTGRES_DB"
createdb -h db -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -w "$POSTGRES_DB"
heroku pg:pull "$HEROKU_POSTGRESQL_COLOR_URL" postgres://"$POSTGRES_USER":"$POSTGRES_PASSWORD"@db:"$POSTGRES_PORT"/"$POSTGRES_DB" -a bri-tool
psql -h db -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -w --set=postgres_db="$POSTGRES_DB" <<<'ALTER DATABASE :postgres_db SET search_path TO "$user", public, heroku_ext'
psql -h db -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -w --set=postgres_user="$POSTGRES_USER" <<<'ALTER ROLE :postgres_user SET search_path TO "$user", public, heroku_ext'