# Generated by Django 3.2.10 on 2022-03-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('type', models.CharField(choices=[('article', 'article'), ('dataset', 'dataset'), ('book', 'book'), ('website', 'website'), ('custom', 'custom'), ('waste_flyer', 'waste_flyer')], default='custom', max_length=255)),
                ('authors', models.CharField(blank=True, max_length=500, null=True)),
                ('publisher', models.CharField(blank=True, max_length=127, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('journal', models.CharField(blank=True, max_length=500, null=True)),
                ('issue', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(null=True)),
                ('abbreviation', models.CharField(max_length=50, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('attributions', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=511, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('last_accessed', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliography_source_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliography_source_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bibliography.licence')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visible_to_groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'verbose_name': 'Source',
            },
        ),
    ]
