# Generated by Django 3.0.7 on 2021-10-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_auto_20211007_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiteratureSource',
        ),
    ]
