# Generated by Django 3.2.10 on 2022-05-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re

def create_initial_data(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model('auth', 'Permission')

    models = ['Author']
    permission_prefixes = ['add', 'view', 'change', 'delete']

    editors, _ = Group.objects.get_or_create(name='editors')
    for model in models:
        model_class = apps.get_model('bibliography', model)
        content_type = ContentType.objects.get_for_model(model_class, for_concrete_model=False)
        verbose_name = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", str(model_class.__name__)).lower()

        for prefix in permission_prefixes:
            codename = f'{prefix}_{model_class._meta.model_name}'
            name = f'Can {prefix} {verbose_name}'
            permission, _ = Permission.objects.get_or_create(
                codename=codename,
                content_type=content_type,
                defaults={'name': name})
            editors.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bibliography', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('first_names', models.CharField(max_length=1023)),
                ('last_names', models.CharField(max_length=1023)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliography_author_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliography_author_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visible_to_groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_initial_data)
    ]
