# Generated by Django 5.2.4 on 2026-02-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0003_alter_author_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='licence',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('review', 'Review'), ('published', 'Published'), ('declined', 'Declined'), ('archived', 'Archived')], default='private', max_length=10),
        ),
    ]
