# Generated by Django 3.2.8 on 2021-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bibliography', '0003_delete_literaturesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='journal',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='publisher',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(
                choices=[('article', 'article'), ('dataset', 'dataset'), ('website', 'website'), ('custom', 'custom')],
                default='custom', max_length=255),
        ),
    ]
