# Generated by Django 5.2.4 on 2026-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_alter_author_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
