# Generated by Django 3.2.10 on 2022-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_auto_20220505_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('article', 'article'), ('dataset', 'dataset'), ('book', 'book'), ('website', 'website'), ('custom', 'custom')], default='custom', max_length=255),
        ),
    ]
