# Generated by Django 5.2.4 on 2026-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0005_alter_source_abbreviation_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
