# Generated by Django 3.2.8 on 2021-11-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0005_alter_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='journal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('article', 'article'), ('dataset', 'dataset'), ('book', 'book'), ('website', 'website'), ('custom', 'custom'), ('waste_flyer', 'waste_flyer')], default='custom', max_length=255),
        ),
    ]
