# Generated by Django 3.2.10 on 2022-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0005_alter_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='url_valid',
            field=models.BooleanField(default=False),
        ),
    ]
