# Generated by Django 3.2.10 on 2022-08-30 08:24

from django.db import migrations, models
from users.models import get_default_owner

def create_author_models_from_char(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Author = apps.get_model('bibliography', 'Author')
    Source = apps.get_model('bibliography', 'Source')
    User = apps.get_model('auth', 'User')
    owner = User.objects.get(username=get_default_owner().username)

    for source in Source.objects.filter(type__in=('article', 'book', 'dataset', 'website', 'custom')):
        if source.authors:
            full_names = source.authors.split(';')
            for name in full_names:
                name_dict = dict(zip(('last_names', 'first_names'), name.split(',')))
                author, _ = Author.objects.get_or_create(
                    owner=owner,
                    last_names=name_dict.get('last_names', '').strip(),
                    first_names=name_dict.get('first_names', '').strip()
                )
                source.new_authors.add(author)



class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0006_auto_20220822_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='new_authors',
            field=models.ManyToManyField(related_name='sources', to='bibliography.Author'),
        ),
        migrations.RunPython(create_author_models_from_char)
    ]
