# Generated by Django 3.2.8 on 2021-11-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0006_auto_20211115_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source'},
        ),
    ]
