# Generated by Django 3.2.10 on 2022-08-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0007_auto_20220830_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='authors',
        ),
    ]
