# Generated by Django 3.2.8 on 2021-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0008_auto_20211117_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
    ]
