# Generated by Django 6.0.5 on 2026-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliography", "0010_author_contact_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="author_type",
            field=models.CharField(
                choices=[("person", "Person"), ("organization", "Organization")],
                default="person",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="organization_abbreviation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="organization_name",
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
