# Generated by Django 3.2.10 on 2022-11-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0013_auto_20220924_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_names', 'first_names']},
        ),
    ]
