# Generated by Django 4.2.8 on 2024-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0015_alter_author_created_by_alter_author_lastmodified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='middle_names',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='preferred_citation',
            field=models.CharField(blank=True, max_length=2046, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
