# Generated by Django 5.1.1 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0017_author_publication_status_licence_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licence',
            options={'ordering': ['name', 'id']},
        ),
    ]
