# Generated by Django 5.1.1 on 2024-11-16 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bibliography', '0018_alter_licence_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='source',
            name='visible_to_groups',
        ),
    ]
