# Generated by Django 5.1.1 on 2024-12-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0019_remove_author_visible_to_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.author')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.source')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('source', 'author', 'position')},
            },
        ),
    ]
