# Generated by Django 5.1.1 on 2024-12-18 15:23

from django.db import migrations

def populate_sourceauthor(apps, schema_editor):
    Source = apps.get_model('bibliography', 'Source')
    SourceAuthor = apps.get_model('bibliography', 'SourceAuthor')
    for source in Source.objects.all():
        for position, author in enumerate(source.authors.all(), start=1):
            SourceAuthor.objects.create(source=source, author=author, position=position)


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0020_sourceauthor'),
    ]

    operations = [
        migrations.RunPython(populate_sourceauthor),
    ]
