# Generated by Django 5.1.1 on 2024-12-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0021_populate_source_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='authors',
            new_name='old_authors',
        ),
    ]
