# Generated by Django 5.1.1 on 2024-12-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0022_rename_authors_source_old_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='old_authors',
            field=models.ManyToManyField(related_name='old_sources', to='bibliography.author'),
        ),
    ]
