# Generated by Django 5.1.1 on 2024-12-18 15:30

from django.db import migrations, models


def populate_author(apps, schema_editor):
    Source = apps.get_model('bibliography', 'Source')
    SourceAuthor = apps.get_model('bibliography', 'SourceAuthor')
    for source in Source.objects.all():
        for position, author in enumerate(source.old_authors.all(), start=1):
            SourceAuthor.objects.create(source=source, author=author, position=position)


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0023_alter_source_old_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='authors',
            field=models.ManyToManyField(related_name='sources', through='bibliography.SourceAuthor', to='bibliography.author'),
        ),
    ]
