# Generated by Django 5.1.1 on 2024-12-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0024_source_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='old_authors',
        ),
    ]
