# Generated by Django 5.1.1 on 2025-02-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0025_remove_source_old_authors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourceauthor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_names',
            field=models.CharField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Custom abbreviations in inline citations. If left blank, the authors last name and the year are used.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sourceauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceauthors', to='bibliography.author'),
        ),
        migrations.AlterField(
            model_name='sourceauthor',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceauthors', to='bibliography.source'),
        ),
        migrations.AddConstraint(
            model_name='sourceauthor',
            constraint=models.UniqueConstraint(fields=('source', 'position'), name='unique_source_position'),
        ),
        migrations.AddConstraint(
            model_name='sourceauthor',
            constraint=models.UniqueConstraint(fields=('source', 'author'), name='unique_source_author'),
        ),
    ]
