# Generated by Django 5.1.1 on 2025-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0026_alter_sourceauthor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_names',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
    ]
