# Generated by Django 5.1.1 on 2025-03-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0027_alter_author_last_names_alter_source_abbreviation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sourceauthor',
            name='unique_source_position',
        ),
        migrations.RemoveConstraint(
            model_name='sourceauthor',
            name='unique_source_author',
        ),
    ]
