from django.urls import include, path

from .views import (MaterialComponentGroupAddComponentView,
                    CatchmentCreateView,
                    CatchmentBrowseView,
                    CatchmentGeometryAPI,
                    CatchmentUpdateView,
                    CatchmentDeleteView,
                    MaterialAddComponentGroupView,
                    MaterialListView,
                    MaterialCreateView,
                    MaterialDetailView,
                    MaterialUpdateView,
                    MaterialDeleteView,
                    MaterialSettingsDetailView,
                    MaterialComponentListView,
                    MaterialComponentCreateView,
                    MaterialComponentDetailView,
                    MaterialComponentUpdateView,
                    MaterialComponentDeleteView,
                    MaterialComponentGroupListView,
                    MaterialComponentGroupCreateView,
                    MaterialComponentGroupDetailView,
                    MaterialComponentGroupUpdateView,
                    MaterialComponentGroupDeleteView,
                    MaterialComponentShareUpdateView,
                    MaterialRemoveComponentGroupView,
                    MaterialComponentGroupRemoveComponentView,
                    MaterialComponentGroupAddTemporalDistributionView,
                    MaterialComponentGroupShareDistributionUpdateView,
                    RegionGeometryAPI,
                    ScenarioDetailView,
                    ScenarioListView,
                    ScenarioCreateView,
                    ScenarioDeleteView,
                    ScenarioUpdateView,
                    SeasonalDistributionCreateView,
                    ResultMapAPI,
                    ScenarioAddInventoryAlgorithmView,
                    ScenarioRemoveInventoryAlgorithmView,
                    ScenarioAlgorithmConfigurationUpdateView,
                    load_geodataset_options,
                    load_algorithm_options,
                    load_parameter_options,
                    load_catchment_options,
                    )

urlpatterns = [
    path('catchments/', CatchmentBrowseView.as_view(), name='catchment_list'),
    path('catchment/create/', CatchmentCreateView.as_view(), name='catchment_definition'),
    path('catchments/<int:pk>/update/', CatchmentUpdateView.as_view(), name='catchment_update'),
    path('catchments/<int:pk>/delete/', CatchmentDeleteView.as_view(), name='catchment_delete'),
    path('materials/', MaterialListView.as_view(), name='material_list'),
    path('materials/create/', MaterialCreateView.as_view(), name='material_create'),
    path('materials/<int:pk>/', MaterialDetailView.as_view(), name='material_detail'),
    path('materials/<int:pk>/update/', MaterialUpdateView.as_view(), name='material_update'),
    path('materials/<int:pk>/delete/', MaterialDeleteView.as_view(), name='material_delete'),
    path('materials/settings/<int:pk>', MaterialSettingsDetailView.as_view(), name='material_settings'),
    path('materials/settings/<int:pk>/add_component_group/', MaterialAddComponentGroupView.as_view(),
         name='material_add_component_group'),
    path('materialcomponents/', MaterialComponentListView.as_view(), name='material_component_list'),
    path('materialcomponents/create/', MaterialComponentCreateView.as_view(), name='material_component_create'),
    path('materialcomponents/<int:pk>/', MaterialComponentDetailView.as_view(), name='material_component_detail'),
    path('materialcomponents/<int:pk>/update/', MaterialComponentUpdateView.as_view(),
         name='material_component_update'),
    path('materialcomponents/<int:pk>/delete/', MaterialComponentDeleteView.as_view(),
         name='material_component_delete'),
    path('materialcomponentgroups/', MaterialComponentGroupListView.as_view(), name='material_component_group_list'),
    path('materialcomponentgroups/create/', MaterialComponentGroupCreateView.as_view(),
         name='material_component_group_create'),
    path('materialcomponentgroups/<int:pk>/', MaterialComponentGroupDetailView.as_view(),
         name='material_component_group_detail'),
    path('materialcomponentgroups/<int:pk>/update/', MaterialComponentGroupUpdateView.as_view(),
         name='material_component_group_update'),
    path('materialcomponentgroups/<int:pk>/delete/', MaterialComponentGroupDeleteView.as_view(),
         name='material_component_group_delete'),
    path('materialcomponentgroups/settings/<int:pk>/add_component/', MaterialComponentGroupAddComponentView.as_view(),
         name='material_component_group_add_component'),
    path('materialcomponentgroups/settings/<int:pk>/remove_component/<int:component_pk>/',
         MaterialComponentGroupRemoveComponentView.as_view(), name='material_component_group_remove_component'),
    path('materialcomponentgroups/settings/<int:pk>/remove/', MaterialRemoveComponentGroupView.as_view(),
         name='material_component_group_remove'),
    path('materialcomponentgroups/settings/<int:pk>/add_temporal_distribution/',
         MaterialComponentGroupAddTemporalDistributionView.as_view(),
         name='material_component_group_add_temporal_distribution'),
    path('materialcomponentgroupshares/<int:pk>/update/', MaterialComponentShareUpdateView.as_view(),
         name='material_component_group_share_update'),
    path('material_component_groups/settings/<int:pk>/shares/<int:timestep_pk>/update/',
         MaterialComponentGroupShareDistributionUpdateView.as_view(),
         name='material_component_group_share_distribution_update'),
    path('materials/<int:material_pk>/<int:component_pk>/seasonal_distributions/create/',
         SeasonalDistributionCreateView.as_view(),
         name='seasonal_distribution_create'),
    path('scenarios/', ScenarioListView.as_view(), name='scenario_list'),
    path('scenarios/create/', ScenarioCreateView.as_view(), name='create_scenario'),
    path('scenarios/<int:pk>/', ScenarioDetailView.as_view(), name='scenario_detail'),
    path('scenarios/<int:pk>/update/', ScenarioUpdateView.as_view(), name='scenario_update'),
    path('scenarios/<int:pk>/delete/', ScenarioDeleteView.as_view(), name='scenario_delete'),
    path('scenarios/<int:pk>/add_inventory_algorithm/', ScenarioAddInventoryAlgorithmView.as_view(),
         name='add_scenario_configuration'),
    path('scenarios/<int:scenario_pk>/change_config/<int:algorithm_pk>/',
         ScenarioAlgorithmConfigurationUpdateView.as_view(),
         name='scenario_update_config'),
    path('scenarios/<int:scenario_pk>/configuration/<int:feedstock_pk>/<int:algorithm_pk>/remove/',
         ScenarioRemoveInventoryAlgorithmView.as_view(),
         name='remove_algorithm_from_scenario'),
    path(
        'scenarios/<int:scenario_pk>/materials/<int:material_pk>/<int:component_pk>/seasonal_distributions/create/',
        SeasonalDistributionCreateView.as_view(),
        name='seasonal_distribution_create'),

    path('ajax/catchment-options/', load_catchment_options, name='ajax_catchment_options'),
    path('ajax/catchment_geometries/', CatchmentGeometryAPI.as_view(), name='ajax_catchment_geometries'),
    path('ajax/region_geometries/', RegionGeometryAPI.as_view(), name='ajax_region_geometries'),
    path('ajax/load-geodatasets/', load_geodataset_options, name='ajax_load_geodatasets'),
    path('ajax/load-algorithms/', load_algorithm_options, name='ajax_load_inventory_algorithms'),
    path('ajax/load-inventory-parameters/', load_parameter_options, name='ajax_load_inventory_parameters'),
    path('ajax/result_layer/<layer_name>/', ResultMapAPI.as_view(), name='data.result_layer'),
    path('nantes/', include('case_studies.flexibi_nantes.urls')),
]
