MAP_SET_LABELS = {
    "DE": "Germany",
    "DE-BW-RP": "Baden-Württemberg & Rheinland-Pfalz",
    "ES-CT": "Catalonia",
    "IT": "Italy",
    "IT-ST": "South Tyrol",
    "SE": "Sweden",
    "DK": "Denmark",
    "NL": "The Netherlands",
    "BE": "Belgium",
    "BE-FL-BR": "Flanders + Brussels",
}

MAP_ASPECT_LABELS = {
    "orga_level": "Administrative level",
    "collection_system": "Biowaste collection systems",
    "connection_rate": "Connection rate",
    "food_waste_category": "Accepted food waste",
    "paper_bags": "Paper products",
    "plastic_bags": "Plastic bags",
    "collection_support": "Collection aids",
    "green_waste_collection_system_count": "Green waste system count",
    "collection_point_count": "Collection points",
    "biowaste_collection_point_count": "Biowaste collection points",
    "residual_collection_point_count": "Residual waste collection points",
    "collection_point_count_ratio": "Collection-point ratio",
    "residual_frequency": "Residual waste schedule",
    "biowaste_frequency": "Biowaste schedule",
    "combined_frequency": "Combined schedule",
    "residual_collection_count": "Residual waste collection count",
    "biowaste_collection_count": "Biowaste collection count",
    "combined_collection_count": "Combined collection count",
    "collection_count_ratio": "Collection-count ratio",
    "residual_fee_system": "Residual waste fees",
    "biowaste_fee_system": "Biowaste fees",
    "combined_fee_system": "Combined fees",
    "residual_collection_amount": "Residual waste amount",
    "biowaste_collection_amount": "Biowaste amount",
    "green_waste_collection_amount": "Green waste amount",
    "waste_ratio": "Amount ratio",
    "population_density": "Population density",
    "organic_collection_amount": "Organic-fraction amount",
    "organic_waste_ratio": "Organic-fraction share",
    "biowaste_min_bin_size": "Biowaste bin size",
    "residual_min_bin_size": "Residual waste bin size",
    "min_bin_size_ratio": "Minimum bin-size ratio",
    "biowaste_required_bin_capacity": "Biowaste bin capacity",
    "residual_required_bin_capacity": "Residual waste bin capacity",
    "access_control": "Access control",
    "bin_configuration": "Bin configuration",
}

MAP_SELECTION_ROUTE_NAMES = {
    "DE": {
        "orga_level": "waste-atlas-germany-orga-level-map",
        "collection_system": "waste-atlas-germany-collection-system-map",
        "connection_rate": "waste-atlas-germany-connection-rate-map",
        "food_waste_category": "waste-atlas-germany-food-waste-category-map",
        "paper_bags": "waste-atlas-germany-paper-bags-map",
        "plastic_bags": "waste-atlas-germany-plastic-bags-map",
        "collection_support": "waste-atlas-germany-collection-support-map",
        "green_waste_collection_system_count": "waste-atlas-germany-green-waste-collection-system-count-map",
        "collection_point_count": "waste-atlas-germany-collection-point-count-map",
        "residual_frequency": "waste-atlas-germany-residual-frequency-map",
        "biowaste_frequency": "waste-atlas-germany-biowaste-frequency-map",
        "combined_frequency": "waste-atlas-germany-combined-frequency-map",
        "residual_collection_count": "waste-atlas-germany-residual-collection-count-map",
        "biowaste_collection_count": "waste-atlas-germany-biowaste-collection-count-map",
        "combined_collection_count": "waste-atlas-germany-combined-collection-count-map",
        "collection_count_ratio": "waste-atlas-germany-collection-count-ratio-map",
        "residual_fee_system": "waste-atlas-germany-residual-fee-system-map",
        "biowaste_fee_system": "waste-atlas-germany-biowaste-fee-system-map",
        "combined_fee_system": "waste-atlas-germany-combined-fee-system-map",
        "residual_collection_amount": "waste-atlas-germany-residual-collection-amount-map",
        "biowaste_collection_amount": "waste-atlas-germany-biowaste-collection-amount-map",
        "green_waste_collection_amount": "waste-atlas-germany-green-waste-collection-amount-map",
        "waste_ratio": "waste-atlas-germany-waste-ratio-map",
        "population_density": "waste-atlas-germany-population-density-map",
        "organic_collection_amount": "waste-atlas-germany-organic-collection-amount-map",
        "organic_waste_ratio": "waste-atlas-germany-organic-waste-ratio-map",
        "biowaste_min_bin_size": "waste-atlas-germany-biowaste-min-bin-size-map",
        "residual_min_bin_size": "waste-atlas-germany-residual-min-bin-size-map",
        "biowaste_required_bin_capacity": "waste-atlas-germany-biowaste-required-bin-capacity-map",
        "residual_required_bin_capacity": "waste-atlas-germany-residual-required-bin-capacity-map",
    },
    "DE-BW-RP": {
        "orga_level": "waste-atlas-bw-rp-orga-level-map",
        "collection_system": "waste-atlas-bw-rp-collection-system-map",
        "connection_rate": "waste-atlas-bw-rp-connection-rate-map",
        "food_waste_category": "waste-atlas-bw-rp-food-waste-category-map",
        "paper_bags": "waste-atlas-bw-rp-paper-bags-map",
        "plastic_bags": "waste-atlas-bw-rp-plastic-bags-map",
        "collection_support": "waste-atlas-bw-rp-collection-support-map",
        "green_waste_collection_system_count": "waste-atlas-bw-rp-green-waste-collection-system-count-map",
        "residual_frequency": "waste-atlas-bw-rp-residual-frequency-map",
        "biowaste_frequency": "waste-atlas-bw-rp-biowaste-frequency-map",
        "combined_frequency": "waste-atlas-bw-rp-combined-frequency-map",
        "residual_collection_count": "waste-atlas-bw-rp-residual-collection-count-map",
        "biowaste_collection_count": "waste-atlas-bw-rp-biowaste-collection-count-map",
        "combined_collection_count": "waste-atlas-bw-rp-combined-collection-count-map",
        "collection_count_ratio": "waste-atlas-bw-rp-collection-count-ratio-map",
        "residual_fee_system": "waste-atlas-bw-rp-residual-fee-system-map",
        "biowaste_fee_system": "waste-atlas-bw-rp-biowaste-fee-system-map",
        "combined_fee_system": "waste-atlas-bw-rp-combined-fee-system-map",
        "residual_collection_amount": "waste-atlas-bw-rp-residual-collection-amount-map",
        "biowaste_collection_amount": "waste-atlas-bw-rp-biowaste-collection-amount-map",
        "green_waste_collection_amount": "waste-atlas-bw-rp-green-waste-collection-amount-map",
        "waste_ratio": "waste-atlas-bw-rp-waste-ratio-map",
        "population_density": "waste-atlas-bw-rp-population-density-map",
        "organic_collection_amount": "waste-atlas-bw-rp-organic-collection-amount-map",
        "organic_waste_ratio": "waste-atlas-bw-rp-organic-waste-ratio-map",
        "biowaste_min_bin_size": "waste-atlas-bw-rp-biowaste-min-bin-size-map",
        "residual_min_bin_size": "waste-atlas-bw-rp-residual-min-bin-size-map",
        "biowaste_required_bin_capacity": "waste-atlas-bw-rp-biowaste-required-bin-capacity-map",
        "residual_required_bin_capacity": "waste-atlas-bw-rp-residual-required-bin-capacity-map",
    },
    "ES-CT": {
        "orga_level": "waste-atlas-catalonia-orga-level-map",
        "collection_system": "waste-atlas-catalonia-collection-system-map",
        "access_control": "waste-atlas-catalonia-access-control-map",
        "green_waste_collection_system_count": "waste-atlas-catalonia-green-waste-collection-system-count-map",
        "collection_point_count": "waste-atlas-catalonia-collection-point-count-map",
        "connection_rate": "waste-atlas-catalonia-connection-rate-map",
        "food_waste_category": "waste-atlas-catalonia-food-waste-category-map",
        "paper_bags": "waste-atlas-catalonia-paper-bags-map",
        "plastic_bags": "waste-atlas-catalonia-plastic-bags-map",
        "collection_support": "waste-atlas-catalonia-collection-support-map",
        "residual_frequency": "waste-atlas-catalonia-residual-frequency-map",
        "biowaste_frequency": "waste-atlas-catalonia-biowaste-frequency-map",
        "combined_frequency": "waste-atlas-catalonia-combined-frequency-map",
        "residual_collection_count": "waste-atlas-catalonia-residual-collection-count-map",
        "biowaste_collection_count": "waste-atlas-catalonia-biowaste-collection-count-map",
        "combined_collection_count": "waste-atlas-catalonia-combined-collection-count-map",
        "collection_count_ratio": "waste-atlas-catalonia-collection-count-ratio-map",
        "residual_fee_system": "waste-atlas-catalonia-residual-fee-system-map",
        "biowaste_fee_system": "waste-atlas-catalonia-biowaste-fee-system-map",
        "combined_fee_system": "waste-atlas-catalonia-combined-fee-system-map",
        "residual_collection_amount": "waste-atlas-catalonia-residual-collection-amount-map",
        "biowaste_collection_amount": "waste-atlas-catalonia-biowaste-collection-amount-map",
        "green_waste_collection_amount": "waste-atlas-catalonia-green-waste-collection-amount-map",
        "waste_ratio": "waste-atlas-catalonia-waste-ratio-map",
        "population_density": "waste-atlas-catalonia-population-density-map",
        "organic_collection_amount": "waste-atlas-catalonia-organic-collection-amount-map",
        "organic_waste_ratio": "waste-atlas-catalonia-organic-waste-ratio-map",
        "biowaste_min_bin_size": "waste-atlas-catalonia-biowaste-min-bin-size-map",
        "residual_min_bin_size": "waste-atlas-catalonia-residual-min-bin-size-map",
        "biowaste_required_bin_capacity": "waste-atlas-catalonia-biowaste-required-bin-capacity-map",
        "residual_required_bin_capacity": "waste-atlas-catalonia-residual-required-bin-capacity-map",
    },
    "IT": {
        "orga_level": "waste-atlas-orga-level-italy-map",
        "collection_system": "waste-atlas-italy-collection-system-map",
        "green_waste_collection_system_count": "waste-atlas-italy-green-waste-collection-system-count-map",
        "collection_point_count": "waste-atlas-italy-collection-point-count-map",
        "residual_frequency": "waste-atlas-italy-residual-frequency-map",
        "biowaste_frequency": "waste-atlas-italy-biowaste-frequency-map",
        "residual_collection_count": "waste-atlas-italy-residual-collection-count-map",
        "biowaste_collection_count": "waste-atlas-italy-biowaste-collection-count-map",
        "residual_collection_amount": "waste-atlas-italy-residual-collection-amount-map",
        "biowaste_collection_amount": "waste-atlas-italy-biowaste-collection-amount-map",
        "green_waste_collection_amount": "waste-atlas-italy-green-waste-collection-amount-map",
        "organic_collection_amount": "waste-atlas-italy-organic-collection-amount-map",
        "organic_waste_ratio": "waste-atlas-italy-organic-waste-ratio-map",
    },
    "IT-ST": {
        "orga_level": "waste-atlas-south-tyrol-orga-level-map",
        "collection_system": "waste-atlas-south-tyrol-collection-system-map",
        "green_waste_collection_system_count": "waste-atlas-south-tyrol-green-waste-collection-system-count-map",
        "collection_point_count": "waste-atlas-south-tyrol-collection-point-count-map",
        "biowaste_collection_point_count": "waste-atlas-south-tyrol-biowaste-collection-point-count-map",
        "residual_collection_point_count": "waste-atlas-south-tyrol-residual-collection-point-count-map",
        "collection_point_count_ratio": "waste-atlas-south-tyrol-collection-point-count-ratio-map",
        "residual_frequency": "waste-atlas-south-tyrol-residual-frequency-map",
        "biowaste_frequency": "waste-atlas-south-tyrol-biowaste-frequency-map",
        "combined_frequency": "waste-atlas-south-tyrol-combined-frequency-map",
        "residual_collection_count": "waste-atlas-south-tyrol-residual-collection-count-map",
        "biowaste_collection_count": "waste-atlas-south-tyrol-biowaste-collection-count-map",
        "combined_collection_count": "waste-atlas-south-tyrol-combined-collection-count-map",
        "collection_count_ratio": "waste-atlas-south-tyrol-collection-count-ratio-map",
        "residual_fee_system": "waste-atlas-south-tyrol-residual-fee-system-map",
        "biowaste_fee_system": "waste-atlas-south-tyrol-biowaste-fee-system-map",
        "combined_fee_system": "waste-atlas-south-tyrol-combined-fee-system-map",
        "residual_collection_amount": "waste-atlas-south-tyrol-residual-collection-amount-map",
        "biowaste_collection_amount": "waste-atlas-south-tyrol-biowaste-collection-amount-map",
        "green_waste_collection_amount": "waste-atlas-south-tyrol-green-waste-collection-amount-map",
        "organic_collection_amount": "waste-atlas-south-tyrol-organic-collection-amount-map",
        "organic_waste_ratio": "waste-atlas-south-tyrol-organic-waste-ratio-map",
        "biowaste_min_bin_size": "waste-atlas-south-tyrol-biowaste-min-bin-size-map",
        "residual_min_bin_size": "waste-atlas-south-tyrol-residual-min-bin-size-map",
        "min_bin_size_ratio": "waste-atlas-south-tyrol-min-bin-size-ratio-map",
    },
    "SE": {
        "orga_level": "waste-atlas-orga-level-sweden-map",
        "bin_configuration": "waste-atlas-bin-configuration-sweden-map",
    },
    "DK": {
        "orga_level": "waste-atlas-orga-level-denmark-map",
        "food_waste_category": "waste-atlas-denmark-food-waste-category-map",
        "paper_bags": "waste-atlas-denmark-paper-bags-map",
        "plastic_bags": "waste-atlas-denmark-plastic-bags-map",
        "collection_support": "waste-atlas-denmark-collection-support-map",
    },
    "NL": {
        "orga_level": "waste-atlas-orga-level-netherlands-map",
        "collection_system": "waste-atlas-collection-system-netherlands-map",
        "biowaste_frequency": "waste-atlas-biowaste-frequency-netherlands-map",
        "biowaste_collection_amount": "waste-atlas-biowaste-collection-amount-netherlands-map",
        "organic_collection_amount": "waste-atlas-organic-collection-amount-netherlands-map",
        "organic_waste_ratio": "waste-atlas-organic-waste-ratio-netherlands-map",
    },
    "BE": {
        "orga_level": "waste-atlas-orga-level-belgium-map",
    },
    "BE-FL-BR": {
        "orga_level": "waste-atlas-orga-level-belgium-flanders-map",
    },
}

MAP_SELECTION_YEARS = ("2022", "2023", "2024")


def build_map_selection_context(
    reverse_func, selected_map_set="DE", selected_aspect="orga_level"
):
    map_sets = []
    aspects_by_map_set = {}
    for map_set, aspect_routes in MAP_SELECTION_ROUTE_NAMES.items():
        aspects = [
            {
                "value": aspect,
                "label": MAP_ASPECT_LABELS[aspect],
                "url": reverse_func(route_name),
            }
            for aspect, route_name in aspect_routes.items()
        ]
        aspects_by_map_set[map_set] = aspects
        map_sets.append(
            {
                "value": map_set,
                "label": MAP_SET_LABELS[map_set],
                "selected": map_set == selected_map_set,
            }
        )
    return {
        "map_selection_map_sets": map_sets,
        "map_selection_aspects_by_map_set": aspects_by_map_set,
        "map_selection_years": MAP_SELECTION_YEARS,
        "selected_map_set": selected_map_set,
        "selected_map_aspect": selected_aspect,
    }
