"""Central registry of Waste Atlas choropleth map configurations.

Each entry is keyed by a map config key referenced from the page registry
in ``pages.py``.  The ``atlas_js_config`` template tag merges these static
values with runtime context (country, year, NUTS scope) and injects them
into the generic ``map.html`` template as JSON.

``transformName`` references a named client-side transform defined in
``static/js/waste_atlas_choropleth.js``.
"""

NO_DATA_COLOR = "#e0e0e0"
BIOWASTE_NO_COLLECTION_COLOR = "#fff696"

ADMINISTRATIVE_LEVEL_CATEGORIES_DE = [
    {
        "value": "nuts",
        "label": "Districts and district-free cities",
        "color": "#93d163",
    },
    {
        "value": "lau",
        "label": "Municipal level",
        "color": "#72a0dd",
    },
    {
        "value": "individual",
        "label": "Other administrative level",
        "color": "#d491f3",
    },
]

ADMINISTRATIVE_LEVEL_CATEGORIES_EU = [
    {
        "value": "nuts",
        "label": "NUTS 3 / county level",
        "color": "#93d163",
    },
    {
        "value": "lau",
        "label": "LAU / municipal level",
        "color": "#72a0dd",
    },
    {
        "value": "individual",
        "label": "Other administrative level",
        "color": "#d491f3",
    },
]

MAP_CONFIGS = {
    "access_control": {
        "title": "Access control for biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/access-control/",
        "dataField": "access_control",
        "categories": [
            {
                "value": "Bring point: yes",
                "label": "Bring point: yes",
                "color": "#1b9e77",
            },
            {
                "value": "Bring point: no",
                "label": "Bring point: no",
                "color": "#a6dba0",
            },
            {
                "value": "Door-to-door: yes",
                "label": "Door-to-door: yes",
                "color": "#2166ac",
            },
            {
                "value": "Door-to-door: no",
                "label": "Door-to-door: no",
                "color": "#92c5de",
            },
            {
                "value": "Bring point: yes | Door-to-door: yes",
                "label": "Bring point: yes | Door-to-door: yes",
                "color": "#542788",
            },
            {
                "value": "Bring point: no | Door-to-door: no",
                "label": "Bring point: no | Door-to-door: no",
                "color": "#c2a5cf",
            },
            {
                "value": "Bring point: yes | Door-to-door: no",
                "label": "Bring point: yes | Door-to-door: no",
                "color": "#b2182b",
            },
            {
                "value": "Bring point: no | Door-to-door: yes",
                "label": "Bring point: no | Door-to-door: yes",
                "color": "#ef8a62",
            },
            {
                "value": "No separate biowaste collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Access control",
        "fileBase": "access_control",
    },
    "bin_configuration": {
        "title": "Bin configuration of waste fractions",
        "dataUrl": "/waste_collection/api/waste-atlas/bin-configuration/",
        "dataField": "bin_configuration",
        "categories": [
            {
                "value": "Separate bins",
                "label": "Separate bins",
                "color": "#4dbf8b",
            },
            {
                "value": "Optical bag sorting",
                "label": "Optical bag sorting",
                "color": "#66a3ff",
            },
            {
                "value": "Four compartments bin",
                "label": "Four compartments bin",
                "exportLabel": "4-compartment bin",
                "color": "#f2a541",
            },
            {
                "value": "Two compartments bin",
                "label": "Two compartments bin",
                "exportLabel": "2-compartment bin",
                "color": "#9c89d9",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Bin configuration",
        "fileBase": "map34_bin_configuration_sweden",
    },
    "biowaste_collection_amount": {
        "title": "Specifically collected amount of biowaste",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-amount/",
        "dataField": "_classified",
        "transformName": "biowasteCollectionAmount",
        "categories": [
            {
                "value": "very_high",
                "label": "151–236 (very high)",
                "color": "#1a9850",
            },
            {
                "value": "high",
                "label": "101–150 (high)",
                "color": "#66bd63",
            },
            {
                "value": "medium",
                "label": "51–100 (medium)",
                "color": "#a6d96a",
            },
            {
                "value": "low",
                "label": "0–50 (low)",
                "color": "#d9f0d3",
            },
            {
                "value": "no_bio",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collected amount (kg/cap/a)",
        "fileBase": "biowaste_collection_amount",
        "outlineGeoJsonUrl": "/waste_collection/api/waste-atlas/biowaste-collection-amount/acpv-outline-geojson/",
        "outlineStrokeColor": "#ffffff",
        "outlineStrokeOpacity": 0.95,
        "outlineStrokeWidth": 1.35,
        "overlayPatternField": "_has_acpv_overlay",
        "overlayPatternLegendLabel": "Hatched = aggregated value",
        "exportOverlayPatternLegendLabel": "Hatched = aggregated value",
        "numericField": "amount",
        "quartileColors": ["#d9f0d3", "#a6d96a", "#66bd63", "#1a9850"],
        "quartileSpecialCases": [
            {
                "field": "no_collection",
                "classValue": "no_bio",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            }
        ],
    },
    "biowaste_collection_count": {
        "title": "Annual biowaste collection count",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-count/",
        "dataField": "_classified",
        "transformName": "biowasteCollectionCount",
        "categories": [
            {
                "value": "twice_weekly",
                "label": "104 per year (2× per week)",
                "color": "#08519c",
            },
            {
                "value": "weekly",
                "label": "52 per year (weekly)",
                "color": "#1E90FF",
            },
            {
                "value": "biweekly",
                "label": "26 per year (every 2 weeks)",
                "color": "#66CDAA",
            },
            {
                "value": "less_frequent",
                "label": "Less than 26 per year",
                "color": "#4b2a60",
            },
            {
                "value": "seasonal",
                "label": "Seasonally varying",
                "color": "#F4A460",
            },
            {
                "value": "no_door_to_door",
                "label": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection count",
        "fileBase": "biowaste_collection_count",
        "numericField": "collection_count",
        "quartileColors": ["#4b2a60", "#66CDAA", "#1E90FF", "#08519c"],
        "quartilePreserveClasses": ["seasonal", "no_door_to_door"],
    },
    "biowaste_collection_point_count": {
        "title": "Number of biowaste collection points",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-point-count/",
        "dataField": "_classified",
        "transformName": "biowasteCollectionPointCount",
        "categories": [
            {
                "value": "very_high",
                "label": "≥ 59",
                "color": "#005a32",
            },
            {
                "value": "high",
                "label": "10 – 58",
                "color": "#31a354",
            },
            {
                "value": "medium",
                "label": "2 – 9",
                "color": "#74c476",
            },
            {
                "value": "very_low",
                "label": "Collection points, but no data",
                "color": NO_DATA_COLOR,
            },
            {
                "value": "full_dtd",
                "label": "Full door-to-door / no data",
                "color": NO_DATA_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Biowaste collection points",
        "fileBase": "biowaste_collection_point_count",
        "numericField": "collection_point_count",
        "quartileColors": ["#edf8e9", "#74c476", "#31a354", "#005a32"],
        "quartilePreserveClasses": ["full_dtd"],
    },
    "biowaste_collection_system": {
        "title": "Biowaste collection system",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-system/",
        "dataField": "collection_system",
        "categories": [
            {
                "value": "Door to door",
                "label": "PAP total",
                "color": "#d0fcd5",
            },
            {
                "value": "Mixed door-to-door and bring point",
                "label": "PAP parcial",
                "color": "#a8e6cf",
            },
            {
                "value": "Bring point",
                "label": "Bring point",
                "color": "#3dc7dc",
            },
            {
                "value": "No separate collection",
                "label": "No separate collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "legendTitle": "Collection system",
        "fileBase": "catalonia_biowaste_collection_system",
    },
    "biowaste_fee_system": {
        "title": "Fee system for biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-fee-system/",
        "dataField": "fee_system",
        "categories": [
            {
                "value": "Flat fee",
                "label": "Flat rate",
                "color": "#228B22",
            },
            {
                "value": "Flexible",
                "label": "Flexible",
                "color": "#00ced1",
            },
            {
                "value": "Flexible+",
                "label": "Flexible+",
                "color": "#FFD700",
            },
            {
                "value": "Pay as you throw (PAYT)",
                "label": "Pay as you throw",
                "color": "#4b2a60",
            },
            {
                "value": "No fee",
                "label": "No fee",
                "color": "#e41a1c",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Fee system",
        "fileBase": "biowaste_fee_system",
    },
    "biowaste_frequency": {
        "title": "Collection frequency setting for biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-frequency-type/",
        "dataField": "_classified",
        "transformName": "biowasteFrequency",
        "categories": [
            {
                "value": "Fixed-Seasonal",
                "label": "Seasonally varying",
                "color": "#2e8b57",
            },
            {
                "value": "Fixed-Flexible",
                "label": "Flexible",
                "color": "#4169e1",
            },
            {
                "value": "Fixed",
                "label": "Fixed",
                "color": "#8c9eff",
            },
            {
                "value": "no_bio_collection",
                "label": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection frequency setting",
        "fileBase": "biowaste_collection_schedule",
    },
    "biowaste_impurity": {
        "title": "Biowaste impurity rate",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-impurity/",
        "dataField": "_classified",
        "transformName": "biowasteImpurity",
        "categories": [
            {
                "value": "very_low",
                "label": "0–5 (very low)",
                "color": "#1a9850",
            },
            {
                "value": "low",
                "label": "5–10 (low)",
                "color": "#66bd63",
            },
            {
                "value": "medium",
                "label": "10–20 (medium)",
                "color": "#fee08b",
            },
            {
                "value": "high",
                "label": "20–40 (high)",
                "color": "#f46d43",
            },
            {
                "value": "very_high",
                "label": "> 40 (very high)",
                "color": "#d73027",
            },
            {
                "value": "no_collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Impurity rate (%)",
        "fileBase": "biowaste_impurity",
        "collectionYear": 2024,
        "numericField": "impurity_rate",
        "quartileColors": ["#1a9850", "#66bd63", "#f46d43", "#d73027"],
        "quartileSpecialCases": [
            {
                "field": "no_collection",
                "classValue": "no_collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            }
        ],
    },
    "biowaste_min_bin_size": {
        "title": "Smallest available bin size for biowaste (L)",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-min-bin-size/",
        "dataField": "_classified",
        "transformName": "biowasteMinBinSize",
        "categories": [
            {
                "value": "xs",
                "label": "≤ 26.5",
                "color": "#d9f0d3",
            },
            {
                "value": "small",
                "label": "27 – 60",
                "color": "#a6d96a",
            },
            {
                "value": "medium",
                "label": "61 – 120",
                "color": "#1a9850",
            },
            {
                "value": "large",
                "label": "121 – 140",
                "color": "#006837",
            },
            {
                "value": "no_door_to_door",
                "label": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Min. bin size (L)",
        "fileBase": "biowaste_min_bin_size",
        "numericField": "min_bin_size",
        "quartileColors": ["#d9f0d3", "#a6d96a", "#1a9850", "#006837"],
        "quartilePreserveClasses": ["no_door_to_door"],
    },
    "biowaste_required_bin_capacity": {
        "title": "Required bin capacity for biowaste (L/reference unit)",
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-required-bin-capacity/",
        "dataField": "_classified",
        "transformName": "biowasteRequiredBinCapacity",
        "categories": [
            {
                "value": "very_low",
                "label": "≤ 5",
                "color": "#d9f0d3",
            },
            {
                "value": "low",
                "label": "6 – 10",
                "color": "#a6d96a",
            },
            {
                "value": "medium",
                "label": "11 – 20",
                "color": "#66bd63",
            },
            {
                "value": "high",
                "label": "21 – 60",
                "color": "#1a9850",
            },
            {
                "value": "very_high",
                "label": "> 60",
                "color": "#006837",
            },
            {
                "value": "no_door_to_door",
                "label": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Minimum bin capacity (L/unit)",
        "fileBase": "biowaste_required_bin_capacity",
        "numericField": "required_bin_capacity",
        "quartileColors": ["#d9f0d3", "#a6d96a", "#1a9850", "#006837"],
        "quartilePreserveClasses": ["no_door_to_door"],
    },
    "collection_count_ratio": {
        "title": "Annual collection-count ratio: biowaste vs residual waste",
        "dataUrl": "/waste_collection/api/waste-atlas/collection-count-ratio/",
        "dataField": "_classified",
        "transformName": "collectionCountRatio",
        "categories": [
            {
                "value": "bio_2x",
                "label": "2 : 1 (biowaste collected twice as often)",
                "exportLabel": "2:1 bio > residual",
                "color": "#1b9e77",
            },
            {
                "value": "same",
                "label": "1 : 1 (collected equally often)",
                "exportLabel": "1:1 equal",
                "color": "#7570b3",
            },
            {
                "value": "bio_half",
                "label": "1 : 2 (residual collected twice as often)",
                "exportLabel": "1:2 bio < residual",
                "color": "#d95f02",
            },
            {
                "value": "seasonal",
                "label": "Seasonally varying ratio",
                "exportLabel": "Seasonal",
                "color": "#F4A460",
            },
            {
                "value": "no_bio",
                "label": "No separate door-to-door collection",
                "exportLabel": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Bio : residual count",
        "fileBase": "collection_count_ratio",
    },
    "collection_point_count": {
        "title": "Number of collection points",
        "dataUrl": "/waste_collection/api/waste-atlas/collection-point-count/",
        "dataField": "_classified",
        "transformName": "collectionPointCount",
        "categories": [
            {
                "value": "high",
                "label": "> 10",
                "color": "#d95f0e",
            },
            {
                "value": "medium",
                "label": "6 – 10",
                "color": "#fe9929",
            },
            {
                "value": "low",
                "label": "2 – 5",
                "color": "#fed98e",
            },
            {
                "value": "very_low",
                "label": "Collection point",
                "color": "#ffffd4",
            },
            {
                "value": "full_dtd",
                "label": "Full Door to door/No data",
                "color": NO_DATA_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection points",
        "fileBase": "collection_point_count",
        "numericField": "collection_point_count",
        "quartileColors": ["#ffffd4", "#fed98e", "#fe9929", "#d95f0e"],
        "quartilePreserveClasses": ["full_dtd"],
    },
    "collection_point_count_ratio": {
        "title": "Collection points: biowaste vs residual waste",
        "dataUrl": "/waste_collection/api/waste-atlas/collection-point-count-ratio/",
        "dataField": "_classified",
        "transformName": "collectionPointCountRatio",
        "categories": [
            {
                "value": "bio_more",
                "label": "More biowaste than residual points",
                "exportLabel": "Bio > residual",
                "color": "#1b9e77",
            },
            {
                "value": "same",
                "label": "Equal number of points",
                "exportLabel": "Equal",
                "color": "#7570b3",
            },
            {
                "value": "bio_less",
                "label": "Fewer biowaste than residual points",
                "exportLabel": "Bio < residual",
                "color": "#d95f02",
            },
            {
                "value": "no_bio",
                "label": "No biowaste collection-point data",
                "exportLabel": "No bio data",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Bio / residual points",
        "fileBase": "collection_point_count_ratio",
    },
    "collection_support": {
        "title": "Accepted materials for biowaste collection aids",
        "dataUrl": "/waste_collection/api/waste-atlas/collection-support/",
        "dataField": "_classified",
        "transformName": "collectionSupport",
        "categories": [
            {
                "value": "paper_a_plastic_a",
                "label": "Paper allowed, compostable plastic bags allowed",
                "color": "#4caf50",
            },
            {
                "value": "paper_f_plastic_a",
                "label": "Paper forbidden, compostable plastic bags allowed",
                "color": "#fdd835",
            },
            {
                "value": "paper_a_plastic_f",
                "label": "Paper allowed, compostable plastic bags forbidden",
                "color": "#2196f3",
            },
            {
                "value": "paper_a_plastic_n",
                "label": "Paper allowed, compostable plastic bags unknown",
                "color": "#90caf9",
            },
            {
                "value": "paper_f_plastic_f",
                "label": "Paper forbidden, compostable plastic bags forbidden",
                "color": "#7e57c2",
            },
            {
                "value": "paper_n_plastic_f",
                "label": "Paper unknown, compostable plastic bags forbidden",
                "color": "#ff7043",
            },
            {
                "value": "no_collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection aids",
        "fileBase": "collection_aids",
    },
    "collection_system": {
        "title": "Primary collection system for biowaste",
        "dataUrl": "/waste_collection/api/waste-atlas/collection-system/",
        "dataField": "collection_system",
        "categories": [
            {
                "value": "Door to door",
                "label": "Door to door collection",
                "color": "#d0fcd5",
            },
            {
                "value": "Mixed door-to-door and bring point",
                "label": "Mixed door-to-door and bring point",
                "color": "#a8e6cf",
            },
            {
                "value": "Recycling centre",
                "label": "Recycling centre",
                "color": "#3dc79b",
            },
            {
                "value": "Bring point",
                "label": "Bring point",
                "color": "#3dc7dc",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection system",
        "fileBase": "collection_systems",
        "conflictUrl": "/waste_collection/api/waste-atlas/collection-conflicts/",
        "conflictTheme": "collection_system",
        "conflictOverlayLabel": "Conflicting catchments (>1 collection system)",
    },
    "combined_collection_count": {
        "title": "Annual collection count: biowaste vs residual waste",
        "dataUrl": "/waste_collection/api/waste-atlas/combined-collection-count/",
        "dataField": "_classified",
        "transformName": "combinedCollectionCount",
        "categories": [
            {
                "value": "bio_more_res_more",
                "label": "Biowaste more often, residual waste more often",
                "exportLabel": "More / more",
                "color": "#64427b",
            },
            {
                "value": "bio_more_res_bi",
                "label": "Biowaste more often, residual waste every two weeks",
                "exportLabel": "More / 2 weeks",
                "color": "#9c67a5",
            },
            {
                "value": "bio_more_res_less",
                "label": "Biowaste more often, residual waste less frequent",
                "exportLabel": "More / less",
                "color": "#c5a5cf",
            },
            {
                "value": "bio_bi_res_more",
                "label": "Biowaste every two weeks, residual waste more often",
                "exportLabel": "2 weeks / more",
                "color": "#2862a8",
            },
            {
                "value": "bio_bi_res_bi",
                "label": "Biowaste every two weeks, residual waste every two weeks",
                "exportLabel": "2 weeks / 2 weeks",
                "color": "#4292c6",
            },
            {
                "value": "bio_bi_res_less",
                "label": "Biowaste every two weeks, residual waste less frequent",
                "exportLabel": "2 weeks / less",
                "color": "#73b2d8",
            },
            {
                "value": "bio_less_res_more",
                "label": "Biowaste less frequent, residual waste more often",
                "exportLabel": "Less / more",
                "color": "#e33e88",
            },
            {
                "value": "bio_less_res_bi",
                "label": "Biowaste less frequent, residual waste every two weeks",
                "exportLabel": "Less / 2 weeks",
                "color": "#ff7986",
            },
            {
                "value": "bio_less_res_less",
                "label": "Biowaste less frequent, residual waste less frequent",
                "exportLabel": "Less / less",
                "color": "#f7b1b8",
            },
            {
                "value": "no_bio",
                "label": "No separate door-to-door collection",
                "exportLabel": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection count",
        "exportLegendTitle": "Collection count: bio / residual",
        "fileBase": "combined_collection_count",
    },
    "combined_collection_system": {
        "title": "Collection system combination: biowaste vs residual waste",
        "dataUrl": "/waste_collection/api/waste-atlas/combined-collection-system/",
        "dataField": "_classified",
        "transformName": "combinedCollectionSystem",
        "categories": [
            {
                "value": "Door to door / Door to door",
                "label": "PAP total / PAP total",
                "exportLabel": "PAP total / PAP total",
                "color": "#238b45",
            },
            {
                "value": "Door to door / Bring point",
                "label": "PAP total / Bring point",
                "exportLabel": "PAP total / BP",
                "color": "#74c476",
            },
            {
                "value": "Door to door / No separate collection",
                "label": "PAP total / no residual",
                "exportLabel": "PAP total / none",
                "color": "#bae4b3",
            },
            {
                "value": "Mixed door-to-door and bring point / Door to door",
                "label": "PAP parcial / PAP total",
                "exportLabel": "PAP parcial / PAP total",
                "color": "#2b8cbe",
            },
            {
                "value": "Mixed door-to-door and bring point / Bring point",
                "label": "PAP parcial / Bring point",
                "exportLabel": "PAP parcial / BP",
                "color": "#7bccc4",
            },
            {
                "value": "Mixed door-to-door and bring point / No separate collection",
                "label": "PAP parcial / no residual",
                "exportLabel": "PAP parcial / none",
                "color": "#bae4bc",
            },
            {
                "value": "Bring point / Door to door",
                "label": "Bring point / PAP total",
                "exportLabel": "BP / PAP total",
                "color": "#756bb1",
            },
            {
                "value": "Bring point / Bring point",
                "label": "Bring point / Bring point",
                "exportLabel": "BP / BP",
                "color": "#9e9ac8",
            },
            {
                "value": "Bring point / No separate collection",
                "label": "Bring point / no residual",
                "exportLabel": "BP / none",
                "color": "#cbc9e2",
            },
            {
                "value": "No separate collection / Door to door",
                "label": "No biowaste / PAP total",
                "exportLabel": "None / PAP total",
                "color": "#fd8d3c",
            },
            {
                "value": "No separate collection / Bring point",
                "label": "No biowaste / Bring point",
                "exportLabel": "None / BP",
                "color": "#fdae6b",
            },
            {
                "value": "No separate collection / No separate collection",
                "label": "No separate collection",
                "exportLabel": "None / none",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection system: bio / residual",
        "fileBase": "catalonia_combined_collection_system",
    },
    "combined_fee_system": {
        "title": "Fee system: biowaste vs residual waste",
        "dataUrl": "/waste_collection/api/waste-atlas/combined-fee-system/",
        "dataField": "_classified",
        "transformName": "combinedFeeSystem",
        "categories": [
            {
                "value": "flex_flex",
                "label": "BWB & RWB: Flexible",
                "exportLabel": "BWB & RWB: Flexible",
                "color": "#00ced1",
            },
            {
                "value": "no_fee_flex",
                "label": "BWB: No fee | RWB: Flexible",
                "exportLabel": "BWB: No fee | RWB: Flexible",
                "color": "#80e6e8",
            },
            {
                "value": "payt_payt",
                "label": "BWB & RWB: PAYT",
                "exportLabel": "BWB & RWB: PAYT",
                "color": "#4b2a60",
            },
            {
                "value": "flex_payt",
                "label": "BWB: Flexible | RWB: PAYT",
                "exportLabel": "BWB: Flexible | RWB: PAYT",
                "color": "#7b5a8c",
            },
            {
                "value": "no_fee_payt",
                "label": "BWB: No fee | RWB: PAYT",
                "exportLabel": "BWB: No fee | RWB: PAYT",
                "color": "#b6a1c5",
            },
            {
                "value": "flex_flex_plus",
                "label": "BWB: Flexible | RWB: Flexible+",
                "exportLabel": "BWB: Flexible | RWB: Flexible+",
                "color": "#ffd700",
            },
            {
                "value": "no_bio",
                "label": "No separate door-to-door collection",
                "exportLabel": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
            {
                "value": "other_combined",
                "label": "Other combinations",
                "exportLabel": "Other combinations",
                "color": "#4daf4a",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Fee: bio / residual",
        "exportLegendBottomColumns": 2,
        "fileBase": "combined_fee_system",
    },
    "combined_frequency": {
        "title": "Collection frequency setting: biowaste vs residual waste",
        "dataUrl": "/waste_collection/api/waste-atlas/combined-frequency-type/",
        "dataField": "_classified",
        "transformName": "combinedFrequency",
        "categories": [
            {
                "value": "bio_seasonal_res_flexible",
                "label": "Biowaste seasonal, residual flexible",
                "exportLabel": "Seasonal / flexible",
                "color": "#2e8b57",
            },
            {
                "value": "bio_flexible_res_flexible",
                "label": "Biowaste flexible, residual flexible",
                "exportLabel": "Flexible / flexible",
                "color": "#4169e1",
            },
            {
                "value": "bio_fixed_res_flexible",
                "label": "Biowaste fixed, residual flexible",
                "exportLabel": "Fixed / flexible",
                "color": "#9ecae1",
            },
            {
                "value": "bio_seasonal_res_fixed",
                "label": "Biowaste seasonal, residual fixed",
                "exportLabel": "Seasonal / fixed",
                "color": "#66cdaa",
            },
            {
                "value": "bio_flexible_res_fixed",
                "label": "Biowaste flexible, residual fixed",
                "exportLabel": "Flexible / fixed",
                "color": "#e08840",
            },
            {
                "value": "bio_fixed_res_fixed",
                "label": "Biowaste fixed, residual fixed",
                "exportLabel": "Fixed / fixed",
                "color": "#6a51a3",
            },
            {
                "value": "no_bio_collection",
                "label": "No separate door-to-door collection",
                "exportLabel": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection frequency setting",
        "exportLegendTitle": "Schedule: bio / residual",
        "fileBase": "combined_collection_schedule",
    },
    "connection_rate": {
        "title": "Connection rate for door-to-door biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/connection-rate/",
        "dataField": "_classified",
        "transformName": "connectionRate",
        "categories": [
            {
                "value": "75-100",
                "label": "100% – 75%",
                "color": "#00608e",
            },
            {
                "value": "50-74",
                "label": "74% – 50%",
                "color": "#0090cb",
            },
            {
                "value": "25-49",
                "label": "49% – 25%",
                "color": "#7fcce9",
            },
            {
                "value": "0-24",
                "label": "24% – 0%",
                "color": "#d1e7e6",
            },
            {
                "value": "no_d2d",
                "label": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Connection rate",
        "fileBase": "connection_rate",
        "numericField": "connection_rate",
        "quartileDisplayMultiplier": 100,
        "tooltipFields": [{"field": "reporting_year", "label": "Reporting year"}],
        "quartileColors": ["#d1e7e6", "#7fcce9", "#0090cb", "#00608e"],
        "quartilePreserveClasses": ["no_d2d"],
    },
    "participation_policy": {
        "title": "Participation Policy",
        "dataUrl": "/waste_collection/api/waste-atlas/participation-policy/",
        "dataField": "participation_policy",
        "categories": [
            {
                "value": "no_bio_collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
            {
                "value": "MANDATORY",
                "label": "Mandatory",
                "color": "#00608e",
            },
            {
                "value": "MANDATORY_WITH_HOME_COMPOSTER_EXCEPTION",
                "label": "Mandatory, except home composters",
                "color": "#0090cb",
            },
            {
                "value": "VOLUNTARY",
                "label": "Voluntary",
                "color": "#7fcce9",
            },
            {
                "value": "not_specified",
                "label": "Not specified",
                "color": NO_DATA_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Participation Policy",
        "fileBase": "participation_policy",
    },
    "denmark_collection_support": {
        "title": "Accepted materials for biowaste collection aids",
        "dataUrl": "/waste_collection/api/waste-atlas/regular-plastic-collection-support/",
        "dataField": "_classified",
        "transformName": "denmarkCollectionSupport",
        "categories": [
            {
                "value": "paper_a_plastic_a",
                "label": "Paper allowed, plastic bags allowed",
                "color": "#4caf50",
            },
            {
                "value": "paper_f_plastic_a",
                "label": "Paper forbidden, plastic bags allowed",
                "color": "#fdd835",
            },
            {
                "value": "paper_a_plastic_f",
                "label": "Paper allowed, plastic bags forbidden",
                "color": "#2196f3",
            },
            {
                "value": "paper_a_plastic_n",
                "label": "Paper allowed, plastic bags unknown",
                "color": "#90caf9",
            },
            {
                "value": "paper_f_plastic_f",
                "label": "Paper forbidden, plastic bags forbidden",
                "color": "#7e57c2",
            },
            {
                "value": "paper_n_plastic_f",
                "label": "Paper unknown, plastic bags forbidden",
                "color": "#ff7043",
            },
            {
                "value": "no_collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection aids",
        "fileBase": "map48_collection_aids_denmark",
    },
    "denmark_food_waste_category": {
        "title": "Accepted food waste in biowaste",
        "dataUrl": "/waste_collection/api/waste-atlas/food-waste-category/",
        "dataField": "food_waste_category",
        "categories": [
            {
                "value": "All four materials",
                "label": "All food waste",
                "color": "#2c7da0",
            },
            {
                "value": "No raw meat",
                "label": "No raw animal products",
                "color": "#61a35c",
            },
            {
                "value": "No meat",
                "label": "No animal products",
                "color": "#41b6c4",
            },
            {
                "value": "Only raw plant-based",
                "label": "Only raw plant-based products",
                "color": "#9ac93e",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Accepted food waste",
        "fileBase": "map45_food_waste_category_denmark",
    },
    "denmark_paper_bags": {
        "title": "Use of paper bags for biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/paper-bags/",
        "dataField": "status",
        "categories": [
            {
                "value": "allowed",
                "label": "Allowed",
                "color": "#2196f3",
            },
            {
                "value": "forbidden",
                "label": "Forbidden",
                "color": "#f57c00",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Paper bags",
        "fileBase": "map46_paper_bags_denmark",
    },
    "denmark_plastic_bags": {
        "title": "Use of plastic bags for biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/regular-plastic-bags/",
        "dataField": "status",
        "categories": [
            {
                "value": "allowed",
                "label": "Allowed",
                "color": "#fdd835",
            },
            {
                "value": "forbidden",
                "label": "Forbidden",
                "color": "#78909c",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Plastic bags",
        "fileBase": "map47_plastic_bags_denmark",
    },
    "food_waste_category": {
        "title": "Accepted food waste in biowaste",
        "dataUrl": "/waste_collection/api/waste-atlas/food-waste-category/",
        "dataField": "food_waste_category",
        "categories": [
            {
                "value": "All four materials",
                "label": "All food waste",
                "color": "#2c7da0",
            },
            {
                "value": "No raw meat",
                "label": "No raw animal products",
                "color": "#61a35c",
            },
            {
                "value": "No meat",
                "label": "No animal products",
                "color": "#41b6c4",
            },
            {
                "value": "Only raw plant-based",
                "label": "Only raw plant-based products",
                "color": "#9ac93e",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Accepted food waste",
        "fileBase": "food_waste_category",
    },
    "green_waste_collection_amount": {
        "title": "Specifically collected amount of green waste",
        "dataUrl": "/waste_collection/api/waste-atlas/green-waste-collection-amount/",
        "dataField": "_classified",
        "transformName": "greenWasteCollectionAmount",
        "categories": [
            {
                "value": "very_high",
                "label": "151 and more (very high)",
                "color": "#1b9e77",
            },
            {
                "value": "high",
                "label": "101–150 (high)",
                "color": "#66a61e",
            },
            {
                "value": "medium",
                "label": "51–100 (medium)",
                "color": "#a6d854",
            },
            {
                "value": "low",
                "label": "0–50 (low)",
                "color": "#d9f0d3",
            },
            {
                "value": "no_green",
                "label": "No separate green waste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collected amount (kg/cap/a)",
        "fileBase": "green_waste_collection_amount",
        "numericField": "amount",
        "quartileColors": ["#d9f0d3", "#a6d854", "#66a61e", "#1b9e77"],
        "quartileSpecialCases": [
            {
                "field": "no_collection",
                "classValue": "no_green",
                "label": "No separate green waste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            }
        ],
    },
    "green_waste_collection_system_count": {
        "title": "Number of green waste collection systems per catchment",
        "dataUrl": "/waste_collection/api/waste-atlas/green-waste-collection-system-count/",
        "dataField": "_classified",
        "transformName": "greenWasteCollectionSystemCount",
        "categories": [
            {
                "value": "3plus",
                "label": "3 or more collection systems",
                "color": "#1b9e77",
            },
            {
                "value": "2",
                "label": "2 collection systems",
                "color": "#66a61e",
            },
            {
                "value": "1",
                "label": "1 collection system",
                "color": "#a6d854",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Number of collection systems",
        "fileBase": "green_waste_collection_system_count",
    },
    "min_bin_size_ratio": {
        "title": "Ratio of minimum bin sizes (Biowaste / Residual waste)",
        "dataUrl": "/waste_collection/api/waste-atlas/min-bin-size-ratio/",
        "dataField": "_classified",
        "transformName": "minBinSizeRatio",
        "categories": [
            {
                "value": "bio_larger",
                "label": "Biowaste bin larger than residual waste bin",
                "exportLabel": "Bio bin larger",
                "color": "#1b9e77",
            },
            {
                "value": "same",
                "label": "Biowaste and residual waste bins equal size",
                "exportLabel": "Equal bin size",
                "color": "#7570b3",
            },
            {
                "value": "bio_smaller",
                "label": "Biowaste bin smaller than residual waste bin",
                "exportLabel": "Bio bin smaller",
                "color": "#d95f02",
            },
            {
                "value": "no_bio",
                "label": "No separate door-to-door collection",
                "exportLabel": "No separate door-to-door collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Biowaste / Residual waste",
        "fileBase": "min_bin_size_ratio",
    },
    "orga_level": {
        "title": "Administrative level of collectors",
        "dataUrl": "/waste_collection/api/waste-atlas/collector-orga-level/",
        "catchmentDataUrl": "/waste_collection/api/waste-atlas/catchment/collector-geojson/",
        "dataField": "orga_level",
        "categories": ADMINISTRATIVE_LEVEL_CATEGORIES_DE,
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Administrative level",
        "fileBase": "collector_administrative_level",
    },
    "orga_level_eu": {
        "title": "Administrative level of collectors",
        "dataUrl": "/waste_collection/api/waste-atlas/collector-orga-level/",
        "catchmentDataUrl": "/waste_collection/api/waste-atlas/catchment/collector-geojson/",
        "dataField": "orga_level",
        "categories": ADMINISTRATIVE_LEVEL_CATEGORIES_EU,
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Administrative level",
        "fileBase": "map29_orga_level_italy",
    },
    "collection_orga_level": {
        "title": "Administrative level of collections",
        "dataUrl": "/waste_collection/api/waste-atlas/collection-orga-level/",
        "catchmentDataUrl": "/waste_collection/api/waste-atlas/catchment/collection-geojson/",
        "dataField": "orga_level",
        "categories": ADMINISTRATIVE_LEVEL_CATEGORIES_DE,
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Administrative level",
        "fileBase": "collection_administrative_level",
    },
    "collection_orga_level_eu": {
        "title": "Administrative level of collections",
        "dataUrl": "/waste_collection/api/waste-atlas/collection-orga-level/",
        "catchmentDataUrl": "/waste_collection/api/waste-atlas/catchment/collection-geojson/",
        "dataField": "orga_level",
        "categories": ADMINISTRATIVE_LEVEL_CATEGORIES_EU,
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Administrative level",
        "fileBase": "collection_administrative_level",
    },
    "organic_collection_amount": {
        "title": "Aggregated collected amount of organic fractions (kg/cap/a)",
        "dataUrl": "/waste_collection/api/waste-atlas/organic-collection-amount/",
        "dataField": "_classified",
        "transformName": "organicCollectionAmount",
        "categories": [
            {
                "value": "very_high",
                "label": "> 300",
                "color": "#1a9850",
            },
            {
                "value": "high",
                "label": "201 – 300",
                "color": "#66bd63",
            },
            {
                "value": "medium",
                "label": "101 – 200",
                "color": "#a6d96a",
            },
            {
                "value": "low",
                "label": "51 – 100",
                "color": "#d9f0d3",
            },
            {
                "value": "very_low",
                "label": "0 – 50",
                "color": "#f7fcf0",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Organic-fraction amount (kg/cap/a)",
        "fileBase": "organic_collection_amount",
        "numericField": "amount",
        "quartileColors": ["#d9f0d3", "#a6d96a", "#66bd63", "#1a9850"],
    },
    "organic_waste_ratio": {
        "title": "Organic stream separation rate (%)",
        "dataUrl": "/waste_collection/api/waste-atlas/organic-waste-ratio/",
        "dataField": "_classified",
        "transformName": "organicWasteRatio",
        "categories": [
            {
                "value": "very_high",
                "label": "> 66 (much more organic than residual)",
                "color": "#0868ac",
            },
            {
                "value": "high",
                "label": "51–66 (more organic than residual)",
                "color": "#43a2ca",
            },
            {
                "value": "medium",
                "label": "34–50 (more residual than organic)",
                "color": "#7bccc4",
            },
            {
                "value": "low",
                "label": "0–33 (low organic share)",
                "color": "#bae4bc",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Organic stream separation rate (%)",
        "fileBase": "organic_waste_ratio",
        "numericField": "ratio",
        "quartileDisplayMultiplier": 100,
        "quartileColors": ["#bae4bc", "#7bccc4", "#43a2ca", "#0868ac"],
    },
    "paper_bags": {
        "title": "Use of paper bags for biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/paper-bags/",
        "dataField": "status",
        "categories": [
            {
                "value": "allowed",
                "label": "Allowed",
                "color": "#2196f3",
            },
            {
                "value": "forbidden",
                "label": "Forbidden",
                "color": "#f57c00",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Paper bags",
        "fileBase": "paper_bags",
    },
    "plastic_bags": {
        "title": "Use of compostable plastic bags for biowaste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/plastic-bags/",
        "dataField": "status",
        "categories": [
            {
                "value": "allowed",
                "label": "Allowed",
                "color": "#fdd835",
            },
            {
                "value": "forbidden",
                "label": "Forbidden",
                "color": "#78909c",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Plastic bags",
        "fileBase": "plastic_bags",
    },
    "population_density": {
        "title": "Population density",
        "dataUrl": "/waste_collection/api/waste-atlas/population/",
        "dataField": "_classified",
        "transformName": "populationDensity",
        "categories": [
            {
                "value": "urban",
                "label": "Urban (> 1 500 / km²)",
                "color": "#ffea46",
            },
            {
                "value": "suburban",
                "label": "Suburban (300 – 1 500 / km²)",
                "color": "#7d7c78",
            },
            {
                "value": "rural",
                "label": "Rural (< 300 / km²)",
                "color": "#00204d",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Population density",
        "fileBase": "population_density",
        "numericField": "population_density",
        "quartileColors": ["#00204d", "#7d7c78", "#ffea46", "#fff59d"],
    },
    "residual_collection_amount": {
        "title": "Specifically collected amount of residual waste",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-amount/",
        "dataField": "_classified",
        "transformName": "residualCollectionAmount",
        "categories": [
            {
                "value": "high",
                "label": "226–311 (high)",
                "color": "#d95f0e",
            },
            {
                "value": "medium",
                "label": "151–225 (medium)",
                "color": "#fe9929",
            },
            {
                "value": "low",
                "label": "76–150 (low)",
                "color": "#fed98e",
            },
            {
                "value": "very_low",
                "label": "0 – 75 (Very low)",
                "color": "#ffffd4",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collected amount (kg/cap/a)",
        "fileBase": "residual_collection_amount",
        "numericField": "amount",
        "quartileColors": ["#ffffd4", "#fed98e", "#fe9929", "#d95f0e"],
    },
    "residual_collection_count": {
        "title": "Annual residual waste collection count",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-count/",
        "dataField": "_classified",
        "transformName": "residualCollectionCount",
        "categories": [
            {
                "value": "twice_weekly",
                "label": "104 per year (2× per week)",
                "color": "#08306B",
            },
            {
                "value": "weekly",
                "label": "52 per year (weekly)",
                "color": "#4292C6",
            },
            {
                "value": "biweekly",
                "label": "26 per year (every 2 weeks)",
                "color": "#9ECAE1",
            },
            {
                "value": "less_frequent",
                "label": "< 26 per year (every 3–4 weeks)",
                "color": "#FDBF6F",
            },
            {
                "value": "seasonal",
                "label": "Seasonally varying",
                "color": "#e4595b",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection count",
        "fileBase": "residual_collection_count",
        "numericField": "collection_count",
        "quartileColors": ["#FDBF6F", "#9ECAE1", "#4292C6", "#08306B"],
        "quartilePreserveClasses": ["seasonal"],
    },
    "residual_collection_point_count": {
        "title": "Number of residual waste collection points",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-point-count/",
        "dataField": "_classified",
        "transformName": "residualCollectionPointCount",
        "categories": [
            {
                "value": "very_high",
                "label": "≥ 121",
                "color": "#67000d",
            },
            {
                "value": "high",
                "label": "59 – 120",
                "color": "#cb181d",
            },
            {
                "value": "medium",
                "label": "8 – 58",
                "color": "#fc9272",
            },
            {
                "value": "low",
                "label": "1 – 7",
                "color": "#fee0d2",
            },
            {
                "value": "full_dtd",
                "label": "Full door-to-door / no data",
                "color": NO_DATA_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Residual collection points",
        "fileBase": "residual_collection_point_count",
        "numericField": "collection_point_count",
        "quartileColors": ["#fee0d2", "#fc9272", "#cb181d", "#67000d"],
        "quartilePreserveClasses": ["full_dtd"],
    },
    "residual_collection_system": {
        "title": "Residual waste collection system",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-system/",
        "dataField": "collection_system",
        "categories": [
            {
                "value": "Door to door",
                "label": "PAP total",
                "color": "#d0fcd5",
            },
            {
                "value": "Mixed door-to-door and bring point",
                "label": "PAP parcial",
                "color": "#a8e6cf",
            },
            {
                "value": "Bring point",
                "label": "Bring point",
                "color": "#3dc7dc",
            },
            {
                "value": "No separate collection",
                "label": "No separate collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "legendTitle": "Collection system",
        "fileBase": "catalonia_residual_collection_system",
    },
    "residual_fee_system": {
        "title": "Fee system for residual waste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-fee-system/",
        "dataField": "fee_system",
        "categories": [
            {
                "value": "Flat fee",
                "label": "Flat rate",
                "color": "#4daf4a",
            },
            {
                "value": "Flexible",
                "label": "Flexible",
                "color": "#00ced1",
            },
            {
                "value": "Flexible+",
                "label": "Flexible+",
                "color": "#ffd700",
            },
            {
                "value": "Pay as you throw (PAYT)",
                "label": "Pay as you throw",
                "color": "#4b2a60",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Fee system",
        "fileBase": "residual_fee_system",
    },
    "residual_frequency": {
        "title": "Collection frequency setting for residual waste collection",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-frequency-type/",
        "dataField": "frequency_type",
        "categories": [
            {
                "value": "Fixed-Seasonal",
                "label": "Seasonally varying",
                "color": "#2e8b57",
            },
            {
                "value": "Fixed-Flexible",
                "label": "Flexible",
                "color": "#4169e1",
            },
            {
                "value": "Fixed",
                "label": "Fixed",
                "color": "#b0b0ff",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Collection frequency setting",
        "fileBase": "residual_collection_schedule",
    },
    "residual_min_bin_size": {
        "title": "Smallest available bin size for residual waste (L)",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-min-bin-size/",
        "dataField": "_classified",
        "transformName": "residualMinBinSize",
        "categories": [
            {
                "value": "xs",
                "label": "≤ 30",
                "color": "#fde0dd",
            },
            {
                "value": "small",
                "label": "31 – 60",
                "color": "#fc9272",
            },
            {
                "value": "medium",
                "label": "61 – 120",
                "color": "#de2d26",
            },
            {
                "value": "large",
                "label": "121 – 240",
                "color": "#67000d",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Min. bin size (L)",
        "fileBase": "residual_min_bin_size",
        "numericField": "min_bin_size",
        "quartileColors": ["#fde0dd", "#fc9272", "#de2d26", "#67000d"],
    },
    "residual_required_bin_capacity": {
        "title": "Required bin capacity for residual waste (L/reference unit)",
        "dataUrl": "/waste_collection/api/waste-atlas/residual-required-bin-capacity/",
        "dataField": "_classified",
        "transformName": "residualRequiredBinCapacity",
        "categories": [
            {
                "value": "very_low",
                "label": "≤ 10",
                "color": "#fde0dd",
            },
            {
                "value": "low",
                "label": "11 – 20",
                "color": "#fc9272",
            },
            {
                "value": "medium",
                "label": "21 – 40",
                "color": "#de2d26",
            },
            {
                "value": "high",
                "label": "41 – 80",
                "color": "#a50f15",
            },
            {
                "value": "very_high",
                "label": "> 80",
                "color": "#67000d",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Minimum bin capacity (L/unit)",
        "fileBase": "residual_required_bin_capacity",
        "numericField": "required_bin_capacity",
        "quartileColors": ["#fde0dd", "#fc9272", "#a50f15", "#67000d"],
    },
    "system_access_control": {
        "title": "Collection system and access/use control",
        "dataUrl": "/waste_collection/api/waste-atlas/catalonia-system-access-control/",
        "dataField": "access_control",
        "categories": [
            {
                "value": "Bring point + access control",
                "label": "Bring point + access control",
                "exportLabel": "BP + access",
                "color": "#238b45",
            },
            {
                "value": "Bring point + no access control",
                "label": "Bring point + no access control",
                "exportLabel": "BP + no access",
                "color": "#a1d99b",
            },
            {
                "value": "PAP + use control",
                "label": "PAP + use control",
                "color": "#2b8cbe",
            },
            {
                "value": "PAP + no use control",
                "label": "PAP + no use control",
                "color": "#a6bddb",
            },
            {
                "value": "Other combination",
                "label": "Other combination",
                "color": "#bdbdbd",
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "System + access/use control",
        "fileBase": "catalonia_system_access_control",
    },
    "waste_ratio": {
        "title": "Separation rate – Biowaste stream (%)",
        "dataUrl": "/waste_collection/api/waste-atlas/waste-ratio/",
        "dataField": "_classified",
        "transformName": "wasteRatio",
        "categories": [
            {
                "value": "very_high",
                "label": "\u003e 66 (Biowaste-stream dominant)",
                "color": "#0868ac",
            },
            {
                "value": "high",
                "label": "51–66",
                "color": "#43a2ca",
            },
            {
                "value": "low",
                "label": "34–50",
                "color": "#7bccc4",
            },
            {
                "value": "very_low",
                "label": "\u2264 33 (Residual-waste-stream dominant)",
                "color": "#bae4bc",
            },
            {
                "value": "no_bio",
                "label": "No separate biowaste collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Separation rate – Biowaste stream (%)",
        "exportLegendTitle": "Separation rate –\nBiowaste stream (%)",
        "fileBase": "waste_amount_ratio",
        "numericField": "ratio",
        "quartileDisplayMultiplier": 100,
        "quartileColors": ["#bae4bc", "#7bccc4", "#43a2ca", "#0868ac"],
        "quartilePreserveClasses": ["no_bio"],
    },
    "weekly_bp_access_days": {
        "title": "Weekly bring-point access days",
        "dataUrl": "/waste_collection/api/waste-atlas/weekly-bp-access-days/",
        "dataField": "_classified",
        "transformName": "weeklyBpAccessDays",
        "categories": [
            {
                "value": "7",
                "label": "7 days (daily access)",
                "color": "#1a9850",
            },
            {
                "value": "5_6",
                "label": "5–6 days",
                "color": "#66bd63",
            },
            {
                "value": "3_4",
                "label": "3–4 days",
                "color": "#a6d96a",
            },
            {
                "value": "1_2",
                "label": "1–2 days",
                "color": "#d9f0d3",
            },
            {
                "value": "no_bp",
                "label": "No bring-point collection",
                "color": BIOWASTE_NO_COLLECTION_COLOR,
            },
        ],
        "noDataColor": NO_DATA_COLOR,
        "noDataLabel": "No data",
        "legendTitle": "Weekly access days",
        "fileBase": "weekly_bp_access_days",
        "numericField": "weekly_access_days",
        "quartileColors": ["#d9f0d3", "#a6d96a", "#66bd63", "#1a9850"],
        "quartilePreserveClasses": ["no_bp"],
    },
}
