"""Central registry of Waste Atlas choropleth map configurations.

Each entry is a plain dict keyed by ``map_route_key``.  Views only set the
route key; the template tag looks the configuration up here and injects it
into the single generic ``map.html`` template.
"""

MAP_CONFIGS = {
    # ── Administration ──
    "orga_level": {
        "dataUrl": "/waste_collection/api/waste-atlas/orga-level/",
        "dataField": "orga_level",
        "categories": [
            {
                "value": "nuts",
                "label": "Districts and district-free cities",
                "color": "#93d163",
            },
            {"value": "lau", "label": "Municipal level", "color": "#72a0dd"},
            {
                "value": "individual",
                "label": "Other administrative level",
                "color": "#d491f3",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Administrative level",
        "fileBase": "administrative_level",
    },
    # ── Collection systems ──
    "collection_system": {
        "dataUrl": "/waste_collection/api/waste-atlas/collection-system/",
        "dataField": "collection_system",
        "categories": [
            {
                "value": "Door to door",
                "label": "Door to door collection",
                "color": "#d0fcd5",
            },
            {
                "value": "Mixed door-to-door and bring point",
                "label": "Mixed door-to-door and bring point",
                "color": "#a8e6cf",
            },
            {
                "value": "Recycling centre",
                "label": "Recycling centre",
                "color": "#3dc79b",
            },
            {"value": "Bring point", "label": "Bring point", "color": "#3dc7dc"},
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection system",
        "fileBase": "collection_systems",
    },
    "green_waste_collection_system_count": {
        "dataUrl": "/waste_collection/api/waste-atlas/green-waste-collection-system-count/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "3plus",
                "label": "3 or more collection systems",
                "color": "#1b9e77",
            },
            {"value": "2", "label": "2 collection systems", "color": "#66a61e"},
            {"value": "1", "label": "1 collection system", "color": "#a6d854"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Number of collection systems",
        "fileBase": "green_waste_collection_system_count",
        "transformName": "greenWasteCollectionSystemCount",
    },
    # ── Connection rate ──
    "connection_rate": {
        "dataUrl": "/waste_collection/api/waste-atlas/connection-rate/",
        "dataField": "_classified",
        "categories": [
            {"value": "75-100", "label": "100% \u2013 75%", "color": "#00608e"},
            {"value": "50-74", "label": "74% \u2013 50%", "color": "#0090cb"},
            {"value": "25-49", "label": "49% \u2013 25%", "color": "#7fcce9"},
            {"value": "0-24", "label": "24% \u2013 0%", "color": "#d1e7e6"},
            {
                "value": "no_d2d",
                "label": "No door-to-door biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Connection rate",
        "fileBase": "connection_rate",
        "transformName": "connectionRate",
    },
    # ── Frequency types ──
    "residual_frequency": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-frequency-type/",
        "dataField": "frequency_type",
        "categories": [
            {
                "value": "Fixed-Seasonal",
                "label": "Seasonally varying",
                "color": "#2e8b57",
            },
            {"value": "Fixed-Flexible", "label": "Flexible", "color": "#4169e1"},
            {"value": "Fixed", "label": "Fixed", "color": "#b0b0ff"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection frequency setting",
        "fileBase": "residual_collection_schedule",
    },
    "biowaste_frequency": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-frequency-type/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "Fixed-Seasonal",
                "label": "Seasonally varying",
                "color": "#2e8b57",
            },
            {"value": "Fixed-Flexible", "label": "Flexible", "color": "#4169e1"},
            {"value": "Fixed", "label": "Fixed", "color": "#8c9eff"},
            {
                "value": "no_bio_collection",
                "label": "No door-to-door biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection frequency setting",
        "fileBase": "biowaste_collection_schedule",
        "transformName": "biowasteFrequency",
    },
    # ── Collection counts ──
    "residual_collection_count": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-count/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "twice_weekly",
                "label": "104 per year (2\u00d7 per week)",
                "color": "#08306B",
            },
            {"value": "weekly", "label": "52 per year (weekly)", "color": "#4292C6"},
            {
                "value": "biweekly",
                "label": "26 per year (every 2 weeks)",
                "color": "#9ECAE1",
            },
            {
                "value": "less_frequent",
                "label": "< 26 per year (every 3\u20134 weeks)",
                "color": "#FDBF6F",
            },
            {"value": "seasonal", "label": "Seasonally varying", "color": "#e4595b"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection count",
        "fileBase": "residual_collection_count",
        "transformName": "residualCollectionCount",
    },
    "biowaste_collection_count": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-count/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "twice_weekly",
                "label": "104 per year (2\u00d7 per week)",
                "color": "#08306B",
            },
            {"value": "weekly", "label": "52 per year (weekly)", "color": "#4292C6"},
            {
                "value": "biweekly",
                "label": "26 per year (every 2 weeks)",
                "color": "#9ECAE1",
            },
            {
                "value": "less_frequent",
                "label": "< 26 per year (every 3\u20134 weeks)",
                "color": "#FDBF6F",
            },
            {"value": "seasonal", "label": "Seasonally varying", "color": "#e4595b"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection count",
        "fileBase": "biowaste_collection_count",
        "transformName": "biowasteCollectionCount",
    },
    # ── Fee systems ──
    "residual_fee_system": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-fee-system/",
        "dataField": "fee_system",
        "categories": [
            {"value": "Flat fee", "label": "Flat rate", "color": "#4daf4a"},
            {"value": "Flexible", "label": "Flexible", "color": "#00ced1"},
            {"value": "Flexible+", "label": "Flexible+", "color": "#ffd700"},
            {
                "value": "Pay as you throw (PAYT)",
                "label": "Pay as you throw",
                "color": "#4b2a60",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Fee system",
        "fileBase": "residual_fee_system",
    },
    "biowaste_fee_system": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-fee-system/",
        "dataField": "fee_system",
        "categories": [
            {"value": "Flat fee", "label": "Flat rate", "color": "#228B22"},
            {"value": "Flexible", "label": "Flexible", "color": "#00ced1"},
            {"value": "Flexible+", "label": "Flexible+", "color": "#FFD700"},
            {
                "value": "Pay as you throw (PAYT)",
                "label": "Pay as you throw",
                "color": "#4b2a60",
            },
            {"value": "No fee", "label": "No fee", "color": "#e41a1c"},
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": "#FFF696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Fee system",
        "fileBase": "biowaste_fee_system",
    },
    # ── Collection amounts ──
    "biowaste_collection_amount": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-amount/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "very_high",
                "label": "151\u2013236 kg (very high)",
                "color": "#1a9850",
            },
            {"value": "high", "label": "101\u2013150 kg (high)", "color": "#66bd63"},
            {"value": "medium", "label": "51\u2013100 kg (medium)", "color": "#a6d96a"},
            {"value": "low", "label": "0\u201350 kg (low)", "color": "#d9f0d3"},
            {
                "value": "no_bio",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Collected amount (kg/cap/a)",
        "overlayPatternField": "_has_acpv_overlay",
        "overlayPatternLegendLabel": "Hatched = aggregated value (ACPV)",
        "exportOverlayPatternLegendLabel": "Hatched = ACPV",
        "outlineGeoJsonUrl": "/waste_collection/api/waste-atlas/biowaste-collection-amount/acpv-outline-geojson/",
        "outlineStrokeColor": "#ffffff",
        "outlineStrokeOpacity": 0.95,
        "outlineStrokeWidth": 1.35,
        "fileBase": "biowaste_collection_amount",
        "transformName": "biowasteCollectionAmount",
    },
    "residual_collection_amount": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-amount/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_high", "label": "> 350 kg (very high)", "color": "#08306B"},
            {"value": "high", "label": "251\u2013350 kg (high)", "color": "#4292C6"},
            {
                "value": "medium",
                "label": "151\u2013250 kg (medium)",
                "color": "#9ECAE1",
            },
            {"value": "low", "label": "0\u2013150 kg (low)", "color": "#d1e7e6"},
            {
                "value": "no_residual",
                "label": "No separate residual collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Collected amount (kg/cap/a)",
        "overlayPatternField": "_has_acpv_overlay",
        "overlayPatternLegendLabel": "Hatched = aggregated value (ACPV)",
        "exportOverlayPatternLegendLabel": "Hatched = ACPV",
        "outlineGeoJsonUrl": "/waste_collection/api/waste-atlas/residual-collection-amount/acpv-outline-geojson/",
        "outlineStrokeColor": "#ffffff",
        "outlineStrokeOpacity": 0.95,
        "outlineStrokeWidth": 1.35,
        "fileBase": "residual_collection_amount",
        "transformName": "residualCollectionAmount",
    },
    "green_waste_collection_amount": {
        "dataUrl": "/waste_collection/api/waste-atlas/green-waste-collection-amount/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_high", "label": "> 120 kg (very high)", "color": "#1a9850"},
            {"value": "high", "label": "81\u2013120 kg (high)", "color": "#66bd63"},
            {"value": "medium", "label": "41\u201380 kg (medium)", "color": "#a6d96a"},
            {"value": "low", "label": "0\u201340 kg (low)", "color": "#d9f0d3"},
            {
                "value": "no_green",
                "label": "No separate green-waste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Collected amount (kg/cap/a)",
        "overlayPatternField": "_has_acpv_overlay",
        "overlayPatternLegendLabel": "Hatched = aggregated value (ACPV)",
        "exportOverlayPatternLegendLabel": "Hatched = ACPV",
        "outlineGeoJsonUrl": "/waste_collection/api/waste-atlas/green-waste-collection-amount/acpv-outline-geojson/",
        "outlineStrokeColor": "#ffffff",
        "outlineStrokeOpacity": 0.95,
        "outlineStrokeWidth": 1.35,
        "fileBase": "green_waste_collection_amount",
        "transformName": "greenWasteCollectionAmount",
    },
    "organic_collection_amount": {
        "dataUrl": "/waste_collection/api/waste-atlas/organic-collection-amount/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_high", "label": "> 300 kg (very high)", "color": "#1a9850"},
            {"value": "high", "label": "201\u2013300 kg (high)", "color": "#66bd63"},
            {
                "value": "medium",
                "label": "101\u2013200 kg (medium)",
                "color": "#a6d96a",
            },
            {"value": "low", "label": "0\u2013100 kg (low)", "color": "#d9f0d3"},
            {
                "value": "no_organic",
                "label": "No separate organic collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Collected amount (kg/cap/a)",
        "overlayPatternField": "_has_acpv_overlay",
        "overlayPatternLegendLabel": "Hatched = aggregated value (ACPV)",
        "exportOverlayPatternLegendLabel": "Hatched = ACPV",
        "outlineGeoJsonUrl": "/waste_collection/api/waste-atlas/organic-collection-amount/acpv-outline-geojson/",
        "outlineStrokeColor": "#ffffff",
        "outlineStrokeOpacity": 0.95,
        "outlineStrokeWidth": 1.35,
        "fileBase": "organic_collection_amount",
        "transformName": "organicCollectionAmount",
    },
    "waste_ratio": {
        "dataUrl": "/waste_collection/api/waste-atlas/waste-ratio/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "very_high",
                "label": "> 0.66 (much more biowaste than residual waste)",
                "exportLabel": "> 0.66 bio-dominant",
                "color": "#0868ac",
            },
            {
                "value": "high",
                "label": "0.51\u20130.66 (More biowaste than residual waste)",
                "exportLabel": "0.51\u20130.66 bio > residual",
                "color": "#43a2ca",
            },
            {
                "value": "low",
                "label": "0.34\u20130.50 (More residual waste than biowaste)",
                "exportLabel": "0.34\u20130.50 residual > bio",
                "color": "#7bccc4",
            },
            {
                "value": "very_low",
                "label": "0.00\u20130.33 (Low biowaste share)",
                "exportLabel": "0.00\u20130.33 low bio share",
                "color": "#bae4bc",
            },
            {
                "value": "no_bio",
                "label": "No separate biowaste collection",
                "exportLabel": "No separate bio",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Biowaste / (Biowaste + Residual waste)",
        "fileBase": "waste_amount_ratio",
        "transformName": "wasteRatio",
    },
    "organic_waste_ratio": {
        "dataUrl": "/waste_collection/api/waste-atlas/organic-waste-ratio/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "very_high",
                "label": "> 0.66 (much more organic than residual)",
                "exportLabel": "> 0.66 organic-dominant",
                "color": "#0868ac",
            },
            {
                "value": "high",
                "label": "0.51\u20130.66 (More organic than residual)",
                "exportLabel": "0.51\u20130.66 organic > residual",
                "color": "#43a2ca",
            },
            {
                "value": "medium",
                "label": "0.34\u20130.50 (More residual than organic)",
                "exportLabel": "0.34\u20130.50 residual > organic",
                "color": "#7bccc4",
            },
            {
                "value": "low",
                "label": "0.00\u20130.33 (Low organic share)",
                "exportLabel": "0.00\u20130.33 low organic share",
                "color": "#bae4bc",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Organic / (organic + residual)",
        "fileBase": "organic_waste_ratio",
        "transformName": "organicWasteRatio",
    },
    # ── Bins ──
    "biowaste_min_bin_size": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-min-bin-size/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_large", "label": "\u2265 240 L", "color": "#08306B"},
            {"value": "large", "label": "120\u2013239 L", "color": "#4292C6"},
            {"value": "medium", "label": "60\u2013119 L", "color": "#9ECAE1"},
            {"value": "small", "label": "< 60 L", "color": "#d1e7e6"},
            {
                "value": "no_bio",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Smallest available bin size (L)",
        "fileBase": "biowaste_min_bin_size",
        "transformName": "biowasteMinBinSize",
    },
    "residual_min_bin_size": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-min-bin-size/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_large", "label": "\u2265 240 L", "color": "#08306B"},
            {"value": "large", "label": "120\u2013239 L", "color": "#4292C6"},
            {"value": "medium", "label": "60\u2013119 L", "color": "#9ECAE1"},
            {"value": "small", "label": "< 60 L", "color": "#d1e7e6"},
            {
                "value": "no_residual",
                "label": "No separate residual collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Smallest available bin size (L)",
        "fileBase": "residual_min_bin_size",
        "transformName": "residualMinBinSize",
    },
    # ── Collection points ──
    "collection_point_count": {
        "dataUrl": "/waste_collection/api/waste-atlas/collection-point-count/",
        "dataField": "_classified",
        "categories": [
            {"value": "full_d2d", "label": "Full door-to-door", "color": "#1a9850"},
            {"value": "many", "label": "\u2265 10 points", "color": "#66bd63"},
            {"value": "some", "label": "2\u20139 points", "color": "#a6d96a"},
            {"value": "few", "label": "1 point", "color": "#d9f0d3"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Number of collection points",
        "fileBase": "collection_point_count",
        "transformName": "collectionPointCount",
    },
    # ── Population density ──
    "population_density": {
        "dataUrl": "/waste_collection/api/waste-atlas/population/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "urban",
                "label": "Urban (> 1 500 / km\u00b2)",
                "color": "#ffea46",
            },
            {
                "value": "suburban",
                "label": "Suburban (300 \u2013 1 500 / km\u00b2)",
                "color": "#7d7c78",
            },
            {"value": "rural", "label": "Rural (< 300 / km\u00b2)", "color": "#00204d"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Population density",
        "fileBase": "population_density",
        "transformName": "populationDensity",
    },
    # ── Combined maps ──
    "combined_frequency": {
        "dataUrl": "/waste_collection/api/waste-atlas/combined-frequency-type/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "bio_seasonal_res_flexible",
                "label": "Biowaste seasonal, residual flexible",
                "exportLabel": "Seasonal / flexible",
                "color": "#2e8b57",
            },
            {
                "value": "bio_flexible_res_flexible",
                "label": "Biowaste flexible, residual flexible",
                "exportLabel": "Flexible / flexible",
                "color": "#4169e1",
            },
            {
                "value": "bio_fixed_res_flexible",
                "label": "Biowaste fixed, residual flexible",
                "exportLabel": "Fixed / flexible",
                "color": "#9ecae1",
            },
            {
                "value": "bio_seasonal_res_fixed",
                "label": "Biowaste seasonal, residual fixed",
                "exportLabel": "Seasonal / fixed",
                "color": "#66cdaa",
            },
            {
                "value": "bio_flexible_res_fixed",
                "label": "Biowaste flexible, residual fixed",
                "exportLabel": "Flexible / fixed",
                "color": "#e08840",
            },
            {
                "value": "bio_fixed_res_fixed",
                "label": "Biowaste fixed, residual fixed",
                "exportLabel": "Fixed / fixed",
                "color": "#6a51a3",
            },
            {
                "value": "no_bio_collection",
                "label": "No door-to-door biowaste collection",
                "exportLabel": "No D2D bio",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection frequency setting",
        "fileBase": "combined_collection_schedule",
        "transformName": "combinedFrequency",
    },
    "combined_collection_count": {
        "dataUrl": "/waste_collection/api/waste-atlas/combined-collection-count/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "bio_more_res_more",
                "label": "Biowaste more often, residual waste more often",
                "exportLabel": "More / more",
                "color": "#64427b",
            },
            {
                "value": "bio_more_res_bi",
                "label": "Biowaste more often, residual waste every two weeks",
                "exportLabel": "More / 2 weeks",
                "color": "#9c67a5",
            },
            {
                "value": "bio_more_res_less",
                "label": "Biowaste more often, residual waste less frequent",
                "exportLabel": "More / less",
                "color": "#c5a5cf",
            },
            {
                "value": "bio_bi_res_more",
                "label": "Biowaste every two weeks, residual waste more often",
                "exportLabel": "2 weeks / more",
                "color": "#2862a8",
            },
            {
                "value": "bio_bi_res_bi",
                "label": "Biowaste every two weeks, residual waste every two weeks",
                "exportLabel": "2 weeks / 2 weeks",
                "color": "#4292c6",
            },
            {
                "value": "bio_bi_res_less",
                "label": "Biowaste every two weeks, residual waste less frequent",
                "exportLabel": "2 weeks / less",
                "color": "#73b2d8",
            },
            {
                "value": "bio_less_res_more",
                "label": "Biowaste less frequent, residual waste more often",
                "exportLabel": "Less / more",
                "color": "#e33e88",
            },
            {
                "value": "bio_less_res_bi",
                "label": "Biowaste less frequent, residual waste every two weeks",
                "exportLabel": "Less / 2 weeks",
                "color": "#ff7986",
            },
            {
                "value": "bio_less_res_less",
                "label": "Biowaste less frequent, residual waste less frequent",
                "exportLabel": "Less / less",
                "color": "#f7b1b8",
            },
            {
                "value": "no_bio",
                "label": "No door-to-door biowaste collection",
                "exportLabel": "No D2D bio",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection count",
        "exportLegendTitle": "Collection count: bio / residual",
        "fileBase": "combined_collection_count",
        "transformName": "combinedCollectionCount",
    },
    "collection_count_ratio": {
        "dataUrl": "/waste_collection/api/waste-atlas/collection-count-ratio/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "bio_2x",
                "label": "2 : 1 (biowaste collected twice as often)",
                "exportLabel": "2:1 bio > residual",
                "color": "#1b9e77",
            },
            {
                "value": "same",
                "label": "1 : 1 (collected equally often)",
                "exportLabel": "1:1 equal",
                "color": "#7570b3",
            },
            {
                "value": "bio_half",
                "label": "1 : 2 (residual collected twice as often)",
                "exportLabel": "1:2 bio < residual",
                "color": "#d95f02",
            },
            {
                "value": "seasonal",
                "label": "Seasonally varying ratio",
                "exportLabel": "Seasonal",
                "color": "#F4A460",
            },
            {
                "value": "no_bio",
                "label": "No door-to-door biowaste collection",
                "exportLabel": "No D2D bio",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Bio : residual count",
        "fileBase": "collection_count_ratio",
        "transformName": "collectionCountRatio",
    },
    "combined_fee_system": {
        "dataUrl": "/waste_collection/api/waste-atlas/combined-fee-system/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "flex_flex",
                "label": "BWB & RWB: Flexible",
                "exportLabel": "BWB & RWB: Flexible",
                "color": "#00ced1",
            },
            {
                "value": "no_fee_flex",
                "label": "BWB: No fee | RWB: Flexible",
                "exportLabel": "BWB: No fee | RWB: Flexible",
                "color": "#80e6e8",
            },
            {
                "value": "payt_payt",
                "label": "BWB & RWB: PAYT",
                "exportLabel": "BWB & RWB: PAYT",
                "color": "#4b2a60",
            },
            {
                "value": "flex_payt",
                "label": "BWB: Flexible | RWB: PAYT",
                "exportLabel": "BWB: Flexible | RWB: PAYT",
                "color": "#7b5a8c",
            },
            {
                "value": "no_fee_payt",
                "label": "BWB: No fee | RWB: PAYT",
                "exportLabel": "BWB: No fee | RWB: PAYT",
                "color": "#b6a1c5",
            },
            {
                "value": "flex_flex_plus",
                "label": "BWB: Flexible | RWB: Flexible+",
                "exportLabel": "BWB: Flexible | RWB: Flexible+",
                "color": "#ffd700",
            },
            {
                "value": "no_bio",
                "label": "No door-to-door biowaste collection",
                "exportLabel": "No D2D bio",
                "color": "#fff696",
            },
            {
                "value": "other_combined",
                "label": "Other combinations",
                "exportLabel": "Other combinations",
                "color": "#4daf4a",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Fee: bio / residual",
        "exportLegendBottomColumns": 2,
        "fileBase": "combined_fee_system",
        "transformName": "combinedFeeSystem",
    },
    # ── Bin capacity ──
    "biowaste_required_bin_capacity": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-required-bin-capacity/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_low", "label": "\u2264 5 L/unit", "color": "#d9f0d3"},
            {"value": "low", "label": "6 \u2013 10 L/unit", "color": "#a6d96a"},
            {"value": "medium", "label": "11 \u2013 20 L/unit", "color": "#66bd63"},
            {"value": "high", "label": "21 \u2013 60 L/unit", "color": "#1a9850"},
            {"value": "very_high", "label": "> 60 L/unit", "color": "#006837"},
            {
                "value": "no_door_to_door",
                "label": "No door-to-door biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Minimum bin capacity (L/unit)",
        "fileBase": "biowaste_required_bin_capacity",
        "transformName": "biowasteRequiredBinCapacity",
    },
    "residual_required_bin_capacity": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-required-bin-capacity/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_low", "label": "\u2264 10 L/unit", "color": "#fde0dd"},
            {"value": "low", "label": "11 \u2013 20 L/unit", "color": "#fc9272"},
            {"value": "medium", "label": "21 \u2013 40 L/unit", "color": "#de2d26"},
            {"value": "high", "label": "41 \u2013 80 L/unit", "color": "#a50f15"},
            {"value": "very_high", "label": "> 80 L/unit", "color": "#67000d"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Minimum bin capacity (L/unit)",
        "fileBase": "residual_required_bin_capacity",
        "transformName": "residualRequiredBinCapacity",
    },
    # ── Collection points ──
    "biowaste_collection_point_count": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-point-count/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_high", "label": "\u2265 59", "color": "#005a32"},
            {"value": "high", "label": "10 \u2013 58", "color": "#31a354"},
            {"value": "medium", "label": "2 \u2013 9", "color": "#74c476"},
            {
                "value": "very_low",
                "label": "Collection points, but no data",
                "color": "#edf8e9",
            },
            {
                "value": "full_dtd",
                "label": "Full door-to-door / no data",
                "color": "#ffffd4",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Biowaste collection points",
        "fileBase": "biowaste_collection_point_count",
        "transformName": "biowasteCollectionPointCount",
    },
    "residual_collection_point_count": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-point-count/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_high", "label": "\u2265 121", "color": "#67000d"},
            {"value": "high", "label": "59 \u2013 120", "color": "#cb181d"},
            {"value": "medium", "label": "8 \u2013 58", "color": "#fc9272"},
            {"value": "low", "label": "1 \u2013 7", "color": "#fee0d2"},
            {
                "value": "full_dtd",
                "label": "Full door-to-door / no data",
                "color": "#ffffd4",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Residual collection points",
        "fileBase": "residual_collection_point_count",
        "transformName": "residualCollectionPointCount",
    },
    "collection_point_count_ratio": {
        "dataUrl": "/waste_collection/api/waste-atlas/collection-point-count-ratio/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "bio_more",
                "label": "More biowaste than residual points",
                "exportLabel": "Bio > residual",
                "color": "#1b9e77",
            },
            {
                "value": "same",
                "label": "Equal number of points",
                "exportLabel": "Equal",
                "color": "#7570b3",
            },
            {
                "value": "bio_less",
                "label": "Fewer biowaste than residual points",
                "exportLabel": "Bio < residual",
                "color": "#d95f02",
            },
            {
                "value": "no_bio",
                "label": "No biowaste collection-point data",
                "exportLabel": "No bio data",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Bio / residual points",
        "fileBase": "collection_point_count_ratio",
        "transformName": "collectionPointCountRatio",
    },
    "min_bin_size_ratio": {
        "dataUrl": "/waste_collection/api/waste-atlas/min-bin-size-ratio/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "bio_larger",
                "label": "Biowaste bin larger than residual waste bin",
                "exportLabel": "Bio bin larger",
                "color": "#1b9e77",
            },
            {
                "value": "same",
                "label": "Biowaste and residual waste bins equal size",
                "exportLabel": "Equal bin size",
                "color": "#7570b3",
            },
            {
                "value": "bio_smaller",
                "label": "Biowaste bin smaller than residual waste bin",
                "exportLabel": "Bio bin smaller",
                "color": "#d95f02",
            },
            {
                "value": "no_bio",
                "label": "No door-to-door biowaste collection",
                "exportLabel": "No D2D bio",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Biowaste / Residual waste",
        "fileBase": "min_bin_size_ratio",
        "transformName": "minBinSizeRatio",
    },
    # ── Quality & compliance ──
    "biowaste_impurity": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-impurity/",
        "dataField": "_classified",
        "categories": [
            {"value": "very_low", "label": "0\u20135% (very low)", "color": "#1a9850"},
            {"value": "low", "label": "5\u201310% (low)", "color": "#66bd63"},
            {"value": "medium", "label": "10\u201320% (medium)", "color": "#fee08b"},
            {"value": "high", "label": "20\u201340% (high)", "color": "#f46d43"},
            {"value": "very_high", "label": "> 40% (very high)", "color": "#d73027"},
            {
                "value": "no_collection",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Impurity rate (%)",
        "fileBase": "biowaste_impurity",
        "transformName": "biowasteImpurity",
    },
    "weekly_bp_access_days": {
        "dataUrl": "/waste_collection/api/waste-atlas/weekly-bp-access-days/",
        "dataField": "_classified",
        "categories": [
            {"value": "7", "label": "7 days (daily access)", "color": "#1a9850"},
            {"value": "5_6", "label": "5\u20136 days", "color": "#66bd63"},
            {"value": "3_4", "label": "3\u20134 days", "color": "#a6d96a"},
            {"value": "1_2", "label": "1\u20132 days", "color": "#d9f0d3"},
            {
                "value": "no_bp",
                "label": "No bring-point collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Weekly access days",
        "fileBase": "weekly_bp_access_days",
        "transformName": "weeklyBpAccessDays",
    },
    # ── Materials & rules ──
    "food_waste_category": {
        "dataUrl": "/waste_collection/api/waste-atlas/food-waste-category/",
        "dataField": "food_waste_category",
        "categories": [
            {
                "value": "All four materials",
                "label": "All food waste",
                "color": "#2c7da0",
            },
            {
                "value": "No raw meat",
                "label": "No raw animal products",
                "color": "#61a35c",
            },
            {"value": "No meat", "label": "No animal products", "color": "#41b6c4"},
            {
                "value": "Only raw plant-based",
                "label": "Only raw plant-based products",
                "color": "#9ac93e",
            },
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Accepted food waste",
        "fileBase": "food_waste_category",
    },
    "paper_bags": {
        "dataUrl": "/waste_collection/api/waste-atlas/paper-bags/",
        "dataField": "status",
        "categories": [
            {"value": "allowed", "label": "Allowed", "color": "#2196f3"},
            {"value": "forbidden", "label": "Forbidden", "color": "#f57c00"},
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Paper bags",
        "fileBase": "paper_bags",
    },
    "plastic_bags": {
        "dataUrl": "/waste_collection/api/waste-atlas/plastic-bags/",
        "dataField": "status",
        "categories": [
            {"value": "allowed", "label": "Allowed", "color": "#fdd835"},
            {"value": "forbidden", "label": "Forbidden", "color": "#78909c"},
            {
                "value": "No separate collection",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Plastic bags",
        "fileBase": "plastic_bags",
    },
    "collection_support": {
        "dataUrl": "/waste_collection/api/waste-atlas/collection-support/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "paper_a_plastic_a",
                "label": "Paper allowed, compostable plastic bags allowed",
                "color": "#4caf50",
            },
            {
                "value": "paper_f_plastic_a",
                "label": "Paper forbidden, compostable plastic bags allowed",
                "color": "#fdd835",
            },
            {
                "value": "paper_a_plastic_f",
                "label": "Paper allowed, compostable plastic bags forbidden",
                "color": "#2196f3",
            },
            {
                "value": "paper_a_plastic_n",
                "label": "Paper allowed, compostable plastic bags unknown",
                "color": "#90caf9",
            },
            {
                "value": "paper_f_plastic_f",
                "label": "Paper forbidden, compostable plastic bags forbidden",
                "color": "#7e57c2",
            },
            {
                "value": "paper_n_plastic_f",
                "label": "Paper unknown, compostable plastic bags forbidden",
                "color": "#ff7043",
            },
            {
                "value": "no_collection",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#ffffff",
        "noDataLabel": "No data",
        "legendTitle": "Collection aids",
        "fileBase": "collection_aids",
        "transformName": "collectionSupport",
    },
    "access_control": {
        "dataUrl": "/waste_collection/api/waste-atlas/access-control/",
        "dataField": "access_control",
        "categories": [
            {
                "value": "Bring point: yes",
                "label": "Bring point: yes",
                "color": "#1b9e77",
            },
            {
                "value": "Bring point: no",
                "label": "Bring point: no",
                "color": "#a6dba0",
            },
            {
                "value": "Door-to-door: yes",
                "label": "Door-to-door: yes",
                "color": "#2166ac",
            },
            {
                "value": "Door-to-door: no",
                "label": "Door-to-door: no",
                "color": "#92c5de",
            },
            {
                "value": "Bring point: yes | Door-to-door: yes",
                "label": "Bring point: yes | Door-to-door: yes",
                "color": "#542788",
            },
            {
                "value": "Bring point: no | Door-to-door: no",
                "label": "Bring point: no | Door-to-door: no",
                "color": "#c2a5cf",
            },
            {
                "value": "Bring point: yes | Door-to-door: no",
                "label": "Bring point: yes | Door-to-door: no",
                "color": "#b2182b",
            },
            {
                "value": "Bring point: no | Door-to-door: yes",
                "label": "Bring point: no | Door-to-door: yes",
                "color": "#ef8a62",
            },
            {
                "value": "No separate biowaste collection",
                "label": "No separate biowaste collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Access control",
        "fileBase": "access_control",
    },
    "system_access_control": {
        "dataUrl": "/waste_collection/api/waste-atlas/catalonia-system-access-control/",
        "dataField": "access_control",
        "categories": [
            {
                "value": "Bring point + access control",
                "label": "Bring point + access control",
                "exportLabel": "BP + access",
                "color": "#238b45",
            },
            {
                "value": "Bring point + no access control",
                "label": "Bring point + no access control",
                "exportLabel": "BP + no access",
                "color": "#a1d99b",
            },
            {
                "value": "PAP + use control",
                "label": "PAP + use control",
                "color": "#2b8cbe",
            },
            {
                "value": "PAP + no use control",
                "label": "PAP + no use control",
                "color": "#a6bddb",
            },
            {
                "value": "Other combination",
                "label": "Other combination",
                "color": "#bdbdbd",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "System + access/use control",
        "fileBase": "catalonia_system_access_control",
    },
    # ── Bin configuration ──
    "bin_configuration": {
        "dataUrl": "/waste_collection/api/waste-atlas/bin-configuration/",
        "dataField": "bin_configuration",
        "categories": [
            {"value": "Separate bins", "label": "Separate bins", "color": "#4dbf8b"},
            {
                "value": "Optical bag sorting",
                "label": "Optical bag sorting",
                "color": "#66a3ff",
            },
            {
                "value": "Four compartments bin",
                "label": "Four compartments bin",
                "exportLabel": "4-compartment bin",
                "color": "#f2a541",
            },
            {
                "value": "Two compartments bin",
                "label": "Two compartments bin",
                "exportLabel": "2-compartment bin",
                "color": "#9c89d9",
            },
            {
                "value": "No separate collection",
                "label": "No separate collection",
                "color": "#f7d154",
            },
            {"value": "no_data", "label": "No data reported", "color": "#d0d0d0"},
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Bin configuration",
        "fileBase": "map34_bin_configuration_sweden",
    },
    # ── Catalonia-specific collection systems ──
    "biowaste_collection_system": {
        "dataUrl": "/waste_collection/api/waste-atlas/biowaste-collection-system/",
        "dataField": "collection_system",
        "categories": [
            {"value": "Door to door", "label": "PAP total", "color": "#d0fcd5"},
            {
                "value": "Mixed door-to-door and bring point",
                "label": "PAP parcial",
                "color": "#a8e6cf",
            },
            {"value": "Bring point", "label": "Bring point", "color": "#3dc7dc"},
            {
                "value": "No separate collection",
                "label": "No separate collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection system",
        "fileBase": "catalonia_biowaste_collection_system",
    },
    "residual_collection_system": {
        "dataUrl": "/waste_collection/api/waste-atlas/residual-collection-system/",
        "dataField": "collection_system",
        "categories": [
            {"value": "Door to door", "label": "PAP total", "color": "#d0fcd5"},
            {
                "value": "Mixed door-to-door and bring point",
                "label": "PAP parcial",
                "color": "#a8e6cf",
            },
            {"value": "Bring point", "label": "Bring point", "color": "#3dc7dc"},
            {
                "value": "No separate collection",
                "label": "No separate collection",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection system",
        "fileBase": "catalonia_residual_collection_system",
    },
    "combined_collection_system": {
        "dataUrl": "/waste_collection/api/waste-atlas/combined-collection-system/",
        "dataField": "_classified",
        "categories": [
            {
                "value": "Door to door / Door to door",
                "label": "PAP total / PAP total",
                "exportLabel": "PAP total / PAP total",
                "color": "#238b45",
            },
            {
                "value": "Door to door / Bring point",
                "label": "PAP total / Bring point",
                "exportLabel": "PAP total / BP",
                "color": "#74c476",
            },
            {
                "value": "Door to door / No separate collection",
                "label": "PAP total / no residual",
                "exportLabel": "PAP total / none",
                "color": "#bae4b3",
            },
            {
                "value": "Mixed door-to-door and bring point / Door to door",
                "label": "PAP parcial / PAP total",
                "exportLabel": "PAP parcial / PAP total",
                "color": "#2b8cbe",
            },
            {
                "value": "Mixed door-to-door and bring point / Bring point",
                "label": "PAP parcial / Bring point",
                "exportLabel": "PAP parcial / BP",
                "color": "#7bccc4",
            },
            {
                "value": "Mixed door-to-door and bring point / No separate collection",
                "label": "PAP parcial / no residual",
                "exportLabel": "PAP parcial / none",
                "color": "#bae4bc",
            },
            {
                "value": "Bring point / Door to door",
                "label": "Bring point / PAP total",
                "exportLabel": "BP / PAP total",
                "color": "#756bb1",
            },
            {
                "value": "Bring point / Bring point",
                "label": "Bring point / Bring point",
                "exportLabel": "BP / BP",
                "color": "#9e9ac8",
            },
            {
                "value": "Bring point / No separate collection",
                "label": "Bring point / no residual",
                "exportLabel": "BP / none",
                "color": "#cbc9e2",
            },
            {
                "value": "No separate collection / Door to door",
                "label": "No biowaste / PAP total",
                "exportLabel": "None / PAP total",
                "color": "#fd8d3c",
            },
            {
                "value": "No separate collection / Bring point",
                "label": "No biowaste / Bring point",
                "exportLabel": "None / BP",
                "color": "#fdae6b",
            },
            {
                "value": "No separate collection / No separate collection",
                "label": "No separate collection",
                "exportLabel": "None / none",
                "color": "#fff696",
            },
        ],
        "noDataColor": "#e0e0e0",
        "noDataLabel": "No data",
        "legendTitle": "Collection system: bio / residual",
        "fileBase": "catalonia_combined_collection_system",
        "transformName": "combinedCollectionSystem",
    },
}
