"""Declarative registry of all Waste Atlas map pages.

This module is the single source of truth for every choropleth map page:
URL path, route name, region scope (map set), selector theme, page title,
and the JS map configuration key (see ``map_configs.py``).

``views.py`` and ``urls.py`` generate the actual views/urlpatterns from
``MAP_PAGES``; ``map_selection.py`` derives the region/theme selector from it.
"""

# Region scope shared by all pages of a map set.
# ``selector_set`` is the map-set key shown in the region selector
# (None = page is not listed in the selector, e.g. legacy generic routes).
# ``lock`` = ignore ``country``/``nuts_*`` query-string overrides.
REGIONS = {
    "generic": {"selector_set": None, "country": "DE", "year": "2024", "lock": False},
    "germany": {
        "selector_set": "DE",
        "country": "DE",
        "year": "2024",
        "nuts_level": "1",
        "lock": True,
    },
    "bw_rp": {
        "selector_set": "DE-BW-RP",
        "country": "DE",
        "year": "2024",
        "nuts_prefix": "DE1,DEB",
        "nuts_level": "1",
        "lock": True,
    },
    "nrw": {
        "selector_set": "DE-NW",
        "country": "DE",
        "year": "2024",
        "nuts_prefix": "DEA",
        "nuts_level": "1",
        "lock": True,
    },
    "italy": {"selector_set": "IT", "country": "IT", "year": "2024", "lock": True},
    "south_tyrol": {
        "selector_set": "IT-ST",
        "country": "IT",
        "year": "2024",
        "nuts_prefix": "ITH10",
        "nuts_level": "3",
        "lock": True,
    },
    "catalonia": {
        "selector_set": "ES-CT",
        "country": "ES",
        "year": "2024",
        "nuts_prefix": "ES51",
        "nuts_level": "3",
        "lock": True,
    },
    "denmark": {"selector_set": "DK", "country": "DK", "year": "2024", "lock": True},
    "sweden": {"selector_set": "SE", "country": "SE", "year": "2024", "lock": False},
    "netherlands": {
        "selector_set": "NL",
        "country": "NL",
        "year": "2024",
        "lock": False,
    },
    "belgium": {"selector_set": "BE", "country": "BE", "year": "2024", "lock": False},
    "belgium_flanders": {
        "selector_set": "BE-FL-BR",
        "country": "BE",
        "year": "2024",
        "nuts_prefix": "BE1,BE2",
        "lock": False,
    },
}

MAP_SET_COUNTRIES = {
    cfg["selector_set"]: cfg["country"]
    for cfg in REGIONS.values()
    if cfg["selector_set"] is not None
}

MAP_SET_LABELS = {
    "BE": "Belgium",
    "BE-FL-BR": "Flanders + Brussels",
    "DE": "Germany",
    "DE-BW-RP": "Baden-Württemberg & Rheinland-Pfalz",
    "DE-NW": "Nordrhein-Westfalen",
    "DK": "Denmark",
    "ES-CT": "Catalonia",
    "IT": "Italy",
    "IT-ST": "South Tyrol",
    "NL": "The Netherlands",
    "SE": "Sweden",
}


def _page(region, theme, title, path, name, **extra):
    """Build one page entry from region defaults plus page-specific values."""
    page = {
        "region": region,
        "theme": theme,
        "title": title,
        "path": path,
        "name": name,
        "config_key": theme,
        **REGIONS[region],
    }
    page.update(extra)
    return page


MAP_PAGES = [
    # ── generic ──
    _page(
        "generic",
        "orga_level",
        "Administrative level of collectors",
        "map/administrative-level/",
        "waste-atlas-orga-level-map",
    ),
    _page(
        "generic",
        "collection_orga_level",
        "Administrative level of collections",
        "map/administrative-level/collections/",
        "waste-atlas-collection-orga-level-map",
    ),
    # ── italy ──
    _page(
        "italy",
        "orga_level",
        "Administrative level of collectors",
        "map/italy/administrative-level/",
        "waste-atlas-orga-level-italy-map",
        config_key="orga_level_eu",
        overrides={"fileBase": "map29_orga_level_italy"},
    ),
    _page(
        "italy",
        "collection_orga_level",
        "Administrative level of collections",
        "map/italy/administrative-level/collections/",
        "waste-atlas-collection-orga-level-italy-map",
        config_key="collection_orga_level_eu",
        overrides={"fileBase": "map29_collection_orga_level_italy"},
    ),
    _page(
        "italy",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/italy/collection-system/",
        "waste-atlas-italy-collection-system-map",
    ),
    _page(
        "italy",
        "green_waste_collection_system_count",
        "Number of green-waste collection systems per catchment",
        "map/italy/green-waste-collection-system-count/",
        "waste-atlas-italy-green-waste-collection-system-count-map",
    ),
    _page(
        "italy",
        "collection_point_count",
        "Number of collection points",
        "map/italy/collection-point-count/",
        "waste-atlas-italy-collection-point-count-map",
    ),
    _page(
        "italy",
        "residual_frequency",
        "Collection frequency types for residual waste collection",
        "map/italy/residual-frequency/",
        "waste-atlas-italy-residual-frequency-map",
    ),
    _page(
        "italy",
        "biowaste_frequency",
        "Collection frequency types for biowaste collection",
        "map/italy/biowaste-frequency/",
        "waste-atlas-italy-biowaste-frequency-map",
    ),
    _page(
        "italy",
        "residual_collection_count",
        "Annual residual waste collection count",
        "map/italy/residual-collection-count/",
        "waste-atlas-italy-residual-collection-count-map",
    ),
    _page(
        "italy",
        "biowaste_collection_count",
        "Annual biowaste collection count",
        "map/italy/biowaste-collection-count/",
        "waste-atlas-italy-biowaste-collection-count-map",
    ),
    _page(
        "italy",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/italy/residual-collection-amount/",
        "waste-atlas-italy-residual-collection-amount-map",
    ),
    _page(
        "italy",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/italy/biowaste-collection-amount/",
        "waste-atlas-italy-biowaste-collection-amount-map",
    ),
    _page(
        "italy",
        "green_waste_collection_amount",
        "Specifically collected amount of green waste",
        "map/italy/green-waste-collection-amount/",
        "waste-atlas-italy-green-waste-collection-amount-map",
    ),
    _page(
        "italy",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/italy/organic-collection-amount/",
        "waste-atlas-italy-organic-collection-amount-map",
    ),
    _page(
        "italy",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/italy/organic-waste-ratio/",
        "waste-atlas-italy-organic-waste-ratio-map",
    ),
    # ── south_tyrol ──
    _page(
        "south_tyrol",
        "orga_level",
        "Administrative level of collectors",
        "map/south-tyrol/administrative-level/",
        "waste-atlas-south-tyrol-orga-level-map",
        config_key="orga_level_eu",
        overrides={"fileBase": "map29_orga_level_italy"},
    ),
    _page(
        "south_tyrol",
        "collection_orga_level",
        "Administrative level of collections",
        "map/south-tyrol/administrative-level/collections/",
        "waste-atlas-south-tyrol-collection-orga-level-map",
        config_key="collection_orga_level_eu",
        overrides={"fileBase": "map29_collection_orga_level_italy"},
    ),
    _page(
        "south_tyrol",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/south-tyrol/collection-system/",
        "waste-atlas-south-tyrol-collection-system-map",
    ),
    _page(
        "south_tyrol",
        "green_waste_collection_system_count",
        "Number of green-waste collection systems per catchment",
        "map/south-tyrol/green-waste-collection-system-count/",
        "waste-atlas-south-tyrol-green-waste-collection-system-count-map",
    ),
    _page(
        "south_tyrol",
        "collection_count_ratio",
        "Annual collection-count ratio: biowaste vs residual waste",
        "map/south-tyrol/collection-count-ratio/",
        "waste-atlas-south-tyrol-collection-count-ratio-map",
    ),
    _page(
        "south_tyrol",
        "collection_point_count",
        "Number of collection points",
        "map/south-tyrol/collection-point-count/",
        "waste-atlas-south-tyrol-collection-point-count-map",
    ),
    _page(
        "south_tyrol",
        "biowaste_collection_point_count",
        "Number of biowaste collection points",
        "map/south-tyrol/biowaste-collection-point-count/",
        "waste-atlas-south-tyrol-biowaste-collection-point-count-map",
    ),
    _page(
        "south_tyrol",
        "residual_collection_point_count",
        "Number of residual waste collection points",
        "map/south-tyrol/residual-collection-point-count/",
        "waste-atlas-south-tyrol-residual-collection-point-count-map",
    ),
    _page(
        "south_tyrol",
        "collection_point_count_ratio",
        "Collection points: biowaste vs residual waste",
        "map/south-tyrol/collection-point-count-ratio/",
        "waste-atlas-south-tyrol-collection-point-count-ratio-map",
    ),
    _page(
        "south_tyrol",
        "residual_frequency",
        "Collection frequency setting for residual waste collection",
        "map/south-tyrol/residual-frequency/",
        "waste-atlas-south-tyrol-residual-frequency-map",
    ),
    _page(
        "south_tyrol",
        "biowaste_frequency",
        "Collection frequency setting for biowaste collection",
        "map/south-tyrol/biowaste-frequency/",
        "waste-atlas-south-tyrol-biowaste-frequency-map",
    ),
    _page(
        "south_tyrol",
        "residual_collection_count",
        "Annual residual waste collection count",
        "map/south-tyrol/residual-collection-count/",
        "waste-atlas-south-tyrol-residual-collection-count-map",
    ),
    _page(
        "south_tyrol",
        "biowaste_collection_count",
        "Annual biowaste collection count",
        "map/south-tyrol/biowaste-collection-count/",
        "waste-atlas-south-tyrol-biowaste-collection-count-map",
    ),
    _page(
        "south_tyrol",
        "combined_frequency",
        "Collection frequency setting: biowaste vs residual waste",
        "map/south-tyrol/combined-frequency/",
        "waste-atlas-south-tyrol-combined-frequency-map",
    ),
    _page(
        "south_tyrol",
        "combined_collection_count",
        "Annual collection count: biowaste vs residual waste",
        "map/south-tyrol/combined-collection-count/",
        "waste-atlas-south-tyrol-combined-collection-count-map",
    ),
    _page(
        "south_tyrol",
        "residual_fee_system",
        "Fee system for residual waste collection",
        "map/south-tyrol/residual-fee-system/",
        "waste-atlas-south-tyrol-residual-fee-system-map",
    ),
    _page(
        "south_tyrol",
        "biowaste_fee_system",
        "Fee system for biowaste collection",
        "map/south-tyrol/biowaste-fee-system/",
        "waste-atlas-south-tyrol-biowaste-fee-system-map",
    ),
    _page(
        "south_tyrol",
        "combined_fee_system",
        "Fee system: biowaste vs residual waste",
        "map/south-tyrol/combined-fee-system/",
        "waste-atlas-south-tyrol-combined-fee-system-map",
    ),
    _page(
        "south_tyrol",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/south-tyrol/residual-collection-amount/",
        "waste-atlas-south-tyrol-residual-collection-amount-map",
    ),
    _page(
        "south_tyrol",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/south-tyrol/biowaste-collection-amount/",
        "waste-atlas-south-tyrol-biowaste-collection-amount-map",
    ),
    _page(
        "south_tyrol",
        "green_waste_collection_amount",
        "Specifically collected amount of green waste",
        "map/south-tyrol/green-waste-collection-amount/",
        "waste-atlas-south-tyrol-green-waste-collection-amount-map",
    ),
    _page(
        "south_tyrol",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/south-tyrol/organic-collection-amount/",
        "waste-atlas-south-tyrol-organic-collection-amount-map",
    ),
    _page(
        "south_tyrol",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/south-tyrol/organic-waste-ratio/",
        "waste-atlas-south-tyrol-organic-waste-ratio-map",
    ),
    _page(
        "south_tyrol",
        "biowaste_min_bin_size",
        "Smallest available bin size for biowaste (L)",
        "map/south-tyrol/biowaste-min-bin-size/",
        "waste-atlas-south-tyrol-biowaste-min-bin-size-map",
    ),
    _page(
        "south_tyrol",
        "residual_min_bin_size",
        "Smallest available bin size for residual waste (L)",
        "map/south-tyrol/residual-min-bin-size/",
        "waste-atlas-south-tyrol-residual-min-bin-size-map",
    ),
    _page(
        "south_tyrol",
        "min_bin_size_ratio",
        "Minimum bin size ratio: biowaste vs residual waste",
        "map/south-tyrol/min-bin-size-ratio/",
        "waste-atlas-south-tyrol-min-bin-size-ratio-map",
    ),
    # ── sweden ──
    _page(
        "sweden",
        "orga_level",
        "Administrative level of collectors",
        "map/sweden/administrative-level/",
        "waste-atlas-orga-level-sweden-map",
        config_key="orga_level_eu",
        overrides={"fileBase": "map30_orga_level_sweden"},
    ),
    _page(
        "sweden",
        "collection_orga_level",
        "Administrative level of collections",
        "map/sweden/administrative-level/collections/",
        "waste-atlas-collection-orga-level-sweden-map",
        config_key="collection_orga_level_eu",
        overrides={"fileBase": "map30_collection_orga_level_sweden"},
    ),
    _page(
        "sweden",
        "population_density",
        "Population density",
        "map/sweden/population-density/",
        "waste-atlas-sweden-population-density-map",
    ),
    _page(
        "sweden",
        "bin_configuration",
        "Bin configuration of waste fractions",
        "map/bin-configuration-sweden/",
        "waste-atlas-bin-configuration-sweden-map",
    ),
    _page(
        "sweden",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/sweden/collection-system/",
        "waste-atlas-sweden-collection-system-map",
        overrides={"fileBase": "sweden_collection_system"},
    ),
    _page(
        "sweden",
        "connection_rate",
        "Connection rates for door-to-door biowaste collection",
        "map/sweden/connection-rate/",
        "waste-atlas-sweden-connection-rate-map",
        overrides={"fileBase": "sweden_connection_rate"},
    ),
    _page(
        "sweden",
        "paper_bags",
        "Use of paper bags for biowaste collection",
        "map/sweden/paper-bags/",
        "waste-atlas-sweden-paper-bags-map",
        overrides={"fileBase": "sweden_paper_bags"},
    ),
    _page(
        "sweden",
        "plastic_bags",
        "Use of compostable plastic bags for biowaste collection",
        "map/sweden/plastic-bags/",
        "waste-atlas-sweden-plastic-bags-map",
        overrides={"fileBase": "sweden_plastic_bags"},
    ),
    _page(
        "sweden",
        "collection_support",
        "Accepted materials for collection aids",
        "map/sweden/collection-support/",
        "waste-atlas-sweden-collection-support-map",
        overrides={"fileBase": "sweden_collection_support"},
    ),
    _page(
        "sweden",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/sweden/residual-collection-amount/",
        "waste-atlas-sweden-residual-collection-amount-map",
        overrides={"fileBase": "sweden_residual_collection_amount"},
    ),
    _page(
        "sweden",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/sweden/biowaste-collection-amount/",
        "waste-atlas-sweden-biowaste-collection-amount-map",
        overrides={"fileBase": "sweden_biowaste_collection_amount"},
    ),
    _page(
        "sweden",
        "waste_ratio",
        "Biobin stream separation rate (%)",
        "map/sweden/waste-ratio/",
        "waste-atlas-sweden-waste-ratio-map",
        overrides={"fileBase": "sweden_waste_ratio"},
    ),
    _page(
        "sweden",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/sweden/organic-collection-amount/",
        "waste-atlas-sweden-organic-collection-amount-map",
        overrides={"fileBase": "sweden_organic_collection_amount"},
    ),
    _page(
        "sweden",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/sweden/organic-waste-ratio/",
        "waste-atlas-sweden-organic-waste-ratio-map",
        overrides={"fileBase": "sweden_organic_waste_ratio"},
    ),
    # ── denmark ──
    _page(
        "denmark",
        "orga_level",
        "Administrative level of collectors",
        "map/denmark/administrative-level/",
        "waste-atlas-orga-level-denmark-map",
        config_key="orga_level_eu",
        overrides={"fileBase": "map31_orga_level_denmark"},
        lock=False,
    ),
    _page(
        "denmark",
        "collection_orga_level",
        "Administrative level of collections",
        "map/denmark/administrative-level/collections/",
        "waste-atlas-collection-orga-level-denmark-map",
        config_key="collection_orga_level_eu",
        overrides={"fileBase": "map31_collection_orga_level_denmark"},
        lock=False,
    ),
    _page(
        "denmark",
        "food_waste_category",
        "Accepted food-waste categories in biowaste",
        "map/denmark/food-waste-category/",
        "waste-atlas-denmark-food-waste-category-map",
        config_key="denmark_food_waste_category",
    ),
    _page(
        "denmark",
        "paper_bags",
        "Use of paper bags for biowaste collection",
        "map/denmark/paper-bags/",
        "waste-atlas-denmark-paper-bags-map",
        config_key="denmark_paper_bags",
    ),
    _page(
        "denmark",
        "plastic_bags",
        "Use of plastic bags for biowaste collection",
        "map/denmark/plastic-bags/",
        "waste-atlas-denmark-plastic-bags-map",
        config_key="denmark_plastic_bags",
    ),
    _page(
        "denmark",
        "collection_support",
        "Accepted materials for collection aids",
        "map/denmark/collection-support/",
        "waste-atlas-denmark-collection-support-map",
        config_key="denmark_collection_support",
    ),
    # ── netherlands ──
    _page(
        "netherlands",
        "orga_level",
        "Administrative level of collectors",
        "map/netherlands/administrative-level/",
        "waste-atlas-orga-level-netherlands-map",
        config_key="orga_level_eu",
        overrides={"fileBase": "map32_orga_level_netherlands"},
    ),
    _page(
        "netherlands",
        "collection_orga_level",
        "Administrative level of collections",
        "map/netherlands/administrative-level/collections/",
        "waste-atlas-collection-orga-level-netherlands-map",
        config_key="collection_orga_level_eu",
        overrides={"fileBase": "map32_collection_orga_level_netherlands"},
    ),
    _page(
        "netherlands",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/collection-system-netherlands/",
        "waste-atlas-collection-system-netherlands-map",
    ),
    _page(
        "netherlands",
        "biowaste_frequency",
        "Collection frequency types for biowaste",
        "map/biowaste-frequency-netherlands/",
        "waste-atlas-biowaste-frequency-netherlands-map",
    ),
    _page(
        "netherlands",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste per person and year",
        "map/biowaste-collection-amount-netherlands/",
        "waste-atlas-biowaste-collection-amount-netherlands-map",
    ),
    _page(
        "netherlands",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/p/a)",
        "map/organic-collection-amount-netherlands/",
        "waste-atlas-organic-collection-amount-netherlands-map",
    ),
    _page(
        "netherlands",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/organic-waste-ratio-netherlands/",
        "waste-atlas-organic-waste-ratio-netherlands-map",
    ),
    # ── belgium ──
    _page(
        "belgium",
        "orga_level",
        "Administrative level of collectors",
        "map/belgium/administrative-level/",
        "waste-atlas-orga-level-belgium-map",
        config_key="orga_level_eu",
        overrides={"fileBase": "map33_orga_level_belgium"},
    ),
    _page(
        "belgium",
        "collection_orga_level",
        "Administrative level of collections",
        "map/belgium/administrative-level/collections/",
        "waste-atlas-collection-orga-level-belgium-map",
        config_key="collection_orga_level_eu",
        overrides={"fileBase": "map33_collection_orga_level_belgium"},
    ),
    # ── belgium_flanders ──
    _page(
        "belgium_flanders",
        "orga_level",
        "Administrative level of collectors",
        "map/belgium-flanders/administrative-level/",
        "waste-atlas-orga-level-belgium-flanders-map",
        config_key="orga_level_eu",
        overrides={"fileBase": "map35_orga_level_belgium_flanders"},
    ),
    _page(
        "belgium_flanders",
        "collection_orga_level",
        "Administrative level of collections",
        "map/belgium-flanders/administrative-level/collections/",
        "waste-atlas-collection-orga-level-belgium-flanders-map",
        config_key="collection_orga_level_eu",
        overrides={"fileBase": "map35_collection_orga_level_belgium_flanders"},
    ),
    # ── generic ──
    _page(
        "generic",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/collection-system/",
        "waste-atlas-collection-system-map",
    ),
    _page(
        "generic",
        "green_waste_collection_system_count",
        "Number of green-waste collection systems per catchment",
        "map/green-waste-collection-system-count/",
        "waste-atlas-green-waste-collection-system-count-map",
    ),
    _page(
        "generic",
        "connection_rate",
        "Connection rates for door-to-door biowaste collection",
        "map/connection-rate/",
        "waste-atlas-connection-rate-map",
    ),
    _page(
        "generic",
        "participation_policy",
        "Participation Policy",
        "map/participation-policy/",
        "waste-atlas-participation-policy-map",
    ),
    _page(
        "generic",
        "food_waste_category",
        "Accepted food-waste categories in biowaste",
        "map/food-waste-category/",
        "waste-atlas-food-waste-category-map",
    ),
    _page(
        "generic",
        "paper_bags",
        "Use of paper bags for biowaste collection",
        "map/paper-bags/",
        "waste-atlas-paper-bags-map",
    ),
    _page(
        "generic",
        "plastic_bags",
        "Use of compostable plastic bags for biowaste collection",
        "map/plastic-bags/",
        "waste-atlas-plastic-bags-map",
    ),
    _page(
        "generic",
        "collection_support",
        "Accepted materials for collection aids",
        "map/collection-support/",
        "waste-atlas-collection-support-map",
    ),
    _page(
        "generic",
        "residual_frequency",
        "Collection frequency types for residual waste collection",
        "map/residual-frequency/",
        "waste-atlas-residual-frequency-map",
    ),
    _page(
        "generic",
        "biowaste_frequency",
        "Collection frequency types for biowaste collection",
        "map/biowaste-frequency/",
        "waste-atlas-biowaste-frequency-map",
    ),
    _page(
        "generic",
        "combined_frequency",
        "Collection frequency type: biowaste vs residual waste",
        "map/combined-frequency/",
        "waste-atlas-combined-frequency-map",
    ),
    _page(
        "generic",
        "residual_collection_count",
        "Annual residual waste collection count",
        "map/residual-collection-count/",
        "waste-atlas-residual-collection-count-map",
    ),
    _page(
        "generic",
        "biowaste_collection_count",
        "Annual biowaste collection count",
        "map/biowaste-collection-count/",
        "waste-atlas-biowaste-collection-count-map",
    ),
    _page(
        "generic",
        "combined_collection_count",
        "Annual collection count: biowaste vs residual waste",
        "map/combined-collection-count/",
        "waste-atlas-combined-collection-count-map",
    ),
    _page(
        "generic",
        "collection_count_ratio",
        "Annual collection-count ratio: biowaste vs residual waste",
        "map/collection-count-ratio/",
        "waste-atlas-collection-count-ratio-map",
    ),
    _page(
        "generic",
        "residual_fee_system",
        "Fee system for residual waste collection",
        "map/residual-fee-system/",
        "waste-atlas-residual-fee-system-map",
    ),
    _page(
        "generic",
        "biowaste_fee_system",
        "Fee system for biowaste collection",
        "map/biowaste-fee-system/",
        "waste-atlas-biowaste-fee-system-map",
    ),
    _page(
        "generic",
        "combined_fee_system",
        "Fee system: biowaste vs residual waste",
        "map/combined-fee-system/",
        "waste-atlas-combined-fee-system-map",
    ),
    _page(
        "generic",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/residual-collection-amount/",
        "waste-atlas-residual-collection-amount-map",
    ),
    _page(
        "generic",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/biowaste-collection-amount/",
        "waste-atlas-biowaste-collection-amount-map",
    ),
    _page(
        "generic",
        "green_waste_collection_amount",
        "Specifically collected amount of green waste",
        "map/green-waste-collection-amount/",
        "waste-atlas-green-waste-collection-amount-map",
    ),
    _page(
        "generic",
        "waste_ratio",
        "Biobin stream separation rate (%)",
        "map/waste-ratio/",
        "waste-atlas-waste-ratio-map",
    ),
    _page(
        "generic",
        "population_density",
        "Population density",
        "map/population-density/",
        "waste-atlas-population-density-map",
    ),
    _page(
        "generic",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/organic-collection-amount/",
        "waste-atlas-organic-collection-amount-map",
    ),
    _page(
        "generic",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/organic-waste-ratio/",
        "waste-atlas-organic-waste-ratio-map",
    ),
    _page(
        "generic",
        "biowaste_min_bin_size",
        "Smallest available bin size for biowaste (L)",
        "map/biowaste-min-bin-size/",
        "waste-atlas-biowaste-min-bin-size-map",
    ),
    _page(
        "generic",
        "residual_min_bin_size",
        "Smallest available bin size for residual waste (L)",
        "map/residual-min-bin-size/",
        "waste-atlas-residual-min-bin-size-map",
    ),
    _page(
        "generic",
        "biowaste_required_bin_capacity",
        "Required bin capacity for biowaste (L/reference unit)",
        "map/biowaste-required-bin-capacity/",
        "waste-atlas-biowaste-required-bin-capacity-map",
    ),
    _page(
        "generic",
        "residual_required_bin_capacity",
        "Required bin capacity for residual waste (L/reference unit)",
        "map/residual-required-bin-capacity/",
        "waste-atlas-residual-required-bin-capacity-map",
    ),
    # ── germany ──
    _page(
        "germany",
        "orga_level",
        "Administrative level of collectors",
        "map/germany/administrative-level/",
        "waste-atlas-germany-orga-level-map",
    ),
    _page(
        "germany",
        "collection_orga_level",
        "Administrative level of collections",
        "map/germany/administrative-level/collections/",
        "waste-atlas-germany-collection-orga-level-map",
    ),
    _page(
        "germany",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/germany/collection-system/",
        "waste-atlas-germany-collection-system-map",
    ),
    _page(
        "germany",
        "connection_rate",
        "Connection rates for door-to-door biowaste collection",
        "map/germany/connection-rate/",
        "waste-atlas-germany-connection-rate-map",
    ),
    _page(
        "germany",
        "participation_policy",
        "Participation Policy",
        "map/germany/participation-policy/",
        "waste-atlas-germany-participation-policy-map",
    ),
    _page(
        "germany",
        "food_waste_category",
        "Accepted food-waste categories in biowaste",
        "map/germany/food-waste-category/",
        "waste-atlas-germany-food-waste-category-map",
    ),
    _page(
        "germany",
        "paper_bags",
        "Use of paper bags for biowaste collection",
        "map/germany/paper-bags/",
        "waste-atlas-germany-paper-bags-map",
    ),
    _page(
        "germany",
        "plastic_bags",
        "Use of compostable plastic bags for biowaste collection",
        "map/germany/plastic-bags/",
        "waste-atlas-germany-plastic-bags-map",
    ),
    _page(
        "germany",
        "collection_support",
        "Accepted materials for collection aids",
        "map/germany/collection-support/",
        "waste-atlas-germany-collection-support-map",
    ),
    _page(
        "germany",
        "green_waste_collection_system_count",
        "Number of green-waste collection systems per catchment",
        "map/germany/green-waste-collection-system-count/",
        "waste-atlas-germany-green-waste-collection-system-count-map",
    ),
    _page(
        "germany",
        "collection_point_count",
        "Number of collection points",
        "map/germany/collection-point-count/",
        "waste-atlas-germany-collection-point-count-map",
    ),
    _page(
        "germany",
        "biowaste_min_bin_size",
        "Smallest available bin size for biowaste (L)",
        "map/germany/biowaste-min-bin-size/",
        "waste-atlas-germany-biowaste-min-bin-size-map",
    ),
    _page(
        "germany",
        "residual_min_bin_size",
        "Smallest available bin size for residual waste (L)",
        "map/germany/residual-min-bin-size/",
        "waste-atlas-germany-residual-min-bin-size-map",
    ),
    _page(
        "germany",
        "biowaste_required_bin_capacity",
        "Required bin capacity for biowaste (L/reference unit)",
        "map/germany/biowaste-required-bin-capacity/",
        "waste-atlas-germany-biowaste-required-bin-capacity-map",
    ),
    _page(
        "germany",
        "residual_required_bin_capacity",
        "Required bin capacity for residual waste (L/reference unit)",
        "map/germany/residual-required-bin-capacity/",
        "waste-atlas-germany-residual-required-bin-capacity-map",
    ),
    _page(
        "germany",
        "residual_frequency",
        "Collection frequency types for residual waste collection",
        "map/germany/residual-frequency/",
        "waste-atlas-germany-residual-frequency-map",
    ),
    _page(
        "germany",
        "biowaste_frequency",
        "Collection frequency types for biowaste collection",
        "map/germany/biowaste-frequency/",
        "waste-atlas-germany-biowaste-frequency-map",
    ),
    _page(
        "germany",
        "combined_frequency",
        "Collection frequency type: biowaste vs residual waste",
        "map/germany/combined-frequency/",
        "waste-atlas-germany-combined-frequency-map",
    ),
    _page(
        "germany",
        "residual_collection_count",
        "Annual residual waste collection count",
        "map/germany/residual-collection-count/",
        "waste-atlas-germany-residual-collection-count-map",
    ),
    _page(
        "germany",
        "biowaste_collection_count",
        "Annual biowaste collection count",
        "map/germany/biowaste-collection-count/",
        "waste-atlas-germany-biowaste-collection-count-map",
    ),
    _page(
        "germany",
        "combined_collection_count",
        "Annual collection count: biowaste vs residual waste",
        "map/germany/combined-collection-count/",
        "waste-atlas-germany-combined-collection-count-map",
    ),
    _page(
        "germany",
        "collection_count_ratio",
        "Annual collection-count ratio: biowaste vs residual waste",
        "map/germany/collection-count-ratio/",
        "waste-atlas-germany-collection-count-ratio-map",
    ),
    _page(
        "germany",
        "residual_fee_system",
        "Fee system for residual waste collection",
        "map/germany/residual-fee-system/",
        "waste-atlas-germany-residual-fee-system-map",
    ),
    _page(
        "germany",
        "biowaste_fee_system",
        "Fee system for biowaste collection",
        "map/germany/biowaste-fee-system/",
        "waste-atlas-germany-biowaste-fee-system-map",
    ),
    _page(
        "germany",
        "combined_fee_system",
        "Fee system: biowaste vs residual waste",
        "map/germany/combined-fee-system/",
        "waste-atlas-germany-combined-fee-system-map",
    ),
    _page(
        "germany",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/germany/residual-collection-amount/",
        "waste-atlas-germany-residual-collection-amount-map",
    ),
    _page(
        "germany",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/germany/biowaste-collection-amount/",
        "waste-atlas-germany-biowaste-collection-amount-map",
    ),
    _page(
        "germany",
        "waste_ratio",
        "Biobin stream separation rate (%)",
        "map/germany/waste-ratio/",
        "waste-atlas-germany-waste-ratio-map",
    ),
    _page(
        "germany",
        "population_density",
        "Population density",
        "map/germany/population-density/",
        "waste-atlas-germany-population-density-map",
    ),
    _page(
        "germany",
        "green_waste_collection_amount",
        "Specifically collected amount of green waste",
        "map/germany/green-waste-collection-amount/",
        "waste-atlas-germany-green-waste-collection-amount-map",
    ),
    _page(
        "germany",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/germany/organic-collection-amount/",
        "waste-atlas-germany-organic-collection-amount-map",
    ),
    _page(
        "germany",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/germany/organic-waste-ratio/",
        "waste-atlas-germany-organic-waste-ratio-map",
    ),
    # ── nrw ──
    _page(
        "nrw",
        "orga_level",
        "Administrative level of collectors",
        "map/nrw/administrative-level/",
        "waste-atlas-nrw-orga-level-map",
    ),
    _page(
        "nrw",
        "collection_orga_level",
        "Administrative level of collections",
        "map/nrw/administrative-level/collections/",
        "waste-atlas-nrw-collection-orga-level-map",
    ),
    _page(
        "nrw",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/nrw/collection-system/",
        "waste-atlas-nrw-collection-system-map",
    ),
    _page(
        "nrw",
        "connection_rate",
        "Connection rates for door-to-door biowaste collection",
        "map/nrw/connection-rate/",
        "waste-atlas-nrw-connection-rate-map",
    ),
    _page(
        "nrw",
        "participation_policy",
        "Participation Policy",
        "map/nrw/participation-policy/",
        "waste-atlas-nrw-participation-policy-map",
    ),
    _page(
        "nrw",
        "food_waste_category",
        "Accepted food-waste categories in biowaste",
        "map/nrw/food-waste-category/",
        "waste-atlas-nrw-food-waste-category-map",
    ),
    _page(
        "nrw",
        "paper_bags",
        "Use of paper bags for biowaste collection",
        "map/nrw/paper-bags/",
        "waste-atlas-nrw-paper-bags-map",
    ),
    _page(
        "nrw",
        "plastic_bags",
        "Use of compostable plastic bags for biowaste collection",
        "map/nrw/plastic-bags/",
        "waste-atlas-nrw-plastic-bags-map",
    ),
    _page(
        "nrw",
        "collection_support",
        "Accepted materials for collection aids",
        "map/nrw/collection-support/",
        "waste-atlas-nrw-collection-support-map",
    ),
    _page(
        "nrw",
        "green_waste_collection_system_count",
        "Number of green-waste collection systems per catchment",
        "map/nrw/green-waste-collection-system-count/",
        "waste-atlas-nrw-green-waste-collection-system-count-map",
    ),
    _page(
        "nrw",
        "collection_point_count",
        "Number of collection points",
        "map/nrw/collection-point-count/",
        "waste-atlas-nrw-collection-point-count-map",
    ),
    _page(
        "nrw",
        "biowaste_min_bin_size",
        "Smallest available bin size for biowaste (L)",
        "map/nrw/biowaste-min-bin-size/",
        "waste-atlas-nrw-biowaste-min-bin-size-map",
    ),
    _page(
        "nrw",
        "residual_min_bin_size",
        "Smallest available bin size for residual waste (L)",
        "map/nrw/residual-min-bin-size/",
        "waste-atlas-nrw-residual-min-bin-size-map",
    ),
    _page(
        "nrw",
        "biowaste_required_bin_capacity",
        "Required bin capacity for biowaste (L/reference unit)",
        "map/nrw/biowaste-required-bin-capacity/",
        "waste-atlas-nrw-biowaste-required-bin-capacity-map",
    ),
    _page(
        "nrw",
        "residual_required_bin_capacity",
        "Required bin capacity for residual waste (L/reference unit)",
        "map/nrw/residual-required-bin-capacity/",
        "waste-atlas-nrw-residual-required-bin-capacity-map",
    ),
    _page(
        "nrw",
        "residual_frequency",
        "Collection frequency types for residual waste collection",
        "map/nrw/residual-frequency/",
        "waste-atlas-nrw-residual-frequency-map",
    ),
    _page(
        "nrw",
        "biowaste_frequency",
        "Collection frequency types for biowaste collection",
        "map/nrw/biowaste-frequency/",
        "waste-atlas-nrw-biowaste-frequency-map",
    ),
    _page(
        "nrw",
        "combined_frequency",
        "Collection frequency type: biowaste vs residual waste",
        "map/nrw/combined-frequency/",
        "waste-atlas-nrw-combined-frequency-map",
    ),
    _page(
        "nrw",
        "residual_collection_count",
        "Annual residual waste collection count",
        "map/nrw/residual-collection-count/",
        "waste-atlas-nrw-residual-collection-count-map",
    ),
    _page(
        "nrw",
        "biowaste_collection_count",
        "Annual biowaste collection count",
        "map/nrw/biowaste-collection-count/",
        "waste-atlas-nrw-biowaste-collection-count-map",
    ),
    _page(
        "nrw",
        "combined_collection_count",
        "Annual collection count: biowaste vs residual waste",
        "map/nrw/combined-collection-count/",
        "waste-atlas-nrw-combined-collection-count-map",
    ),
    _page(
        "nrw",
        "collection_count_ratio",
        "Annual collection-count ratio: biowaste vs residual waste",
        "map/nrw/collection-count-ratio/",
        "waste-atlas-nrw-collection-count-ratio-map",
    ),
    _page(
        "nrw",
        "residual_fee_system",
        "Fee system for residual waste collection",
        "map/nrw/residual-fee-system/",
        "waste-atlas-nrw-residual-fee-system-map",
    ),
    _page(
        "nrw",
        "biowaste_fee_system",
        "Fee system for biowaste collection",
        "map/nrw/biowaste-fee-system/",
        "waste-atlas-nrw-biowaste-fee-system-map",
    ),
    _page(
        "nrw",
        "combined_fee_system",
        "Fee system: biowaste vs residual waste",
        "map/nrw/combined-fee-system/",
        "waste-atlas-nrw-combined-fee-system-map",
    ),
    _page(
        "nrw",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/nrw/residual-collection-amount/",
        "waste-atlas-nrw-residual-collection-amount-map",
    ),
    _page(
        "nrw",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/nrw/biowaste-collection-amount/",
        "waste-atlas-nrw-biowaste-collection-amount-map",
    ),
    _page(
        "nrw",
        "waste_ratio",
        "Biobin stream separation rate (%)",
        "map/nrw/waste-ratio/",
        "waste-atlas-nrw-waste-ratio-map",
    ),
    _page(
        "nrw",
        "population_density",
        "Population density",
        "map/nrw/population-density/",
        "waste-atlas-nrw-population-density-map",
    ),
    _page(
        "nrw",
        "green_waste_collection_amount",
        "Specifically collected amount of green waste",
        "map/nrw/green-waste-collection-amount/",
        "waste-atlas-nrw-green-waste-collection-amount-map",
    ),
    _page(
        "nrw",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/nrw/organic-collection-amount/",
        "waste-atlas-nrw-organic-collection-amount-map",
    ),
    _page(
        "nrw",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/nrw/organic-waste-ratio/",
        "waste-atlas-nrw-organic-waste-ratio-map",
    ),
    # ── catalonia ──
    _page(
        "catalonia",
        "orga_level",
        "Administrative level of collectors",
        "map/catalonia/administrative-level/",
        "waste-atlas-catalonia-orga-level-map",
    ),
    _page(
        "catalonia",
        "collection_orga_level",
        "Administrative level of collections",
        "map/catalonia/administrative-level/collections/",
        "waste-atlas-catalonia-collection-orga-level-map",
    ),
    _page(
        "catalonia",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/catalonia/collection-system/",
        "waste-atlas-catalonia-collection-system-map",
    ),
    _page(
        "catalonia",
        "biowaste_collection_system",
        "Biowaste collection system",
        "map/catalonia/biowaste-collection-system/",
        "waste-atlas-catalonia-biowaste-collection-system-map",
    ),
    _page(
        "catalonia",
        "residual_collection_system",
        "Residual waste collection system",
        "map/catalonia/residual-collection-system/",
        "waste-atlas-catalonia-residual-collection-system-map",
    ),
    _page(
        "catalonia",
        "combined_collection_system",
        "Collection system combination: biowaste vs residual waste",
        "map/catalonia/combined-collection-system/",
        "waste-atlas-catalonia-combined-collection-system-map",
    ),
    _page(
        "catalonia",
        "system_access_control",
        "Collection system and access/use control",
        "map/catalonia/system-access-control/",
        "waste-atlas-catalonia-system-access-control-map",
    ),
    _page(
        "catalonia",
        "access_control",
        "Access control for biowaste collection",
        "map/catalonia/access-control/",
        "waste-atlas-catalonia-access-control-map",
    ),
    _page(
        "catalonia",
        "connection_rate",
        "Connection rates for door-to-door biowaste collection",
        "map/catalonia/connection-rate/",
        "waste-atlas-catalonia-connection-rate-map",
    ),
    _page(
        "catalonia",
        "participation_policy",
        "Participation Policy",
        "map/catalonia/participation-policy/",
        "waste-atlas-catalonia-participation-policy-map",
    ),
    _page(
        "catalonia",
        "food_waste_category",
        "Accepted food-waste categories in biowaste",
        "map/catalonia/food-waste-category/",
        "waste-atlas-catalonia-food-waste-category-map",
    ),
    _page(
        "catalonia",
        "paper_bags",
        "Use of paper bags for biowaste collection",
        "map/catalonia/paper-bags/",
        "waste-atlas-catalonia-paper-bags-map",
    ),
    _page(
        "catalonia",
        "plastic_bags",
        "Use of compostable plastic bags for biowaste collection",
        "map/catalonia/plastic-bags/",
        "waste-atlas-catalonia-plastic-bags-map",
    ),
    _page(
        "catalonia",
        "collection_support",
        "Accepted materials for collection aids",
        "map/catalonia/collection-support/",
        "waste-atlas-catalonia-collection-support-map",
    ),
    _page(
        "catalonia",
        "green_waste_collection_system_count",
        "Number of green-waste collection systems per catchment",
        "map/catalonia/green-waste-collection-system-count/",
        "waste-atlas-catalonia-green-waste-collection-system-count-map",
    ),
    _page(
        "catalonia",
        "collection_point_count",
        "Number of collection points",
        "map/catalonia/collection-point-count/",
        "waste-atlas-catalonia-collection-point-count-map",
    ),
    _page(
        "catalonia",
        "biowaste_min_bin_size",
        "Smallest available bin size for biowaste (L)",
        "map/catalonia/biowaste-min-bin-size/",
        "waste-atlas-catalonia-biowaste-min-bin-size-map",
    ),
    _page(
        "catalonia",
        "residual_min_bin_size",
        "Smallest available bin size for residual waste (L)",
        "map/catalonia/residual-min-bin-size/",
        "waste-atlas-catalonia-residual-min-bin-size-map",
    ),
    _page(
        "catalonia",
        "biowaste_required_bin_capacity",
        "Required bin capacity for biowaste (L/reference unit)",
        "map/catalonia/biowaste-required-bin-capacity/",
        "waste-atlas-catalonia-biowaste-required-bin-capacity-map",
    ),
    _page(
        "catalonia",
        "residual_required_bin_capacity",
        "Required bin capacity for residual waste (L/reference unit)",
        "map/catalonia/residual-required-bin-capacity/",
        "waste-atlas-catalonia-residual-required-bin-capacity-map",
    ),
    _page(
        "catalonia",
        "residual_frequency",
        "Collection frequency types for residual waste collection",
        "map/catalonia/residual-frequency/",
        "waste-atlas-catalonia-residual-frequency-map",
    ),
    _page(
        "catalonia",
        "biowaste_frequency",
        "Collection frequency types for biowaste collection",
        "map/catalonia/biowaste-frequency/",
        "waste-atlas-catalonia-biowaste-frequency-map",
    ),
    _page(
        "catalonia",
        "combined_frequency",
        "Collection frequency type: biowaste vs residual waste",
        "map/catalonia/combined-frequency/",
        "waste-atlas-catalonia-combined-frequency-map",
    ),
    _page(
        "catalonia",
        "residual_collection_count",
        "Annual residual waste collection count",
        "map/catalonia/residual-collection-count/",
        "waste-atlas-catalonia-residual-collection-count-map",
    ),
    _page(
        "catalonia",
        "biowaste_collection_count",
        "Annual biowaste collection count",
        "map/catalonia/biowaste-collection-count/",
        "waste-atlas-catalonia-biowaste-collection-count-map",
    ),
    _page(
        "catalonia",
        "combined_collection_count",
        "Annual collection count: biowaste vs residual waste",
        "map/catalonia/combined-collection-count/",
        "waste-atlas-catalonia-combined-collection-count-map",
    ),
    _page(
        "catalonia",
        "collection_count_ratio",
        "Annual collection-count ratio: biowaste vs residual waste",
        "map/catalonia/collection-count-ratio/",
        "waste-atlas-catalonia-collection-count-ratio-map",
    ),
    _page(
        "catalonia",
        "residual_fee_system",
        "Fee system for residual waste collection",
        "map/catalonia/residual-fee-system/",
        "waste-atlas-catalonia-residual-fee-system-map",
    ),
    _page(
        "catalonia",
        "biowaste_fee_system",
        "Fee system for biowaste collection",
        "map/catalonia/biowaste-fee-system/",
        "waste-atlas-catalonia-biowaste-fee-system-map",
    ),
    _page(
        "catalonia",
        "combined_fee_system",
        "Fee system: biowaste vs residual waste",
        "map/catalonia/combined-fee-system/",
        "waste-atlas-catalonia-combined-fee-system-map",
    ),
    _page(
        "catalonia",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/catalonia/residual-collection-amount/",
        "waste-atlas-catalonia-residual-collection-amount-map",
    ),
    _page(
        "catalonia",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/catalonia/biowaste-collection-amount/",
        "waste-atlas-catalonia-biowaste-collection-amount-map",
    ),
    _page(
        "catalonia",
        "waste_ratio",
        "Biobin stream separation rate (%)",
        "map/catalonia/waste-ratio/",
        "waste-atlas-catalonia-waste-ratio-map",
    ),
    _page(
        "catalonia",
        "population_density",
        "Population density",
        "map/catalonia/population-density/",
        "waste-atlas-catalonia-population-density-map",
    ),
    _page(
        "catalonia",
        "green_waste_collection_amount",
        "Specifically collected amount of green waste",
        "map/catalonia/green-waste-collection-amount/",
        "waste-atlas-catalonia-green-waste-collection-amount-map",
    ),
    _page(
        "catalonia",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/catalonia/organic-collection-amount/",
        "waste-atlas-catalonia-organic-collection-amount-map",
    ),
    _page(
        "catalonia",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/catalonia/organic-waste-ratio/",
        "waste-atlas-catalonia-organic-waste-ratio-map",
    ),
    _page(
        "catalonia",
        "biowaste_impurity",
        "Biowaste impurity rate",
        "map/catalonia/biowaste-impurity/",
        "waste-atlas-catalonia-biowaste-impurity-map",
    ),
    _page(
        "catalonia",
        "weekly_bp_access_days",
        "Weekly bring-point access days",
        "map/catalonia/weekly-bp-access-days/",
        "waste-atlas-catalonia-weekly-bp-access-days-map",
    ),
    # ── bw_rp ──
    _page(
        "bw_rp",
        "orga_level",
        "Administrative level of collectors",
        "map/bw-rp/administrative-level/",
        "waste-atlas-bw-rp-orga-level-map",
    ),
    _page(
        "bw_rp",
        "collection_orga_level",
        "Administrative level of collections",
        "map/bw-rp/administrative-level/collections/",
        "waste-atlas-bw-rp-collection-orga-level-map",
    ),
    _page(
        "bw_rp",
        "collection_system",
        "Primary collection system for kitchen waste",
        "map/bw-rp/collection-system/",
        "waste-atlas-bw-rp-collection-system-map",
    ),
    _page(
        "bw_rp",
        "connection_rate",
        "Connection rates for door-to-door biowaste collection",
        "map/bw-rp/connection-rate/",
        "waste-atlas-bw-rp-connection-rate-map",
    ),
    _page(
        "bw_rp",
        "participation_policy",
        "Participation Policy",
        "map/bw-rp/participation-policy/",
        "waste-atlas-bw-rp-participation-policy-map",
    ),
    _page(
        "bw_rp",
        "food_waste_category",
        "Accepted food-waste categories in biowaste",
        "map/bw-rp/food-waste-category/",
        "waste-atlas-bw-rp-food-waste-category-map",
    ),
    _page(
        "bw_rp",
        "paper_bags",
        "Use of paper bags for biowaste collection",
        "map/bw-rp/paper-bags/",
        "waste-atlas-bw-rp-paper-bags-map",
    ),
    _page(
        "bw_rp",
        "plastic_bags",
        "Use of compostable plastic bags for biowaste collection",
        "map/bw-rp/plastic-bags/",
        "waste-atlas-bw-rp-plastic-bags-map",
    ),
    _page(
        "bw_rp",
        "collection_support",
        "Accepted materials for collection aids",
        "map/bw-rp/collection-support/",
        "waste-atlas-bw-rp-collection-support-map",
    ),
    _page(
        "bw_rp",
        "green_waste_collection_system_count",
        "Number of green-waste collection systems per catchment",
        "map/bw-rp/green-waste-collection-system-count/",
        "waste-atlas-bw-rp-green-waste-collection-system-count-map",
    ),
    _page(
        "bw_rp",
        "biowaste_min_bin_size",
        "Smallest available bin size for biowaste (L)",
        "map/bw-rp/biowaste-min-bin-size/",
        "waste-atlas-bw-rp-biowaste-min-bin-size-map",
    ),
    _page(
        "bw_rp",
        "residual_min_bin_size",
        "Smallest available bin size for residual waste (L)",
        "map/bw-rp/residual-min-bin-size/",
        "waste-atlas-bw-rp-residual-min-bin-size-map",
    ),
    _page(
        "bw_rp",
        "biowaste_required_bin_capacity",
        "Required bin capacity for biowaste (L/reference unit)",
        "map/bw-rp/biowaste-required-bin-capacity/",
        "waste-atlas-bw-rp-biowaste-required-bin-capacity-map",
    ),
    _page(
        "bw_rp",
        "residual_required_bin_capacity",
        "Required bin capacity for residual waste (L/reference unit)",
        "map/bw-rp/residual-required-bin-capacity/",
        "waste-atlas-bw-rp-residual-required-bin-capacity-map",
    ),
    _page(
        "bw_rp",
        "residual_frequency",
        "Collection frequency types for residual waste collection",
        "map/bw-rp/residual-frequency/",
        "waste-atlas-bw-rp-residual-frequency-map",
    ),
    _page(
        "bw_rp",
        "biowaste_frequency",
        "Collection frequency types for biowaste collection",
        "map/bw-rp/biowaste-frequency/",
        "waste-atlas-bw-rp-biowaste-frequency-map",
    ),
    _page(
        "bw_rp",
        "combined_frequency",
        "Collection frequency type: biowaste vs residual waste",
        "map/bw-rp/combined-frequency/",
        "waste-atlas-bw-rp-combined-frequency-map",
    ),
    _page(
        "bw_rp",
        "residual_collection_count",
        "Annual residual waste collection count",
        "map/bw-rp/residual-collection-count/",
        "waste-atlas-bw-rp-residual-collection-count-map",
    ),
    _page(
        "bw_rp",
        "biowaste_collection_count",
        "Annual biowaste collection count",
        "map/bw-rp/biowaste-collection-count/",
        "waste-atlas-bw-rp-biowaste-collection-count-map",
    ),
    _page(
        "bw_rp",
        "combined_collection_count",
        "Annual collection count: biowaste vs residual waste",
        "map/bw-rp/combined-collection-count/",
        "waste-atlas-bw-rp-combined-collection-count-map",
    ),
    _page(
        "bw_rp",
        "collection_count_ratio",
        "Annual collection-count ratio: biowaste vs residual waste",
        "map/bw-rp/collection-count-ratio/",
        "waste-atlas-bw-rp-collection-count-ratio-map",
    ),
    _page(
        "bw_rp",
        "residual_fee_system",
        "Fee system for residual waste collection",
        "map/bw-rp/residual-fee-system/",
        "waste-atlas-bw-rp-residual-fee-system-map",
    ),
    _page(
        "bw_rp",
        "biowaste_fee_system",
        "Fee system for biowaste collection",
        "map/bw-rp/biowaste-fee-system/",
        "waste-atlas-bw-rp-biowaste-fee-system-map",
    ),
    _page(
        "bw_rp",
        "combined_fee_system",
        "Fee system: biowaste vs residual waste",
        "map/bw-rp/combined-fee-system/",
        "waste-atlas-bw-rp-combined-fee-system-map",
    ),
    _page(
        "bw_rp",
        "residual_collection_amount",
        "Specifically collected amount of residual waste",
        "map/bw-rp/residual-collection-amount/",
        "waste-atlas-bw-rp-residual-collection-amount-map",
    ),
    _page(
        "bw_rp",
        "biowaste_collection_amount",
        "Specifically collected amount of biowaste",
        "map/bw-rp/biowaste-collection-amount/",
        "waste-atlas-bw-rp-biowaste-collection-amount-map",
    ),
    _page(
        "bw_rp",
        "waste_ratio",
        "Biobin stream separation rate (%)",
        "map/bw-rp/waste-ratio/",
        "waste-atlas-bw-rp-waste-ratio-map",
    ),
    _page(
        "bw_rp",
        "population_density",
        "Population density",
        "map/bw-rp/population-density/",
        "waste-atlas-bw-rp-population-density-map",
    ),
    _page(
        "bw_rp",
        "green_waste_collection_amount",
        "Specifically collected amount of green waste",
        "map/bw-rp/green-waste-collection-amount/",
        "waste-atlas-bw-rp-green-waste-collection-amount-map",
    ),
    _page(
        "bw_rp",
        "organic_collection_amount",
        "Aggregated collected amount of organic fractions (kg/cap/a)",
        "map/bw-rp/organic-collection-amount/",
        "waste-atlas-bw-rp-organic-collection-amount-map",
    ),
    _page(
        "bw_rp",
        "organic_waste_ratio",
        "Organic stream separation rate (%)",
        "map/bw-rp/organic-waste-ratio/",
        "waste-atlas-bw-rp-organic-waste-ratio-map",
    ),
]
