# Generated by Django 3.2.10 on 2022-03-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributions', '0001_initial'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('geom_type', models.CharField(max_length=20)),
                ('table_name', models.CharField(max_length=200)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryalgorithm')),
            ],
        ),
        migrations.CreateModel(
            name='LayerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=63)),
                ('data_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LayerAggregatedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer_manager.layer')),
            ],
        ),
        migrations.CreateModel(
            name='LayerAggregatedDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('seasonal', 'seasonal')], max_length=255, null=True)),
                ('distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributions.temporaldistribution')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.layer')),
            ],
        ),
    ]
