# Generated by Django 3.0.7 on 2021-02-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenario_builder', '0001_initial'),
        ('materials', '0001_initial'),
        ('flexibi_dst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('geom_type', models.CharField(max_length=20)),
                ('table_name', models.CharField(max_length=200)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.InventoryAlgorithm')),
                ('feedstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialSettings')),
            ],
        ),
        migrations.CreateModel(
            name='LayerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=63)),
                ('data_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LayerAggregatedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer_manager.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='LayerAggregatedDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('seasonal', 'seasonal')], max_length=255, null=True)),
                ('distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexibi_dst.TemporalDistribution')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.Layer')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='layer_fields',
            field=models.ManyToManyField(to='layer_manager.LayerField'),
        ),
        migrations.AddField(
            model_name='layer',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Scenario'),
        ),
        migrations.CreateModel(
            name='DistributionShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distribution_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer_manager.DistributionSet')),
                ('timestep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibi_dst.Timestep')),
            ],
        ),
        migrations.AddField(
            model_name='distributionset',
            name='aggregated_distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.LayerAggregatedDistribution'),
        ),
        migrations.AddField(
            model_name='distributionset',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialComponent'),
        ),
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('table_name',), name='unique table_name'),
        ),
    ]
