# Generated by Django 6.0.8 on 2026-09-22 16:41

import importlib

import django.db.models.deletion
from django.db import migrations, models

inventory_input_migration = importlib.import_module(
    "inventories.migrations.0008_inventoryinput_and_more"
)


_retarget_fk = inventory_input_migration._retarget_fk


def retarget_feedstock_fk_to_inventoryinput(apps, schema_editor):
    _retarget_fk(
        schema_editor,
        "layer_manager_layer",
        "feedstock_id",
        "inventories_inventoryinput",
        "layer_feedstock_inventoryinput_fk",
    )


def retarget_feedstock_fk_to_sampleseries(apps, schema_editor):
    _retarget_fk(
        schema_editor,
        "layer_manager_layer",
        "feedstock_id",
        "materials_sampleseries",
        "layer_feedstock_sampleseries_fk",
        rewrite=inventory_input_migration.map_feedstock_to_series,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0008_inventoryinput_and_more"),
        ("layer_manager", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="layer",
                    name="feedstock",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventories.inventoryinput",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    retarget_feedstock_fk_to_inventoryinput,
                    retarget_feedstock_fk_to_sampleseries,
                ),
            ],
        ),
    ]
