# Generated by Django 3.0.7 on 2021-03-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('flexibi_dst', '0001_initial'),
        ('materials', '0002_auto_20210218_1640'),
        ('layer_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionset',
            name='component',
        ),
        migrations.RemoveField(
            model_name='distributionshare',
            name='timestep',
        ),
        migrations.AddField(
            model_name='distributionset',
            name='timestep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flexibi_dst.Timestep'),
        ),
        migrations.AddField(
            model_name='distributionshare',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='materials.MaterialComponent'),
        ),
    ]
