# Generated by Django 6.0.8 on 2026-09-22 16:41

import django.db.models.deletion
from django.db import migrations, models


def _retarget_fk(schema_editor, table, column, target_table, constraint_name):
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT kcu.constraint_name
            FROM information_schema.key_column_usage kcu
            JOIN information_schema.table_constraints tc
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
             AND tc.table_name = kcu.table_name
            WHERE kcu.table_schema = current_schema()
              AND kcu.table_name = %s
              AND kcu.column_name = %s
              AND tc.constraint_type = 'FOREIGN KEY'
            """,
            [table, column],
        )
        constraint_names = [row[0] for row in cursor.fetchall()]
        for existing_name in constraint_names:
            cursor.execute(
                f"ALTER TABLE {quote(table)} DROP CONSTRAINT {quote(existing_name)}"
            )
        cursor.execute(
            f"ALTER TABLE {quote(table)} "
            f"ADD CONSTRAINT {quote(constraint_name)} "
            f"FOREIGN KEY ({quote(column)}) REFERENCES {quote(target_table)} ({quote('id')}) "
            "DEFERRABLE INITIALLY DEFERRED"
        )


def retarget_feedstock_fk_to_inventoryinput(apps, schema_editor):
    _retarget_fk(
        schema_editor,
        "layer_manager_layer",
        "feedstock_id",
        "inventories_inventoryinput",
        "layer_feedstock_inventoryinput_fk",
    )


def retarget_feedstock_fk_to_sampleseries(apps, schema_editor):
    _retarget_fk(
        schema_editor,
        "layer_manager_layer",
        "feedstock_id",
        "materials_sampleseries",
        "layer_feedstock_sampleseries_fk",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0008_inventoryinput_and_more"),
        ("layer_manager", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="layer",
                    name="feedstock",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventories.inventoryinput",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    retarget_feedstock_fk_to_inventoryinput,
                    retarget_feedstock_fk_to_sampleseries,
                ),
            ],
        ),
    ]
