# Generated by Django 3.0.7 on 2021-02-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('material_manager', '0001_initial'),
        ('layer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='feedstock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_manager.Material'),
        ),
    ]
