# Generated by Django 6.0.8 on 2026-09-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0002_merge_duplicate_layer_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="layerfield",
            constraint=models.UniqueConstraint(
                fields=("field_name", "data_type"),
                name="unique_layer_field_name_data_type",
            ),
        ),
    ]
