# Generated by Django 3.0.3 on 2020-05-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('layer_manager', '0002_auto_20200519_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfield',
            name='layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.Layer'),
            preserve_default=False,
        ),
    ]
