# Generated by Django 6.0.8 on 2026-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0002_unique_layer_field_name_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="staged",
            field=models.BooleanField(default=False),
        ),
    ]
