# Generated by Django 3.0.7 on 2020-11-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('layer_manager', '0002_layeraggregateddistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeraggregateddistribution',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='layer_manager.Layer'),
        ),
    ]
