# Generated by Django 3.0.3 on 2020-05-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0001_initial'),
        ('layer_manager', '0003_layerfield_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.InventoryAlgorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='scenario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.Scenario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='table_name',
            field=models.CharField(default='table', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
