# Generated by Django 3.0.3 on 2020-05-20 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('layer_manager', '0004_auto_20200520_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='version',
        ),
    ]
