# Generated by Django 3.0.3 on 2020-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('layer_manager', '0005_remove_layer_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='layer',
            constraint=models.UniqueConstraint(fields=('table_name',), name='unique table_name'),
        ),
    ]
