# Generated by Django 3.0.3 on 2020-05-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('layer_manager', '0006_auto_20200520_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerfield',
            name='layer',
        ),
        migrations.AddField(
            model_name='layer',
            name='fields',
            field=models.ManyToManyField(to='layer_manager.LayerField'),
        ),
    ]
