# Generated by Django 3.0.3 on 2020-05-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('layer_manager', '0008_auto_20200520_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerAggregatedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('value', models.FloatField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer_manager.Layer')),
            ],
        ),
    ]
