# Generated by Django 3.0.3 on 2020-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('layer_manager', '0009_layeraggregatedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeraggregatedvalue',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
