# Generated by Django 3.0.7 on 2020-10-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0025_auto_20201012_1850'),
        ('layer_manager', '0011_layer_feedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='feedstock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenario_builder.Material'),
        ),
    ]
