# Generated by Django 3.0.3 on 2020-05-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioResultLayerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=56)),
                ('field_type', models.CharField(max_length=56)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='scenario_evaluator.ScenarioResultLayer')),
            ],
        ),
    ]
