# Generated by Django 3.2.8 on 2021-10-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_runningtask'),
        ('scenario_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningtask',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventories.inventoryalgorithm'),
        ),
        migrations.AlterField(
            model_name='runningtask',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventories.scenario'),
        ),
    ]
