# Generated by Django 3.2.8 on 2021-10-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_evaluator', '0002_auto_20211029_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunningTask',
        ),
    ]
