# Generated by Django 3.0.3 on 2020-06-09 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_evaluator', '0002_scenarioresultlayerfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioresultaggregate',
            name='scenarioresult_ptr',
        ),
        migrations.RemoveField(
            model_name='scenarioresultlayer',
            name='scenarioresult_ptr',
        ),
        migrations.RemoveField(
            model_name='scenarioresultlayerfield',
            name='layer',
        ),
        migrations.DeleteModel(
            name='ScenarioResult',
        ),
        migrations.DeleteModel(
            name='ScenarioResultAggregate',
        ),
        migrations.DeleteModel(
            name='ScenarioResultLayer',
        ),
        migrations.DeleteModel(
            name='ScenarioResultLayerField',
        ),
    ]
