# Generated by Django 3.0.7 on 2020-06-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenario_builder', '0004_scenario_evaluation_running'),
        ('scenario_evaluator', '0004_runningtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningtask',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scenario_builder.InventoryAlgorithm'),
        ),
    ]
