# Generated by Django 5.1.1 on 2024-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closecycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcase',
            options={'ordering': ['name', 'id']},
        ),
    ]
