# Generated by Django 4.2.8 on 2024-07-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closecycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcase',
            options={'ordering': ['name']},
        ),
    ]
