# Generated by Django 5.1.1 on 2024-10-23 12:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closecycle', '0002_alter_showcase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiogasPlantsSweden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('type', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('county', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('municipality', models.CharField(blank=True, null=True)),
                ('creation_year', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('to_upgrade', models.CharField(blank=True, null=True)),
                ('main_type', models.CharField(blank=True, null=True)),
                ('sub_type', models.CharField(blank=True, null=True)),
                ('tech_type', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'closecycle_biogas_plants_sweden',
                'managed': False,
            },
        ),
    ]
