# Generated by Django 5.1.1 on 2024-11-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closecycle', '0003_biogasplantssweden'),
        ('closecycle', '0003_remove_showcase_visible_to_groups'),
    ]

    operations = [
    ]
