# Generated by Django 6.0.8 on 2026-10-02 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("closecycle", "0004_alter_showcase_publication_status"),
        ("maps", "0019_region_name_en"),
        ("materials", "0030_product_material_category"),
        ("processes", "0015_processauthor_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="showcase",
            name="catchment",
            field=models.ForeignKey(
                blank=True,
                help_text="TBN region: the area in which regional stakeholders operate jointly to valorize regional bioresources. Borders may be framed flexibly, e.g. by bioresource catchment areas, product delivery areas or administrative borders.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="showcases",
                to="maps.catchment",
            ),
        ),
        migrations.AddField(
            model_name="showcase",
            name="sample_series",
            field=models.ManyToManyField(
                blank=True,
                help_text="Temporal sample series measured at this showcase, e.g. feedstock monitoring of the processing chain.",
                related_name="showcases",
                to="materials.sampleseries",
                verbose_name="sample series",
            ),
        ),
        migrations.AddField(
            model_name="showcase",
            name="samples",
            field=models.ManyToManyField(
                blank=True,
                help_text="Samples taken at this showcase.",
                related_name="showcases",
                to="materials.sample",
            ),
        ),
        migrations.CreateModel(
            name="ShowcaseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("input", "Input (bioresource)"),
                            ("intermediate", "Intermediate"),
                            ("product", "Product (output)"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Optional order for display purposes."
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="showcase_materials",
                        to="materials.material",
                    ),
                ),
                (
                    "showcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcase_materials",
                        to="closecycle.showcase",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="showcase",
            name="materials",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bioresources, intermediates and products of the showcase's processing chain, linked via ShowcaseMaterial.",
                related_name="showcases",
                through="closecycle.ShowcaseMaterial",
                to="materials.material",
            ),
        ),
        migrations.CreateModel(
            name="ShowcaseProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position of the process in the chain."
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="showcase_processes",
                        to="processes.process",
                    ),
                ),
                (
                    "showcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcase_processes",
                        to="closecycle.showcase",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="showcase",
            name="processes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Technical process units (logistical, pre-, main- and post-treatment) forming the showcase's processing chain, linked via ShowcaseProcess.",
                related_name="showcases",
                through="closecycle.ShowcaseProcess",
                to="processes.process",
            ),
        ),
        migrations.AddIndex(
            model_name="showcasematerial",
            index=models.Index(
                fields=["showcase", "role", "order"],
                name="closecycle__showcas_ce3a67_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="showcasematerial",
            constraint=models.UniqueConstraint(
                fields=("showcase", "material", "role"),
                name="closecycle_showcasematerial_unique_material_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="showcaseprocess",
            constraint=models.UniqueConstraint(
                fields=("showcase", "process"),
                name="closecycle_showcaseprocess_unique_process",
            ),
        ),
    ]
