# Generated by Django 6.0.8 on 2026-10-05 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("closecycle", "0005_showcase_catchment_showcase_sample_series_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="showcase",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Location of the showcase installation. Falls back to the centroid of the region's borders on maps when not set.",
                null=True,
                srid=4326,
            ),
        ),
    ]
