# Generated by Django 3.0.7 on 2021-02-06 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('flexibi_dst', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_feedstock', models.BooleanField(default=False)),
                ('stan_flow_id', models.CharField(blank=True, max_length=5, null=True, validators=[
                    django.core.validators.RegexValidator(code='invalid_stan_id',
                                                          message='STAN id must have 5 digits.s',
                                                          regex='^[0-9]{5}?')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponentGroupSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fractions_of', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                                   to='material_manager.MaterialComponent')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='material_manager.MaterialComponentGroup')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Customization', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('standard', models.BooleanField(default=True)),
                ('material',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_manager.Material')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComponentShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(default=0.0)),
                ('standard_deviation', models.FloatField(default=0.0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='material_manager.MaterialComponent')),
                ('group_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     to='material_manager.MaterialComponentGroupSettings')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='flexibi_dst.LiteratureSource')),
                ('timestep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexibi_dst.Timestep')),
            ],
        ),
        migrations.AddField(
            model_name='materialcomponentgroupsettings',
            name='material_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='material_manager.MaterialSettings'),
        ),
        migrations.AddField(
            model_name='materialcomponentgroupsettings',
            name='owner',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialcomponentgroupsettings',
            name='temporal_distributions',
            field=models.ManyToManyField(to='flexibi_dst.TemporalDistribution'),
        ),
    ]
