# Generated by Django 3.0.7 on 2021-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_manager', '0002_auto_20210218_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsettings',
            name='customization_name',
            field=models.CharField(default='Customization', max_length=255),
        ),
        migrations.AlterField(
            model_name='materialsettings',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
