# Generated by Django 3.0.7 on 2021-05-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_manager', '0003_auto_20210510_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialsettings',
            old_name='name',
            new_name='full_name',
        ),
    ]
