# Generated by Django 3.0.7 on 2021-10-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_auto_20211007_1350'),
        ('material_manager', '0005_auto_20210510_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomponentgroupsettings',
            name='sources',
            field=models.ManyToManyField(to='bibliography.Source'),
        ),
    ]
