# Generated by Django 3.2.10 on 2022-03-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
        ('distributions', '0001_initial'),
        ('bibliography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioinventoryconfiguration',
            name='feedstock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.sampleseries'),
        ),
        migrations.AddField(
            model_name='scenarioinventoryconfiguration',
            name='geodataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.geodataset'),
        ),
        migrations.AddField(
            model_name='scenarioinventoryconfiguration',
            name='inventory_algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryalgorithm'),
        ),
        migrations.AddField(
            model_name='scenarioinventoryconfiguration',
            name='inventory_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryalgorithmparameter'),
        ),
        migrations.AddField(
            model_name='scenarioinventoryconfiguration',
            name='inventory_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryalgorithmparametervalue'),
        ),
        migrations.AddField(
            model_name='scenarioinventoryconfiguration',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.scenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='catchment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catchment', to='maps.catchment'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenario',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.region'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.sfbsite'),
        ),
        migrations.AddField(
            model_name='runningtask',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryalgorithm'),
        ),
        migrations.AddField(
            model_name='runningtask',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.scenario'),
        ),
        migrations.AddField(
            model_name='inventoryamountshare',
            name='feedstock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.sampleseries'),
        ),
        migrations.AddField(
            model_name='inventoryamountshare',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryamountshare',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.scenario'),
        ),
        migrations.AddField(
            model_name='inventoryamountshare',
            name='timestep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributions.timestep'),
        ),
        migrations.AddField(
            model_name='inventoryalgorithmparametervalue',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryalgorithmparameter'),
        ),
        migrations.AddField(
            model_name='inventoryalgorithmparameter',
            name='inventory_algorithm',
            field=models.ManyToManyField(to='inventories.InventoryAlgorithm'),
        ),
        migrations.AddField(
            model_name='inventoryalgorithm',
            name='feedstocks',
            field=models.ManyToManyField(to='materials.Material'),
        ),
        migrations.AddField(
            model_name='inventoryalgorithm',
            name='geodataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.geodataset'),
        ),
        migrations.AddField(
            model_name='inventoryalgorithm',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bibliography.source'),
        ),
    ]
