# Generated by Django 3.2.10 on 2023-01-02 10:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='inventories_scenario_created', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='lastmodified_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now,
                                       verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='lastmodified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='inventories_scenario_lastmodified', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='visible_to_groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
