# Generated by Django 4.2.8 on 2024-03-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_alter_scenario_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='site',
        ),
    ]
