# Generated by Django 6.0.5 on 2026-07-11 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0006_alter_scenariostatus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariostatus",
            name="failed_algorithm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventories.inventoryalgorithm",
            ),
        ),
        migrations.AddField(
            model_name="scenariostatus",
            name="failure_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="scenariostatus",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Changed"),
                    (2, "Running"),
                    (3, "Finished"),
                    (4, "Failed"),
                ],
                default=1,
            ),
        ),
    ]
