# Generated by Django 6.0.8 on 2026-09-22 16:41

import django.db.models.deletion
from django.core.management.color import no_style
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def create_inventory_inputs(apps, schema_editor):
    InventoryInput = apps.get_model("inventories", "InventoryInput")
    InventoryAlgorithm = apps.get_model("inventories", "InventoryAlgorithm")
    Sample = apps.get_model("materials", "Sample")
    SampleSeries = apps.get_model("materials", "SampleSeries")
    connection = schema_editor.connection
    alias = connection.alias

    series_ids = list(
        SampleSeries.objects.using(alias).order_by("pk").values_list("pk", flat=True)
    )
    InventoryInput.objects.using(alias).bulk_create(
        [InventoryInput(id=pk, series_id=pk) for pk in series_ids]
    )

    offset = max(series_ids, default=0)
    sample_ids = list(
        Sample.objects.using(alias)
        .filter(standalone=True)
        .order_by("pk")
        .values_list("pk", flat=True)
    )
    InventoryInput.objects.using(alias).bulk_create(
        [InventoryInput(id=offset + pk, sample_id=pk) for pk in sample_ids]
    )

    InventoryAlgorithm.objects.using(alias).filter(
        function_name__in=(
            "hamburg_park_production",
            "hamburg_roadside_tree_production",
        )
    ).update(supports_standalone_samples=True)

    with connection.cursor() as cursor:
        for sql in connection.ops.sequence_reset_sql(no_style(), [InventoryInput]):
            cursor.execute(sql)


def _retarget_fk(
    schema_editor, table, column, target_table, constraint_name, rewrite=None
):
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT kcu.constraint_name
            FROM information_schema.key_column_usage kcu
            JOIN information_schema.table_constraints tc
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
             AND tc.table_name = kcu.table_name
            WHERE kcu.table_schema = current_schema()
              AND kcu.table_name = %s
              AND kcu.column_name = %s
              AND tc.constraint_type = 'FOREIGN KEY'
            """,
            [table, column],
        )
        constraint_names = [row[0] for row in cursor.fetchall()]
        for existing_name in constraint_names:
            cursor.execute(
                f"ALTER TABLE {quote(table)} DROP CONSTRAINT {quote(existing_name)}"
            )
        if rewrite is not None:
            rewrite(schema_editor, table, column)
        cursor.execute(
            f"ALTER TABLE {quote(table)} "
            f"ADD CONSTRAINT {quote(constraint_name)} "
            f"FOREIGN KEY ({quote(column)}) REFERENCES {quote(target_table)} ({quote('id')}) "
            "DEFERRABLE INITIALLY DEFERRED"
        )


def map_feedstock_to_series(schema_editor, table, column="feedstock_id"):
    """Rewrite adapter IDs in ``table.column`` to the wrapped series IDs.

    Rows that wrap a standalone sample have no series equivalent, so the
    reverse migration refuses to run while such rows exist.
    """
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT COUNT(*) FROM {quote(table)} t "
            f"JOIN {quote('inventories_inventoryinput')} ii ON ii.id = t.{quote(column)} "
            "WHERE ii.series_id IS NULL"
        )
        standalone_count = cursor.fetchone()[0]
        if standalone_count:
            raise IrreversibleError(
                f"{standalone_count} row(s) in {table}.{column} reference standalone "
                "sample inventory inputs, which have no sample series equivalent. "
                "Delete those scenario configurations and result layers before "
                "reversing this migration."
            )
        cursor.execute(
            f"UPDATE {quote(table)} t SET {quote(column)} = ii.series_id "
            f"FROM {quote('inventories_inventoryinput')} ii "
            f"WHERE ii.id = t.{quote(column)}"
        )


def retarget_feedstock_fks_to_inventoryinput(apps, schema_editor):
    _retarget_fk(
        schema_editor,
        "inventories_inventoryamountshare",
        "feedstock_id",
        "inventories_inventoryinput",
        "inventoryamountshare_feedstock_inventoryinput_fk",
    )
    _retarget_fk(
        schema_editor,
        "inventories_scenarioinventoryconfiguration",
        "feedstock_id",
        "inventories_inventoryinput",
        "scenarioconfig_feedstock_inventoryinput_fk",
    )


def retarget_feedstock_fks_to_sampleseries(apps, schema_editor):
    _retarget_fk(
        schema_editor,
        "inventories_inventoryamountshare",
        "feedstock_id",
        "materials_sampleseries",
        "inventoryamountshare_feedstock_sampleseries_fk",
        rewrite=map_feedstock_to_series,
    )
    _retarget_fk(
        schema_editor,
        "inventories_scenarioinventoryconfiguration",
        "feedstock_id",
        "materials_sampleseries",
        "scenarioconfig_feedstock_sampleseries_fk",
        rewrite=map_feedstock_to_series,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0007_scenariostatus_failed_algorithm_and_more"),
        ("materials", "0028_samplegroup_sample_sample_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryalgorithm",
            name="supports_sample_series",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inventoryalgorithm",
            name="supports_standalone_samples",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="InventoryInput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_input",
                        to="materials.sample",
                    ),
                ),
                (
                    "series",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_input",
                        to="materials.sampleseries",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_inventory_inputs, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="inventoryamountshare",
                    name="feedstock",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventories.inventoryinput",
                    ),
                ),
                migrations.AlterField(
                    model_name="scenarioinventoryconfiguration",
                    name="feedstock",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventories.inventoryinput",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    retarget_feedstock_fks_to_inventoryinput,
                    retarget_feedstock_fks_to_sampleseries,
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inventoryinput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sample__isnull", False), ("series__isnull", True)),
                    models.Q(("sample__isnull", True), ("series__isnull", False)),
                    _connector="OR",
                ),
                name="inventory_input_exactly_one_source",
            ),
        ),
    ]
