# Generated by Django 6.0.8 on 2026-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0007_scenariostatus_failed_algorithm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryalgorithmparametervalue",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                verbose_name="User-provided assumption, not a curated preset",
            ),
        ),
    ]
