# Generated by Django 3.0.7 on 2021-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0003_delete_literaturesource'),
        ('inventories', '0007_auto_20211007_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodataset',
            name='sources',
            field=models.ManyToManyField(to='bibliography.Source'),
        ),
    ]
