# Generated by Django 5.1.1 on 2024-11-04 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0007_alter_scenario_options'),
        ('maps', '0016_alter_geodataset_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='catchment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='maps.catchment'),
        ),
    ]
