# Generated by Django 5.1.1 on 2024-11-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_alter_scenario_catchment'),
        ('inventories', '0008_remove_scenario_visible_to_groups'),
    ]

    operations = [
    ]
