# Generated by Django 4.2.8 on 2024-04-12 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0014_attribute_publication_status_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('materials', '0009_alter_composition_fractions_of'),
        ('inventories', '0008_scenarioinventoryconfiguration_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryAlgorithmParameter',
            new_name='Parameter',
        ),
        migrations.RenameModel(
            old_name='InventoryAlgorithmParameterValue',
            new_name='ParameterValue',
        ),
        migrations.RenameModel(
            old_name='ScenarioInventoryConfiguration',
            new_name='ScenarioConfiguration',
        ),
    ]
