# Generated by Django 6.0.8 on 2026-10-02 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("closecycle", "0005_showcase_catchment_showcase_sample_series_and_more"),
        ("inventories", "0009_feedstock_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="showcase",
            field=models.ForeignKey(
                blank=True,
                help_text="CLOSECYCLE showcase whose inventory this scenario evaluates within its TBN region.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenarios",
                to="closecycle.showcase",
            ),
        ),
    ]
