# Generated by Django 3.2.8 on 2021-10-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_auto_20211011_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('algorithm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.inventoryalgorithm')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.scenario')),
            ],
        ),
    ]
