# Generated by Django 3.2.8 on 2021-10-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_runningtask'),
    ]

    operations = [
    ]
