# Generated by Django 4.2.8 on 2024-04-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0011_algorithm_created_at_algorithm_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='data_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='default_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for', to='inventories.parametervalue'),
            preserve_default=False,
        ),
    ]
