# Generated by Django 3.2.8 on 2021-10-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('distributions', '0001_initial'),
        ('inventories', '0011_auto_20211029_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryamountshare',
            name='timestep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='distributions.timestep'),
        ),
    ]
