# Generated by Django 4.2.8 on 2024-04-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0017_author_publication_status_licence_publication_status_and_more'),
        ('inventories', '0012_parameter_data_type_parameter_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventories.parameter'),
        ),
        migrations.RenameField(
            model_name='parametervalue',
            old_name='source',
            new_name='source_old',
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.source', null=True),
        ),
    ]
