# Generated by Django 3.2.8 on 2021-11-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20211102_1340'),
        ('inventories', '0013_auto_20211102_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodataset',
            name='region',
        ),
        migrations.RemoveField(
            model_name='geodataset',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='sfbsite',
            name='owner',
        ),
        migrations.AlterField(
            model_name='inventoryalgorithm',
            name='geodataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.geodataset'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='catchment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.catchment'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.region'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.sfbsite'),
        ),
        migrations.AlterField(
            model_name='scenarioinventoryconfiguration',
            name='geodataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.geodataset'),
        ),
        migrations.DeleteModel(
            name='Catchment',
        ),
        migrations.DeleteModel(
            name='GeoDataset',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='SFBSite',
        ),
    ]
