# Generated by Django 4.2.8 on 2024-04-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0013_alter_parametervalue_parameter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenarioconfiguration',
            old_name='inventory_algorithm',
            new_name='algorithm',
        ),
    ]
