# Generated by Django 3.2.8 on 2021-11-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_alter_geodataset_model_name'),
        ('inventories', '0014_auto_20211102_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='catchment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catchment', to='maps.catchment'),
        ),
    ]
