# Generated by Django 4.2.8 on 2024-04-12 14:18

from django.db import migrations

def create_parameter_settings(apps, schema_editor):
    ScenarioConfiguration = apps.get_model('inventories', 'ScenarioConfiguration')
    ScenarioParameterSetting = apps.get_model('inventories', 'ScenarioParameterSetting')

    keep = []
    for config in ScenarioConfiguration.objects.all():
        target = None
        for keeper in keep:
            if config.scenario == keeper.scenario and config.feedstock == keeper.feedstock and config.geodataset == keeper.geodataset and config.algorithm == keeper.algorithm:
                target = keeper

        if target is None:
            keep.append(config)
            target = config

        setting, _ = ScenarioParameterSetting.objects.get_or_create(
            scenario_configuration=target,
            parameter_value=config.inventory_value,
        )

        if config.id != target.id:
            config.delete()

def create_new_sources_links(apps, schema_editor):
    Source = apps.get_model('bibliography', 'Source')
    ParameterValue = apps.get_model('inventories', 'ParameterValue')

    for val in ParameterValue.objects.all():
        if val.source_old:
            source = Source.objects.filter(abbreviation=val.source_old)
            if source.exists():
                source = source.first()
                val.source = source
                val.save()

def migrate_default_values(apps, schema_editor):
    Parameter = apps.get_model('inventories', 'Parameter')

    for parameter in Parameter.objects.all():
        for value in parameter.values.all():
            if value.default:
                parameter.default_value = value
                parameter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0015_remove_parametervalue_source_old_and_more'),
    ]

    operations = [
        migrations.RunPython(create_parameter_settings),
        migrations.RunPython(create_new_sources_links),
        migrations.RunPython(migrate_default_values),
    ]
