# Generated by Django 4.2.8 on 2024-04-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0016_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='inventories.algorithm'),
            preserve_default=False,
        ),
    ]
