# Generated by Django 4.2.8 on 2024-04-16 10:08

from django.db import migrations


def migrate_parameters(apps, schema_editor):
    Parameter = apps.get_model('inventories', 'Parameter')

    for parameter in Parameter.objects.all():
        parameter.algorithm = parameter.inventory_algorithm.first()
        parameter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0017_parameter_algorithm'),
    ]

    operations = [
        migrations.RunPython(migrate_parameters),
    ]
