# Generated by Django 4.2.8 on 2024-04-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0018_migrate_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='inventory_algorithm',
        ),
    ]
