# Generated by Django 4.2.8 on 2024-04-17 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_attribute_publication_status_and_more'),
        ('inventories', '0019_remove_parameter_inventory_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='geodataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='maps.geodataset'),
        ),
    ]
