# Generated by Django 4.2.8 on 2024-04-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0020_alter_algorithm_geodataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametervalue',
            name='default',
        ),
        migrations.RemoveField(
            model_name='parametervalue',
            name='source_old',
        ),
    ]
