# Generated by Django 4.2.8 on 2024-07-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_alter_attribute_options_alter_catchment_options_and_more'),
        ('inventories', '0021_remove_parametervalue_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='scenario',
            name='catchment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='maps.catchment'),
        ),
        migrations.AlterField(
            model_name='scenariostatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'Changed'), (2, 'Running'), (3, 'Finished'), (4, 'Failed')], default=1),
        ),
    ]
