from sources.contracts import (
    SourceDomainDatasetRuntimeCompatibility,
    SourceDomainLegacyRedirects,
    SourceDomainMapMount,
    SourceDomainPlugin,
)

plugin = SourceDomainPlugin(
    slug="roadside_trees",
    verbose_name="Roadside Trees",
    app_config="sources.roadside_trees.apps.RoadsideTreesConfig",
    urlconf="sources.roadside_trees.urls",
    capabilities=(
        "api",
        "exports",
        "html_views",
        "legacy_redirects",
        "static_assets",
        "templates",
    ),
    mount_in_hub=True,
    mount_path="",
    map_mount=SourceDomainMapMount(
        mount_path="hamburg/",
        urlconf="sources.roadside_trees.urls",
    ),
    legacy_redirects=SourceDomainLegacyRedirects(
        mount_path="case_studies/hamburg/",
        urlconf="sources.roadside_trees.legacy_urls",
    ),
    dataset_runtime_compatibilities=(
        SourceDomainDatasetRuntimeCompatibility(
            runtime_model_name="HamburgRoadsideTrees",
            model="sources.roadside_trees.models.HamburgRoadsideTrees",
            filterset_class=(
                "sources.roadside_trees.filters.HamburgRoadsideTreesFilterSet"
            ),
            template_name="hamburg_roadside_trees_map.html",
            features_api_basename="api-hamburg-roadside-trees",
            apply_user_visibility_filter=False,
        ),
    ),
    sitemap_items=(
        "/maps/hamburg/roadside_trees/data/",
        "/maps/hamburg/roadside_trees/map/",
        "/maps/hamburg/roadside_trees/export/",
        "/maps/hamburg/roadside_trees/catchment_autocomplete/",
        "/case_studies/hamburg/roadside_trees/data/",
        "/case_studies/hamburg/roadside_trees/map/",
        "/case_studies/hamburg/roadside_trees/export/",
        "/case_studies/hamburg/roadside_trees/catchment_autocomplete/",
    ),
    geojson_cache_warmer="sources.roadside_trees.tasks.warm_roadside_tree_geojson_cache",
)
