# Generated by Django 3.0.3 on 2020-05-19 11:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HamburgRoadsideTrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('baumid', models.IntegerField(blank=True, null=True)),
                ('gattung', models.CharField(blank=True, max_length=56, null=True)),
                ('gattung_latein', models.CharField(blank=True, max_length=56, null=True)),
                ('gattung_deutsch', models.CharField(blank=True, max_length=56, null=True)),
                ('art', models.CharField(blank=True, max_length=56, null=True)),
                ('art_latein', models.CharField(blank=True, max_length=56, null=True)),
                ('art_deutsch', models.CharField(blank=True, max_length=56, null=True)),
                ('sorte_latein', models.CharField(blank=True, max_length=56, null=True)),
                ('sorte_deutsch', models.CharField(blank=True, max_length=56, null=True)),
                ('pflanzjahr', models.IntegerField(blank=True, null=True)),
                ('pflanzjahr_portal', models.IntegerField(blank=True, null=True)),
                ('kronendurchmesser', models.IntegerField(blank=True, null=True)),
                ('stammumfang', models.IntegerField(blank=True, null=True)),
                ('strasse', models.CharField(blank=True, max_length=56, null=True)),
                ('hausnummer', models.CharField(blank=True, max_length=56, null=True)),
                ('ortsteil_nr', models.CharField(blank=True, max_length=56, null=True)),
                ('stadtteil', models.CharField(blank=True, max_length=56, null=True)),
                ('bezirk', models.CharField(blank=True, max_length=56, null=True)),
            ],
        ),
    ]
