# Generated by Django 3.0.3 on 2020-05-28 17:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gis_source_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburggreenareas',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
