# Generated by Django 3.0.7 on 2020-10-29 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gis_source_manager', '0002_auto_20200528_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='NantesGreenhouses',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id_exp', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_exp', models.CharField(blank=True, max_length=255, null=True)),
                ('id_serre', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('surface_ha', models.CharField(blank=True, max_length=255, null=True)),
                ('nb_cycles', models.IntegerField(blank=True, null=True)),
                ('culture_1', models.CharField(blank=True, max_length=20, null=True)),
                ('start_cycle_1', models.CharField(blank=True, max_length=20, null=True)),
                ('end_cycle_1', models.CharField(blank=True, max_length=20, null=True)),
                ('culture_2', models.CharField(blank=True, max_length=20, null=True)),
                ('start_cycle_2', models.CharField(blank=True, max_length=20, null=True)),
                ('end_cycle_2', models.CharField(blank=True, max_length=20, null=True)),
                ('culture_3', models.CharField(blank=True, max_length=20, null=True)),
                ('start_cycle_3', models.CharField(blank=True, max_length=20, null=True)),
                ('end_cycle_3', models.CharField(blank=True, max_length=20, null=True)),
                ('layer', models.CharField(blank=True, max_length=20, null=True)),
                ('heated', models.BooleanField(blank=True, null=True)),
                ('lighted', models.BooleanField(blank=True, null=True)),
                ('high_wire', models.BooleanField(blank=True, null=True)),
                ('aboveground', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nantes_greenhouses',
                'managed': False,
            },
        ),
    ]
