# Generated by Django 3.0.7 on 2020-10-29 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gis_source_manager', '0003_nantesgreenhouses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nantesgreenhouses',
            table=None,
        ),
    ]
