# Generated by Django 3.0.7 on 2020-10-29 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gis_source_manager', '0004_auto_20201029_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nantesgreenhouses',
            options={},
        ),
    ]
