# Generated by Django 3.0.7 on 2020-10-30 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gis_source_manager', '0005_auto_20201029_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nantesgreenhouses',
            old_name='aboveground',
            new_name='above_ground',
        ),
    ]
