# Generated by Django 6.0.5 on 2026-07-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bibliography", "0010_author_contact_details"),
        ("maps", "0015_geodatasetcolumnpolicy_is_popup"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("provider", models.CharField(max_length=255)),
                (
                    "source_code",
                    models.CharField(
                        blank=True,
                        help_text="Upstream dataset code, e.g. 'nama_10r_3popgdp'.",
                        max_length=255,
                    ),
                ),
                (
                    "geographic_scope",
                    models.CharField(
                        choices=[("nuts", "NUTS"), ("lau", "LAU")], max_length=10
                    ),
                ),
                (
                    "temporal_basis",
                    models.CharField(
                        choices=[
                            ("calendar_year_average", "Calendar year average"),
                            ("point_in_time", "Point in time"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of the upstream values before conversion to persons, e.g. 'THS'.",
                        max_length=30,
                    ),
                ),
                (
                    "classification_version",
                    models.CharField(
                        blank=True,
                        help_text="NUTS/LAU classification version, e.g. 'NUTS2021'.",
                        max_length=30,
                    ),
                ),
                (
                    "is_canonical",
                    models.BooleanField(
                        default=False,
                        help_text="Preferred dataset when multiple datasets cover the same region and year.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bibliography_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="population_datasets",
                        to="bibliography.source",
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="PopulationEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("value", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "is_mixed_provenance",
                    models.BooleanField(
                        default=False,
                        help_text="True when components come from methodologically different datasets.",
                    ),
                ),
                ("is_provisional", models.BooleanField(default=False)),
                ("calculated_at", models.DateTimeField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="population_estimates",
                        to="maps.region",
                    ),
                ),
            ],
            options={
                "ordering": ["region_id", "year"],
            },
        ),
        migrations.CreateModel(
            name="PopulationImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extracted_at", models.DateTimeField()),
                ("upstream_updated_at", models.DateTimeField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("structure_version", models.CharField(blank=True, max_length=100)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to="population.populationdataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="PopulationObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("value", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "source_status",
                    models.CharField(
                        choices=[
                            ("final", "Final"),
                            ("provisional", "Provisional"),
                            ("estimated", "Estimated"),
                        ],
                        default="final",
                        max_length=20,
                    ),
                ),
                (
                    "flags",
                    models.CharField(
                        blank=True,
                        help_text="Raw upstream status/revision flags, e.g. Eurostat 'p'.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="population.populationdataset",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="population.populationimportrun",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="population_observations",
                        to="maps.region",
                    ),
                ),
            ],
            options={
                "ordering": ["region_id", "year"],
            },
        ),
        migrations.CreateModel(
            name="PopulationEstimateComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_links",
                        to="population.populationestimate",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_links",
                        to="population.populationobservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="populationestimate",
            name="components",
            field=models.ManyToManyField(
                related_name="dependent_estimates",
                through="population.PopulationEstimateComponent",
                to="population.populationobservation",
            ),
        ),
        migrations.AddIndex(
            model_name="populationobservation",
            index=models.Index(
                fields=["region", "year"], name="population_obs_region_year_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="populationobservation",
            constraint=models.UniqueConstraint(
                fields=("dataset", "region", "year"),
                name="population_observation_dataset_region_year_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="populationestimatecomponent",
            constraint=models.UniqueConstraint(
                fields=("estimate", "observation"),
                name="population_estimate_component_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="populationestimate",
            constraint=models.UniqueConstraint(
                fields=("region", "year"), name="population_estimate_region_year_unique"
            ),
        ),
    ]
