# Generated by Django 6.0.5 on 2026-07-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0015_geodatasetcolumnpolicy_is_popup"),
        ("population", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="populationestimate",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="population_estimates",
                to="maps.region",
            ),
        ),
        migrations.AlterField(
            model_name="populationestimatecomponent",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="component_links",
                to="population.populationobservation",
            ),
        ),
        migrations.AlterField(
            model_name="populationobservation",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="population_observations",
                to="maps.region",
            ),
        ),
    ]
