# Generated by Django 3.2.10 on 2023-02-20 09:51

from django.db import migrations
from users.models import get_default_owner


def create_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    owner = User.objects.get(username=get_default_owner().username)
    Unit = apps.get_model('utils', 'Unit')
    no_unit, _ = Unit.objects.get_or_create(owner=owner, name='No unit', dimensionless=True)


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_unit'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
