# Generated by Django 3.2.10 on 2023-02-20 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0003_initial_units'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('owner', 'name')},
        ),
    ]
