# Generated by Django 4.2.8 on 2024-03-03 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0005_alter_property_created_by_and_more'),
    ]

    database_operations = [
        migrations.AlterModelTable('Unit', 'properties_unit'),
        migrations.AlterModelTable('Property', 'properties_property'),
        migrations.RunSQL(
            sql="""
                        CREATE TABLE IF NOT EXISTS utils_unit (
                            id SERIAL PRIMARY KEY
                        );
                        CREATE TABLE IF NOT EXISTS utils_property (
                            id SERIAL PRIMARY KEY
                        );
                    """,
            reverse_sql="""
                        DROP TABLE IF EXISTS utils_unit;
                        DROP TABLE IF EXISTS utils_property;
                        """,
        ),
    ]

    state_operations = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        ),
    ]
