# Generated by Django 4.2.8 on 2024-03-03 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('soilcom', '0025_alter_aggregatedcollectionpropertyvalue_property_and_more'),
        ('utils', '0006_migrate_properties_first_step'),
    ]

    database_operations = [
        migrations.RunSQL(
            sql="""
                    DROP TABLE IF EXISTS utils_unit;
                    DROP TABLE IF EXISTS utils_property;
                """,
            reverse_sql="""
                            CREATE TABLE IF NOT EXISTS utils_unit (
                                id SERIAL PRIMARY KEY
                            );
                            CREATE TABLE IF NOT EXISTS utils_property (
                                id SERIAL PRIMARY KEY
                            );
                        """,
        ),
    ]

    state_operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='lastmodified_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reference_quantity',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='visible_to_groups',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        ),
    ]
