# Generated by Django 4.2.8 on 2024-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0007_alter_unit_unique_together_remove_unit_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=50, unique=True)),
                ('full_path', models.TextField()),
            ],
        ),
    ]
