# Generated by Django 3.2.10 on 2022-02-04 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('soilcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='waste_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='soilcom.wastestream'),
        ),
    ]
