# Generated by Django 3.2.10 on 2022-04-01 07:46

from django.db import migrations
from users.models import get_default_owner


def create_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    owner = User.objects.get(username=get_default_owner().username)
    Region = apps.get_model('maps', 'Region')
    region, _ = Region.objects.get_or_create(owner=owner, name='Europe (NUTS)')
    GeoDataset = apps.get_model('maps', 'GeoDataset')
    GeoDataset.objects.create(
        owner=owner,
        name='Household Biowaste Collection',
        model_name='WasteCollection',
        region=region
    )


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0001_initial'),
        ('maps', '0001_initial'),
        ('users', '0001_initial_data')
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
