# Generated by Django 3.2.10 on 2022-02-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('soilcom', '0002_alter_collection_waste_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='flyers',
            field=models.ManyToManyField(related_name='collections', to='soilcom.WasteFlyer'),
        ),
    ]
