# Generated by Django 3.2.10 on 2022-05-05 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_initial_data'),
        ('soilcom', '0003_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='connection_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='connection_rate_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{4})$', code='invalid year', message='Year needs to be in YYYY format.')]),
        ),
        migrations.AddField(
            model_name='collection',
            name='sources',
            field=models.ManyToManyField(to='bibliography.Source'),
        ),
    ]
