# Generated by Django 3.2.8 on 2021-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20211029_1331'),
        ('soilcom', '0003_auto_20211108_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastecategory',
            options={'verbose_name': 'Waste Category', 'verbose_name_plural': 'Waste categories'},
        ),
        migrations.RenameField(
            model_name='wastestream',
            old_name='materials',
            new_name='allowed_materials',
        ),
        migrations.AddField(
            model_name='wastestream',
            name='composition',
            field=models.ManyToManyField(to='materials.MaterialSettings'),
        ),
    ]
