# Generated by Django 5.2.4 on 2025-11-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0003_alter_author_publication_status_and_more'),
        ('soilcom', '0003_alter_aggregatedcollectionpropertyvalue_publication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedcollectionpropertyvalue',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Sources or references for this property value.', to='bibliography.source'),
        ),
        migrations.AddField(
            model_name='collectionpropertyvalue',
            name='sources',
            field=models.ManyToManyField(blank=True, help_text='Sources or references for this property value.', to='bibliography.source'),
        ),
    ]
