# Generated by Django 3.2.10 on 2022-09-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_regionattributevalue_date'),
        ('soilcom', '0004_add_connection_rate_and_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.catchment'),
        ),
    ]
