# Generated by Django 3.2.8 on 2021-11-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0004_auto_20211108_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastestream',
            options={'verbose_name': 'Waste Stream'},
        ),
    ]
