# Generated by Django 3.2.8 on 2021-11-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0007_alter_source_options'),
        ('soilcom', '0005_alter_wastestream_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteFlyer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bibliography.source',),
        ),
    ]
