# Generated by Django 3.2.10 on 2022-09-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import brit.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soilcom', '0005_collector_catchment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionfrequency',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionsystem',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collector',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wastecategory',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wastestream',
            name='owner',
            field=models.ForeignKey(default=brit.models.get_default_owner_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
