# Generated by Django 3.2.8 on 2021-11-15 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('soilcom', '0006_wasteflyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wasteflyer',
            options={'verbose_name': 'Waste Flyer'},
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('collection_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcom.collectionsystem')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcom.collector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soilcom_collection_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('flyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcom.wasteflyer')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soilcom_collection_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visible_to_groups', models.ManyToManyField(to='auth.Group')),
                ('waste_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcom.wastestream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
