# Generated by Django 3.2.10 on 2022-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0006_auto_20220924_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='fee_system',
            field=models.CharField(choices=[('No fee', 'No fee'), ('Fixed fee', 'Fixed fee'), ('Pay as you throw (PAYT)', 'Pay as you throw (PAYT)')], max_length=32, null=True),
        ),
    ]
