# Generated by Django 3.2.8 on 2021-11-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_georeferencedcatchment_georeferencednutsregion'),
        ('soilcom', '0007_auto_20211115_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maps.catchment'),
        ),
    ]
