# Generated by Django 5.2.4 on 2026-02-17 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "soilcom",
            "0006_alter_aggregatedcollectionpropertyvalue_publication_status_and_more",
        ),
        ("soilcom", "0007_enforce_unique_derived_cpv"),
    ]

    operations = []
