# Generated by Django 3.2.8 on 2021-11-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_alter_geodataset_model_name'),
        ('materials', '0011_alter_material_options'),
        ('soilcom', '0008_collection_catchment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoreferencedWasteCollection',
            fields=[
                ('collection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='soilcom.collection')),
                ('geopolygon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.geopolygon')),
            ],
            options={
                'abstract': False,
            },
            bases=('maps.geopolygon', 'soilcom.collection'),
        ),
        migrations.CreateModel(
            name='WasteComponent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('materials.material',),
        ),
    ]
