# Generated by Django 3.2.8 on 2021-12-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0009_georeferencedwastecollection_wastecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='website',
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
    ]
