# Generated by Django 3.2.10 on 2022-11-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0012_auto_20221122_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='soilcom.collectioncatchment'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='soilcom.collectionsystem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='soilcom.collectionfrequency'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='waste_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='soilcom.wastestream'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='catchment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soilcom.collectioncatchment'),
        ),
    ]
