# Generated by Django 3.2.10 on 2022-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0013_auto_20221125_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionfrequency',
            name='type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Fixed-Flexible', 'Fixed-Flexible'), ('Fixed-Seasonal', 'Fixed-Seasonal'), ('Seasonal', 'Seasonal')], default='Fixed', max_length=16),
        ),
    ]
