# Generated by Django 3.2.10 on 2022-11-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0014_collectionfrequency_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionfrequency',
            options={'verbose_name_plural': 'collection frequencies'},
        ),
    ]
