# Generated by Django 3.2.10 on 2022-12-07 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions', '0006_initial_data'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('soilcom', '0015_alter_collectionfrequency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSeason',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('distributions.period',),
        ),
        migrations.CreateModel(
            name='CollectionCountOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created at')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last modified at')),
                ('standard', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('option_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('option_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('option_3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soilcom_collectioncountoptions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soilcom.collectionfrequency')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soilcom_collectioncountoptions_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('owner', models.ForeignKey(default=utils.models.get_default_owner_pk, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soilcom.collectionseason')),
                ('visible_to_groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collectionfrequency',
            name='seasons',
            field=models.ManyToManyField(through='soilcom.CollectionCountOptions', to='soilcom.CollectionSeason'),
        ),
    ]
