# Generated by Django 3.2.10 on 2022-12-22 11:16

from django.db import migrations
from users.models import get_default_owner


def create_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    owner = User.objects.get(username=get_default_owner().username)
    TemporalDistribution = apps.get_model('distributions', 'TemporalDistribution')
    distribution, _ = TemporalDistribution.objects.get_or_create(owner=owner, name='Months of the year')
    Timestep = apps.get_model('distributions', 'Timestep')
    january, _ = Timestep.objects.get_or_create(owner=owner, distribution=distribution, name='January')
    december, _ = Timestep.objects.get_or_create(owner=owner, distribution=distribution, name='December')
    Period = apps.get_model('distributions', 'Period')
    season, _ = Period.objects.get_or_create(
        distribution=distribution,
        first_timestep=january,
        last_timestep=december
    )
    CollectionFrequency = apps.get_model('soilcom', 'CollectionFrequency')
    frequency, _ = CollectionFrequency.objects.get_or_create(type='Fixed')
    CollectionCountOptions = apps.get_model('soilcom', 'CollectionCountOptions')
    CollectionCountOptions.objects.get_or_create(
        season=season,
        frequency=frequency,
        standard=52
    )


class Migration(migrations.Migration):
    dependencies = [
        ('soilcom', '0016_auto_20221207_1619'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
