# Generated by Django 3.2.10 on 2023-02-20 10:06

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_unit_unique_together'),
        ('soilcom', '0018_auto_20230209_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedcollectionpropertyvalue',
            name='unit',
            field=models.ForeignKey(default=utils.models.get_default_unit_pk, on_delete=django.db.models.deletion.PROTECT, to='utils.unit'),
        ),
        migrations.AddField(
            model_name='collectionpropertyvalue',
            name='unit',
            field=models.ForeignKey(default=utils.models.get_default_unit_pk, on_delete=django.db.models.deletion.PROTECT, to='utils.unit'),
        ),
    ]
