# Generated by Django 3.2.10 on 2023-04-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0019_auto_20230220_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='connection_rate',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='connection_rate_year',
        ),
    ]
