# Generated by Django 4.2.8 on 2024-01-10 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0021_alter_aggregatedcollectionpropertyvalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
