# Generated by Django 4.2.8 on 2024-01-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0023_rename_date_collection_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='predecessors',
            field=models.ManyToManyField(blank=True, related_name='successors', to='soilcom.collection'),
        ),
    ]
