# Generated by Django 4.2.8 on 2024-03-03 10:49

import django.db.models.deletion
from django.db import migrations, models

import utils.properties.models


class Migration(migrations.Migration):
    dependencies = [
        ('properties', '0001_initial'),
        ('soilcom', '0024_collection_predecessors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedcollectionpropertyvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='aggregatedcollectionpropertyvalue',
            name='unit',
            field=models.ForeignKey(default=utils.properties.models.get_default_unit_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to='properties.unit'),
        ),
        migrations.AlterField(
            model_name='collectionpropertyvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='collectionpropertyvalue',
            name='unit',
            field=models.ForeignKey(default=utils.properties.models.get_default_unit_pk,
                                    on_delete=django.db.models.deletion.PROTECT, to='properties.unit'),
        ),
    ]
