# Generated by Django 4.2.8 on 2024-03-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0025_alter_aggregatedcollectionpropertyvalue_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='fee_system',
            new_name='old_fee_system',
        ),
    ]
