# Generated by Django 4.2.8 on 2024-03-07 15:11

from django.db import migrations


def migrate_fee_system_data(apps, schema_editor):
    FeeSystem = apps.get_model('soilcom', 'FeeSystem')
    Collection = apps.get_model('soilcom', 'Collection')
    for collection in Collection.objects.all():
        if collection.old_fee_system:
            fee_system, _ = FeeSystem.objects.get_or_create(name=collection.old_fee_system)
            collection.fee_system = fee_system
            collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0027_feesystem_collection_fee_system'),
    ]

    operations = [
        migrations.RunPython(migrate_fee_system_data),
    ]
