# Generated by Django 4.2.8 on 2024-03-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0028_migrate_fee_system_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='old_fee_system',
        ),
    ]
