# Generated by Django 5.1.1 on 2024-11-16 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('soilcom', '0031_alter_collection_options_alter_feesystem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregatedcollectionpropertyvalue',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='collectioncountoptions',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='collectionfrequency',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='collectionpropertyvalue',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='collectionsystem',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='collector',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='feesystem',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='wastecategory',
            name='visible_to_groups',
        ),
        migrations.RemoveField(
            model_name='wastestream',
            name='visible_to_groups',
        ),
    ]
