# Generated by Django 5.1.1 on 2024-12-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0032_remove_aggregatedcollectionpropertyvalue_visible_to_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionsystem',
            options={'verbose_name': 'waste collection system'},
        ),
        migrations.AlterModelOptions(
            name='collector',
            options={'verbose_name': 'waste collector'},
        ),
        migrations.AlterModelOptions(
            name='wastecategory',
            options={'verbose_name_plural': 'waste categories'},
        ),
    ]
