# Generated by Django 5.1.7 on 2025-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0033_alter_collectionsystem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='connection_type',
            field=models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('VOLUNTARY', 'Voluntary')], default='VOLUNTARY', help_text='Indicates whether connection to the collection system is compulsory or voluntary.', max_length=12, verbose_name='Connection type'),
        ),
    ]
