# Generated by Django 5.1.7 on 2025-05-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0034_collection_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='min_ton_size',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest available container size for this collection (in liters)', null=True, verbose_name='Minimum container size (L)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='min_ton_volume_per_inhabitant',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum available container volume per inhabitant (in liters per person)', null=True, verbose_name='Minimum container volume per inhabitant (L/person)'),
        ),
    ]
