# Generated by Django 5.1.7 on 2025-05-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0035_collection_min_ton_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='min_ton_size',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='min_ton_volume_per_inhabitant',
        ),
        migrations.AddField(
            model_name='collection',
            name='min_bin_size',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest physical bin size that the collector provides for this collection. Exceprions may apply (e.g. for home composters)', null=True, verbose_name='Smallest available bin size (L)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='required_bin_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum total bin capacity that must be supplied per reference unit (see field below).', null=True, verbose_name='Required bin capacity per unit (L)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='required_bin_capacity_reference',
            field=models.CharField(blank=True, choices=[('person', 'per person'), ('household', 'per household'), ('property', 'per property'), (None, '—')], default=None, help_text='Defines the unit (person, household, property) for which the required bin capacity applies. Leave blank if not specified.', max_length=16, null=True, verbose_name='Reference unit for required bin capacity'),
        ),
    ]
