# Generated by Django 5.1.7 on 2025-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilcom', '0036_remove_collection_min_ton_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('COMPULSORY', 'Compulsory'), ('VOLUNTARY', 'Voluntary')], default='VOLUNTARY', help_text='Indicates whether connection to the collection system is compulsory or voluntary.', max_length=12, null=True, verbose_name='Connection type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='required_bin_capacity_reference',
            field=models.CharField(blank=True, choices=[('person', 'per person'), ('household', 'per household'), ('property', 'per property'), ('not_specified', 'Not specified')], default=None, help_text='Defines the unit (person, household, property) for which the required bin capacity applies. Leave blank if not specified.', max_length=16, null=True, verbose_name='Reference unit for required bin capacity'),
        ),
    ]
