from django.contrib.gis.db.models import PointField
from django.db import models
from django.db.models import (
    CASCADE,
    PROTECT,
    CharField,
    ForeignKey,
    ManyToManyField,
    Model,
    PositiveIntegerField,
    Prefetch,
    UniqueConstraint,
)
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from maps.models import Catchment, Region
from materials.models import Material, Sample, SampleSeries
from processes.models import Process
from utils.object_management.models import NamedUserCreatedObject
from utils.object_management.permissions import filter_queryset_for_user


class Showcase(NamedUserCreatedObject):
    """
    A CLOSECYCLE showcase demonstrates best practices or innovative solutions
    for the valorization of residue-based bioresources from rural and urban
    areas to make products for use within the showcase region. Each showcase
    focuses on a specific topic and is assigned to one of the seven broader
    themes aiming at closing cycles on a regional level.

    Showcases are the pilots of a Territorial Biorefinery Network (TBN): a
    specific topic with product generation and/or use is demonstrated by a
    best-practice or innovative installation at a defined location. In BRIT, a
    showcase links its region and catchment to the materials, samples, ordered
    process chain and scenarios that describe its inventory and material
    flows.
    """

    region = ForeignKey(Region, on_delete=PROTECT, null=True, blank=True)
    catchment = ForeignKey(
        Catchment,
        on_delete=PROTECT,
        null=True,
        blank=True,
        related_name="showcases",
        help_text="TBN region: the area in which regional stakeholders operate "
        "jointly to valorize regional bioresources. Borders may be framed "
        "flexibly, e.g. by bioresource catchment areas, product delivery "
        "areas or administrative borders.",
    )
    materials = ManyToManyField(
        Material,
        through="ShowcaseMaterial",
        blank=True,
        related_name="showcases",
        help_text="Bioresources, intermediates and products of the showcase's "
        "processing chain, linked via ShowcaseMaterial.",
    )
    processes = ManyToManyField(
        Process,
        through="ShowcaseProcess",
        blank=True,
        related_name="showcases",
        help_text="Technical process units (logistical, pre-, main- and "
        "post-treatment) forming the showcase's processing chain, linked "
        "via ShowcaseProcess.",
    )
    samples = ManyToManyField(
        Sample,
        blank=True,
        related_name="showcases",
        help_text="Samples taken at this showcase.",
    )
    sample_series = ManyToManyField(
        SampleSeries,
        blank=True,
        related_name="showcases",
        verbose_name="sample series",
        help_text="Temporal sample series measured at this showcase, e.g. "
        "feedstock monitoring of the processing chain.",
    )

    @classmethod
    def public_map_url(cls):
        return reverse("Showcase")

    def _material_links_for_role(self, role: "ShowcaseMaterial.Role"):
        """Return material links for ``role``, using the prefetch cache if set."""
        cache = getattr(self, "_prefetched_objects_cache", None)
        if cache and "showcase_materials" in cache:
            return [link for link in cache["showcase_materials"] if link.role == role]
        return list(
            self.showcase_materials.select_related("material").filter(role=role)
        )

    @property
    def input_materials(self):
        """Bioresources that enter the showcase chain."""
        return [
            link.material
            for link in self._material_links_for_role(ShowcaseMaterial.Role.INPUT)
        ]

    @property
    def intermediate_materials(self):
        """Intermediates passed between the showcase's process steps."""
        return [
            link.material
            for link in self._material_links_for_role(
                ShowcaseMaterial.Role.INTERMEDIATE
            )
        ]

    @property
    def product_materials(self):
        """Products generated by the showcase chain."""
        return [
            link.material
            for link in self._material_links_for_role(ShowcaseMaterial.Role.PRODUCT)
        ]

    @property
    def process_chain(self):
        """Processes in their configured chain order (not Process.Meta ordering)."""
        cache = getattr(self, "_prefetched_objects_cache", None)
        if cache and "showcase_processes" in cache:
            links = cache["showcase_processes"]
        else:
            links = self.showcase_processes.select_related("process")
        return [link.process for link in links]

    @staticmethod
    def _visible_material_links_queryset(user):
        visible_materials = filter_queryset_for_user(Material.objects.all(), user)
        return ShowcaseMaterial.objects.filter(
            material__in=visible_materials
        ).select_related("material")

    @staticmethod
    def _visible_process_links_queryset(user):
        visible_processes = filter_queryset_for_user(Process.objects.all(), user)
        return ShowcaseProcess.objects.filter(
            process__in=visible_processes
        ).select_related("process")

    @classmethod
    def _scenario_model(cls):
        return cls._meta.get_field("scenarios").related_model

    @classmethod
    def prefetch_visible_connections(cls, queryset, user, connections=None):
        """Prefetch the connections of each showcase that ``user`` may read.

        The ``visible_*`` methods read these caches instead of querying per
        showcase. ``connections`` limits the prefetch to the given keys
        (``"material_links"``, ``"process_links"``, ``"samples"``,
        ``"sample_series"``, ``"catchment"``, ``"scenarios"``); ``None``
        prefetches all of them.
        """
        prefetches = {
            "material_links": Prefetch(
                "showcase_materials",
                queryset=cls._visible_material_links_queryset(user),
                to_attr="_visible_material_links",
            ),
            "process_links": Prefetch(
                "showcase_processes",
                queryset=cls._visible_process_links_queryset(user),
                to_attr="_visible_process_links",
            ),
            "samples": Prefetch(
                "samples",
                queryset=filter_queryset_for_user(Sample.objects.all(), user),
                to_attr="_visible_samples",
            ),
            "sample_series": Prefetch(
                "sample_series",
                queryset=filter_queryset_for_user(SampleSeries.objects.all(), user),
                to_attr="_visible_sample_series",
            ),
            "catchment": Prefetch(
                "catchment",
                queryset=filter_queryset_for_user(Catchment.objects.all(), user),
                to_attr="_visible_catchment",
            ),
            "scenarios": Prefetch(
                "scenarios",
                queryset=filter_queryset_for_user(
                    cls._scenario_model().objects.all(), user
                ),
                to_attr="_visible_scenarios",
            ),
        }
        if connections is None:
            connections = prefetches
        return queryset.prefetch_related(*(prefetches[name] for name in connections))

    def visible_material_links(self, user):
        """Material links whose material ``user`` may read, by role and order."""
        if hasattr(self, "_visible_material_links"):
            return self._visible_material_links
        return list(self._visible_material_links_queryset(user).filter(showcase=self))

    def visible_process_chain(self, user):
        """Chain-ordered processes of this showcase that ``user`` may read."""
        if hasattr(self, "_visible_process_links"):
            links = self._visible_process_links
        else:
            links = self._visible_process_links_queryset(user).filter(showcase=self)
        return [link.process for link in links]

    def visible_samples(self, user):
        if hasattr(self, "_visible_samples"):
            return self._visible_samples
        return list(filter_queryset_for_user(self.samples.all(), user))

    def visible_sample_series(self, user):
        if hasattr(self, "_visible_sample_series"):
            return self._visible_sample_series
        return list(filter_queryset_for_user(self.sample_series.all(), user))

    def visible_scenarios(self, user):
        if hasattr(self, "_visible_scenarios"):
            return self._visible_scenarios
        return list(filter_queryset_for_user(self.scenarios.all(), user))

    def visible_catchment(self, user):
        """The catchment if ``user`` may read it, otherwise ``None``."""
        if self.catchment_id is None:
            return None
        if hasattr(self, "_visible_catchment"):
            return self._visible_catchment
        return filter_queryset_for_user(
            Catchment.objects.filter(pk=self.catchment_id), user
        ).first()


class ShowcaseMaterial(Model):
    """Role of a material in a showcase's processing chain.

    Bioresources enter the chain as inputs, intermediates connect process
    steps, and products are the intentionally created outputs with positive
    market value.
    """

    class Role(models.TextChoices):
        INPUT = "input", _("Input (bioresource)")
        INTERMEDIATE = "intermediate", _("Intermediate")
        PRODUCT = "product", _("Product (output)")

    showcase = ForeignKey(
        Showcase, on_delete=CASCADE, related_name="showcase_materials"
    )
    material = ForeignKey(
        Material, on_delete=PROTECT, related_name="showcase_materials"
    )
    role = CharField(max_length=12, choices=Role.choices)
    order = PositiveIntegerField(
        default=0, help_text="Optional order for display purposes."
    )

    class Meta:
        ordering = ["role", "order", "id"]
        constraints = [
            UniqueConstraint(
                fields=["showcase", "material", "role"],
                name="closecycle_showcasematerial_unique_material_role",
            )
        ]
        indexes = [models.Index(fields=["showcase", "role", "order"])]

    def __str__(self):
        return f"{self.material} ({self.get_role_display()})"


class ShowcaseProcess(Model):
    """A process step in the ordered processing chain of a showcase.

    The chain represents the network of technical process units (logistical,
    pre-, main- and post-treatment) through which bioresources are converted
    into products within the showcase's TBN region.
    """

    showcase = ForeignKey(
        Showcase, on_delete=CASCADE, related_name="showcase_processes"
    )
    process = ForeignKey(Process, on_delete=PROTECT, related_name="showcase_processes")
    order = PositiveIntegerField(
        default=0, help_text="Position of the process in the chain."
    )

    class Meta:
        ordering = ["order", "id"]

    def __str__(self):
        return f"{self.showcase}: {self.process} ({self.order})"


class BiogasPlantsSweden(Model):
    geom = PointField(blank=True, null=True)
    type = CharField(blank=True, null=True)
    name = CharField(blank=True, null=True)
    county = CharField(blank=True, null=True)
    city = CharField(blank=True, null=True)
    municipality = CharField(blank=True, null=True)
    creation_year = CharField(blank=True, null=True)
    size = CharField(blank=True, null=True)
    to_upgrade = CharField(blank=True, null=True)
    main_type = CharField(blank=True, null=True)
    sub_type = CharField(blank=True, null=True)
    tech_type = CharField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "closecycle_biogas_plants_sweden"
