from django.contrib.gis.db.models import PointField
from django.db import models
from django.db.models import (
    CASCADE,
    PROTECT,
    CharField,
    ForeignKey,
    ManyToManyField,
    Model,
    PositiveIntegerField,
    UniqueConstraint,
)
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from maps.models import Catchment, Region
from materials.models import Material, Sample, SampleSeries
from processes.models import Process
from utils.object_management.models import NamedUserCreatedObject


class Showcase(NamedUserCreatedObject):
    """
    A CLOSECYCLE showcase demonstrates best practices or innovative solutions
    for the valorization of residue-based bioresources from rural and urban
    areas to make products for use within the showcase region. Each showcase
    focuses on a specific topic and is assigned to one of the seven broader
    themes aiming at closing cycles on a regional level.

    Showcases are the pilots of a Territorial Biorefinery Network (TBN): a
    specific topic with product generation and/or use is demonstrated by a
    best-practice or innovative installation at a defined location. In BRIT, a
    showcase links its region and catchment to the materials, samples, ordered
    process chain and scenarios that describe its inventory and material
    flows.
    """

    region = ForeignKey(Region, on_delete=PROTECT, null=True, blank=True)
    catchment = ForeignKey(
        Catchment,
        on_delete=PROTECT,
        null=True,
        blank=True,
        related_name="showcases",
        help_text="TBN region: the area in which regional stakeholders operate "
        "jointly to valorize regional bioresources. Borders may be framed "
        "flexibly, e.g. by bioresource catchment areas, product delivery "
        "areas or administrative borders.",
    )
    materials = ManyToManyField(
        Material,
        through="ShowcaseMaterial",
        blank=True,
        related_name="showcases",
        help_text="Bioresources, intermediates and products of the showcase's "
        "processing chain, linked via ShowcaseMaterial.",
    )
    processes = ManyToManyField(
        Process,
        through="ShowcaseProcess",
        blank=True,
        related_name="showcases",
        help_text="Technical process units (logistical, pre-, main- and "
        "post-treatment) forming the showcase's processing chain, linked "
        "via ShowcaseProcess.",
    )
    samples = ManyToManyField(
        Sample,
        blank=True,
        related_name="showcases",
        help_text="Samples taken at this showcase.",
    )
    sample_series = ManyToManyField(
        SampleSeries,
        blank=True,
        related_name="showcases",
        verbose_name="sample series",
        help_text="Temporal sample series measured at this showcase, e.g. "
        "feedstock monitoring of the processing chain.",
    )

    @classmethod
    def public_map_url(cls):
        return reverse("Showcase")

    def _material_links_for_role(self, role: "ShowcaseMaterial.Role"):
        """Return material links for ``role``, using the prefetch cache if set."""
        cache = getattr(self, "_prefetched_objects_cache", None)
        if cache and "showcase_materials" in cache:
            return [link for link in cache["showcase_materials"] if link.role == role]
        return list(
            self.showcase_materials.select_related("material").filter(role=role)
        )

    @property
    def input_materials(self):
        """Bioresources that enter the showcase chain."""
        return [
            link.material
            for link in self._material_links_for_role(ShowcaseMaterial.Role.INPUT)
        ]

    @property
    def intermediate_materials(self):
        """Intermediates passed between the showcase's process steps."""
        return [
            link.material
            for link in self._material_links_for_role(
                ShowcaseMaterial.Role.INTERMEDIATE
            )
        ]

    @property
    def product_materials(self):
        """Products generated by the showcase chain."""
        return [
            link.material
            for link in self._material_links_for_role(ShowcaseMaterial.Role.PRODUCT)
        ]

    @property
    def process_chain(self):
        """Processes in their configured chain order (not Process.Meta ordering)."""
        return [
            link.process for link in self.showcase_processes.select_related("process")
        ]


class ShowcaseMaterial(Model):
    """Role of a material in a showcase's processing chain.

    Bioresources enter the chain as inputs, intermediates connect process
    steps, and products are the intentionally created outputs with positive
    market value.
    """

    class Role(models.TextChoices):
        INPUT = "input", _("Input (bioresource)")
        INTERMEDIATE = "intermediate", _("Intermediate")
        PRODUCT = "product", _("Product (output)")

    showcase = ForeignKey(
        Showcase, on_delete=CASCADE, related_name="showcase_materials"
    )
    material = ForeignKey(
        Material, on_delete=PROTECT, related_name="showcase_materials"
    )
    role = CharField(max_length=12, choices=Role.choices)
    order = PositiveIntegerField(
        default=0, help_text="Optional order for display purposes."
    )

    class Meta:
        ordering = ["role", "order", "id"]
        constraints = [
            UniqueConstraint(
                fields=["showcase", "material", "role"],
                name="closecycle_showcasematerial_unique_material_role",
            )
        ]
        indexes = [models.Index(fields=["showcase", "role", "order"])]

    def __str__(self):
        return f"{self.material} ({self.get_role_display()})"


class ShowcaseProcess(Model):
    """A process step in the ordered processing chain of a showcase.

    The chain represents the network of technical process units (logistical,
    pre-, main- and post-treatment) through which bioresources are converted
    into products within the showcase's TBN region.
    """

    showcase = ForeignKey(
        Showcase, on_delete=CASCADE, related_name="showcase_processes"
    )
    process = ForeignKey(Process, on_delete=PROTECT, related_name="showcase_processes")
    order = PositiveIntegerField(
        default=0, help_text="Position of the process in the chain."
    )

    class Meta:
        ordering = ["order", "id"]
        constraints = [
            UniqueConstraint(
                fields=["showcase", "process"],
                name="closecycle_showcaseprocess_unique_process",
            )
        ]

    def __str__(self):
        return f"{self.showcase}: {self.process} ({self.order})"


class BiogasPlantsSweden(Model):
    geom = PointField(blank=True, null=True)
    type = CharField(blank=True, null=True)
    name = CharField(blank=True, null=True)
    county = CharField(blank=True, null=True)
    city = CharField(blank=True, null=True)
    municipality = CharField(blank=True, null=True)
    creation_year = CharField(blank=True, null=True)
    size = CharField(blank=True, null=True)
    to_upgrade = CharField(blank=True, null=True)
    main_type = CharField(blank=True, null=True)
    sub_type = CharField(blank=True, null=True)
    tech_type = CharField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = "closecycle_biogas_plants_sweden"
