# Generated by Django 4.2.8 on 2024-01-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexibi_hamburg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburggreenareas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hamburgroadsidetrees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
