# Generated by Django 5.2.4 on 2026-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexibi_hamburg", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hamburgroadsidetrees",
            index=models.Index(fields=["baumid"], name="flexibi_ham_baumid_4f523a_idx"),
        ),
        migrations.AddIndex(
            model_name="hamburgroadsidetrees",
            index=models.Index(
                fields=["gattung_deutsch"], name="flexibi_ham_gattung_7a939c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hamburgroadsidetrees",
            index=models.Index(
                fields=["pflanzjahr"], name="flexibi_ham_pflanzj_0ac23c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hamburgroadsidetrees",
            index=models.Index(
                fields=["stammumfang"], name="flexibi_ham_stammum_f1ca86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hamburgroadsidetrees",
            index=models.Index(fields=["bezirk"], name="flexibi_ham_bezirk_e41bc8_idx"),
        ),
    ]
