# Generated by Django 5.1.7 on 2025-05-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexibi_hamburg', '0002_alter_hamburggreenareas_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hamburgroadsidetrees',
            options={'ordering': ['baumid'], 'verbose_name': 'Hamburg Roadside Tree', 'verbose_name_plural': 'Hamburg Roadside Trees'},
        ),
    ]
