# Generated by Django 6.0.5 on 2026-08-03 12:56

import django.core.validators
from django.db import migrations, models

import sources.waste_collection.waste_atlas.models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_atlas", "0005_merge_20260730_1555"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteAtlasRenderingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_data_color",
                    models.CharField(
                        default="#e0e0e0",
                        help_text="Fill for regions without data.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "no_collection_color",
                    models.CharField(
                        default="#fff696",
                        help_text="Fill for regions without a separate collection.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "country_fill_color",
                    models.CharField(
                        default="#f0f0f0",
                        help_text="Base fill of the country layer.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "country_stroke_color",
                    models.CharField(
                        default="#000000",
                        help_text="Outline color of the country border.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "country_stroke_width",
                    models.FloatField(
                        default=1.5,
                        help_text="Outline width of the country border in pixels.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "subdivision_stroke_color",
                    models.CharField(
                        default="#666666",
                        help_text="Outline color of first-level subdivisions (e.g. Bundesländer).",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "subdivision_stroke_width",
                    models.FloatField(
                        default=1.0,
                        help_text="Outline width of first-level subdivisions in pixels.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "catchment_stroke_color",
                    models.CharField(
                        default="#232323",
                        help_text="Outline color of catchments.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "catchment_stroke_width",
                    models.FloatField(
                        default=0.35,
                        help_text="Outline width of catchments in pixels.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "conflict_stroke_color",
                    models.CharField(
                        default="#d7263d",
                        help_text="Outline color highlighting catchments with conflicting collections.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "conflict_stroke_width",
                    models.FloatField(
                        default=1.6,
                        help_text="Outline width of the conflict highlight in pixels.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "conflict_stroke_dasharray",
                    models.CharField(
                        default="3 2",
                        help_text="SVG dash pattern of the conflict highlight.",
                        max_length=32,
                    ),
                ),
                (
                    "quartile_colors",
                    models.JSONField(
                        default=sources.waste_collection.waste_atlas.models.default_quartile_colors,
                        help_text="Four hex colors used for quartile classification, low to high.",
                    ),
                ),
                (
                    "change_no_change_color",
                    models.CharField(
                        default="#c8e6c9",
                        help_text="Change maps: regions that did not change.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "change_changed_color",
                    models.CharField(
                        default="#ffb74d",
                        help_text="Change maps: regions whose category changed.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "change_new_color",
                    models.CharField(
                        default="#64b5f6",
                        help_text="Change maps: regions with data only in the later year.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "change_removed_color",
                    models.CharField(
                        default="#bdbdbd",
                        help_text="Change maps: regions with data only in the earlier year.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "change_increase_color",
                    models.CharField(
                        default="#1a9850",
                        help_text="Change maps: numeric increase.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "change_decrease_color",
                    models.CharField(
                        default="#d73027",
                        help_text="Change maps: numeric decrease.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a hex color such as #e0e0e0.",
                                regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "legend_placement",
                    models.CharField(
                        choices=[
                            ("bottom-left", "Bottom left"),
                            ("bottom-right", "Bottom right"),
                            ("top-left", "Top left"),
                            ("top-right", "Top right"),
                        ],
                        default="bottom-left",
                        help_text="Default on-screen legend placement.",
                        max_length=20,
                    ),
                ),
                (
                    "legend_width",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Default on-screen legend width in pixels.",
                        validators=[
                            django.core.validators.MinValueValidator(180),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "legend_font_size",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Default on-screen legend text size in pixels.",
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "export_dpi",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Resolution of exported PNG and SVG documents.",
                        validators=[
                            django.core.validators.MinValueValidator(72),
                            django.core.validators.MaxValueValidator(1200),
                        ],
                    ),
                ),
                (
                    "export_width_mm",
                    models.PositiveIntegerField(
                        default=160,
                        help_text="Width of the exported document in millimetres.",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "export_height_mm",
                    models.PositiveIntegerField(
                        default=110,
                        help_text="Preferred height of the exported document in millimetres.",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "export_max_height_mm",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="Largest height the export layout may grow to.",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "export_legend_font_size_pt",
                    models.FloatField(
                        default=11.0,
                        help_text="Legend text size in exports, in points.",
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(48),
                        ],
                    ),
                ),
                (
                    "export_legend_font_family",
                    models.CharField(
                        default="'Calibri', 'Carlito', Arial, sans-serif",
                        help_text="Font stack used for legend text in exports.",
                        max_length=200,
                    ),
                ),
                (
                    "export_legend_width_fraction",
                    models.FloatField(
                        default=0.52,
                        help_text="Default legend width in exports as a fraction of the page.",
                        validators=[
                            django.core.validators.MinValueValidator(0.2),
                            django.core.validators.MaxValueValidator(0.9),
                        ],
                    ),
                ),
                (
                    "export_legend_columns",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Default number of legend columns in exports.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "export_legend_bottom_columns",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Legend columns used when the legend sits below the map.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "export_file_name_prefix",
                    models.SlugField(
                        default="waste_atlas",
                        help_text="Prefix of every exported file name.",
                    ),
                ),
                (
                    "geometry_simplify_tolerance",
                    models.FloatField(
                        default=0.001,
                        help_text="Geometry simplification tolerance in degrees used when serving catchment geometries (0 disables simplification).",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Waste Atlas rendering settings",
                "verbose_name_plural": "Waste Atlas rendering settings",
            },
        ),
    ]
