# Generated by Django 6.0.5 on 2026-08-04 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_atlas", "0009_drop_placement_coupled_legend_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteatlasrenderingsettings",
            name="change_boundary_changed_color",
            field=models.CharField(
                default="#ba68c8",
                help_text="Change maps: territory reassigned to a different catchment.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a hex color such as #e0e0e0.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
            ),
        ),
    ]
