# Generated by Django 6.0.5 on 2026-08-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "waste_atlas",
            "0010_wasteatlasrenderingsettings_change_boundary_changed_color",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteatlasrenderingsettings",
            name="export_legend_item_flow",
            field=models.CharField(
                choices=[
                    ("column", "By column (fill one column, then the next)"),
                    ("row", "By row (fill across the columns)"),
                ],
                default="column",
                help_text="Default arrangement of legend entries across the legend columns in exports.",
                max_length=10,
            ),
        ),
    ]
