# Generated by Django 6.0.5 on 2026-08-13 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_atlas", "0011_wasteatlasrenderingsettings_export_legend_item_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteatlasrenderingsettings",
            name="acpv_hatch_color",
            field=models.CharField(
                default="#1f2937",
                help_text="Hatching that marks values aggregated over several catchments (ACPV).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a hex color such as #e0e0e0.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="wasteatlasrenderingsettings",
            name="acpv_hatch_opacity",
            field=models.FloatField(
                default=0.9,
                help_text="Opacity of the aggregated-value hatching, 0 to 1.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wasteatlasrenderingsettings",
            name="acpv_outline_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Outline around a group of catchments sharing an aggregated value.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a hex color such as #e0e0e0.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="wasteatlasrenderingsettings",
            name="acpv_outline_opacity",
            field=models.FloatField(
                default=0.95,
                help_text="Opacity of the aggregated-value group outline, 0 to 1.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="wasteatlasrenderingsettings",
            name="acpv_outline_width",
            field=models.FloatField(
                default=1.35,
                help_text="Width of the aggregated-value group outline, in pixels of the on-screen map; exports scale it with the page.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
