# Generated by Django 6.0.5 on 2026-08-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waste_atlas", "0013_centralize_acpv_marker_appearance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteatlasrenderingsettings",
            name="export_legend_item_flow",
            field=models.CharField(
                choices=[
                    ("column", "By column (fill one column, then the next)"),
                    ("row", "By row (fill across the columns)"),
                ],
                default="column",
                help_text="Default arrangement of legend entries across the legend columns, in exports and on the map page.",
                max_length=10,
            ),
        ),
    ]
