from django.urls import include, path
from django.views.generic import RedirectView

from . import views
from .router import router

urlpatterns = [
    path(
        "",
        RedirectView.as_view(url="/materials/samples/featured/"),
        name="materials-home",
    ),
    path("explorer/", views.MaterialsExplorerView.as_view(), name="materials-explorer"),
    path("diagram/", views.MaterialsDiagramView.as_view(), name="materials-diagram"),
    path("materials/", views.MaterialPublishedListView.as_view(), name="material-list"),
    path(
        "materials/user/",
        views.MaterialPrivateListView.as_view(),
        name="material-list-owned",
    ),
    path(
        "materials/create/", views.MaterialCreateView.as_view(), name="material-create"
    ),
    path(
        "materials/create/modal/",
        views.MaterialModalCreateView.as_view(),
        name="material-create-modal",
    ),
    path(
        "materials/<int:pk>/",
        views.MaterialDetailView.as_view(),
        name="material-detail",
    ),
    path(
        "materials/<int:pk>/modal/",
        views.MaterialModalDetailView.as_view(),
        name="material-detail-modal",
    ),
    path(
        "materials/<int:pk>/update/",
        views.MaterialUpdateView.as_view(),
        name="material-update",
    ),
    path(
        "materials/<int:pk>/update/modal/",
        views.MaterialModalUpdateView.as_view(),
        name="material-update-modal",
    ),
    path(
        "materials/<int:pk>/delete/",
        views.MaterialModalDeleteView.as_view(),
        name="material-delete-modal",
    ),
    path(
        "materials/autocomplete/",
        views.MaterialAutocompleteView.as_view(),
        name="material-autocomplete",
    ),
    path(
        "analytical_methods/",
        views.AnalyticalMethodPublishedListView.as_view(),
        name="analyticalmethod-list",
    ),
    path(
        "analytical_methods/user/",
        views.AnalyticalMethodPrivateListView.as_view(),
        name="analyticalmethod-list-owned",
    ),
    path(
        "analytical_methods/create/",
        views.AnalyticalMethodCreateView.as_view(),
        name="analyticalmethod-create",
    ),
    path(
        "analytical_methods/<int:pk>/",
        views.AnalyticalMethodDetailView.as_view(),
        name="analyticalmethod-detail",
    ),
    path(
        "analytical_methods/<int:pk>/modal/",
        views.AnalyticalMethodModalDetailView.as_view(),
        name="analyticalmethod-detail-modal",
    ),
    path(
        "analytical_methods/<int:pk>/update/",
        views.AnalyticalMethodUpdateView.as_view(),
        name="analyticalmethod-update",
    ),
    path(
        "analytical_methods/<int:pk>/delete/modal/",
        views.AnalyticalMethodModalDeleteView.as_view(),
        name="analyticalmethod-delete-modal",
    ),
    path(
        "analytical_methods/autocomplete/",
        views.AnalyticalMethodAutocompleteView.as_view(),
        name="analyticalmethod-autocomplete",
    ),
    path(
        "sample_series/",
        views.SampleSeriesPublishedListView.as_view(),
        name="sampleseries-list",
    ),
    path(
        "sample_series/autocomplete/",
        views.SampleSeriesAutoCompleteView.as_view(),
        name="sampleseries-autocomplete",
    ),
    path(
        "sample_series/featured/",
        views.FeaturedMaterialListView.as_view(),
        name="sampleseries-list-featured",
    ),
    path(
        "sample_series/user/",
        views.SampleSeriesPrivateListView.as_view(),
        name="sampleseries-list-owned",
    ),
    path(
        "sample_series/create/",
        views.SampleSeriesCreateView.as_view(),
        name="sampleseries-create",
    ),
    path(
        "sample_series/create/modal",
        views.SampleSeriesModalCreateView.as_view(),
        name="sampleseries-create-modal",
    ),
    path(
        "sample_series/<int:pk>/",
        views.SampleSeriesDetailView.as_view(),
        name="sampleseries-detail",
    ),
    path(
        "sample_series/<int:pk>/modal/",
        views.SampleSeriesModalDetailView.as_view(),
        name="sampleseries-detail-modal",
    ),
    path(
        "sample_series/<int:pk>/update/",
        views.SampleSeriesUpdateView.as_view(),
        name="sampleseries-update",
    ),
    path(
        "sample_series/<int:pk>/update/modal/",
        views.SampleSeriesModalUpdateView.as_view(),
        name="sampleseries-update-modal",
    ),
    path(
        "sample_series/<int:pk>/delete/modal/",
        views.SampleSeriesModalDeleteView.as_view(),
        name="sampleseries-delete-modal",
    ),
    path(
        "sample_series/<int:pk>/add_composition/",
        views.AddCompositionView.as_view(),
        name="sampleseries-add-composition",
    ),
    path(
        "sample_series/<int:pk>/add_distribution/modal/",
        views.SampleSeriesModalAddDistributionView.as_view(),
        name="sampleseries-add-distribution-modal",
    ),
    path(
        "sample_series/<int:pk>/duplicate/",
        views.SampleSeriesCreateDuplicateView.as_view(),
        name="sampleseries-duplicate",
    ),
    path("samples/", views.SamplePublishedListView.as_view(), name="sample-list"),
    path(
        "samples/autocomplete/",
        views.SampleAutocompleteView.as_view(),
        name="sample-autocomplete",
    ),
    path(
        "samples/autocomplete/public/",
        views.PublishedSampleAutoCompleteView.as_view(),
        name="sample-autocomplete-public",
    ),
    path(
        "samples/autocomplete/user/",
        views.UserOwnedSampleAutoCompleteView.as_view(),
        name="sample-autocomplete-user",
    ),
    path(
        "samples/featured/",
        views.FeaturedSampleListView.as_view(),
        name="sample-list-featured",
    ),
    path(
        "samples/user/", views.SamplePrivateListView.as_view(), name="sample-list-owned"
    ),
    path("samples/create/", views.SampleCreateView.as_view(), name="sample-create"),
    path(
        "samples/create/modal/",
        views.SampleModalCreateView.as_view(),
        name="sample-create-modal",
    ),
    path("samples/<int:pk>/", views.SampleDetailView.as_view(), name="sample-detail"),
    path(
        "samples/<int:pk>/update/",
        views.SampleUpdateView.as_view(),
        name="sample-update",
    ),
    path(
        "samples/<int:pk>/delete/modal/",
        views.SampleModalDeleteView.as_view(),
        name="sample-delete-modal",
    ),
    path(
        "samples/<int:pk>/composition/add/",
        views.SampleAddCompositionView.as_view(),
        name="sample-add-composition",
    ),
    path(
        "samples/<int:pk>/add_property",
        views.SampleAddPropertyView.as_view(),
        name="sample-add-property",
    ),
    path(
        "samples/<int:pk>/add_property/modal/",
        views.SampleModalAddPropertyView.as_view(),
        name="sample-add-property-modal",
    ),
    path(
        "samples/<int:pk>/duplicate/",
        views.SampleCreateDuplicateView.as_view(),
        name="sample-duplicate",
    ),
    path(
        "samples/<int:pk>/export/",
        views.SampleExportView.as_view(),
        name="sample-export",
    ),
    path(
        "categories/",
        views.MaterialCategoryPublishedListView.as_view(),
        name="materialcategory-list",
    ),
    path(
        "categories/user/",
        views.MaterialCategoryPrivateListView.as_view(),
        name="materialcategory-list-owned",
    ),
    path(
        "categories/create/",
        views.MaterialCategoryCreateView.as_view(),
        name="materialcategory-create",
    ),
    path(
        "categories/create/modal/",
        views.MaterialCategoryModalCreateView.as_view(),
        name="materialcategory-create-modal",
    ),
    path(
        "categories/<int:pk>/",
        views.MaterialCategoryDetailView.as_view(),
        name="materialcategory-detail",
    ),
    path(
        "categories/<int:pk>/modal/",
        views.MaterialCategoryModalDetailView.as_view(),
        name="materialcategory-detail-modal",
    ),
    path(
        "categories/<int:pk>/update/",
        views.MaterialCategoryUpdateView.as_view(),
        name="materialcategory-update",
    ),
    path(
        "categories/<int:pk>/update/modal/",
        views.MaterialCategoryModalUpdateView.as_view(),
        name="materialcategory-update-modal",
    ),
    path(
        "categories/<int:pk>/delete/modal/",
        views.MaterialCategoryModalDeleteView.as_view(),
        name="materialcategory-delete-modal",
    ),
    path(
        "categories/autocomplete/",
        views.MaterialCategoryAutocompleteView.as_view(),
        name="materialcategory-autocomplete",
    ),
    path(
        "components/",
        views.ComponentPublishedListView.as_view(),
        name="materialcomponent-list",
    ),
    path(
        "components/user/",
        views.ComponentPrivateListView.as_view(),
        name="materialcomponent-list-owned",
    ),
    path(
        "components/create/",
        views.ComponentCreateView.as_view(),
        name="materialcomponent-create",
    ),
    path(
        "components/create/modal",
        views.ComponentModalCreateView.as_view(),
        name="materialcomponent-create-modal",
    ),
    path(
        "components/<int:pk>/",
        views.ComponentDetailView.as_view(),
        name="materialcomponent-detail",
    ),
    path(
        "components/<int:pk>/modal/",
        views.ComponentModalDetailView.as_view(),
        name="materialcomponent-detail-modal",
    ),
    path(
        "components/<int:pk>/update/",
        views.ComponentUpdateView.as_view(),
        name="materialcomponent-update",
    ),
    path(
        "components/<int:pk>/update/modal/",
        views.ComponentUpdateView.as_view(),
        name="materialcomponent-update-modal",
    ),
    path(
        "components/<int:pk>/delete/modal/",
        views.ComponentModalDeleteView.as_view(),
        name="materialcomponent-delete-modal",
    ),
    path(
        "components/autocomplete/",
        views.ComponentAutocompleteView.as_view(),
        name="materialcomponent-autocomplete",
    ),
    path(
        "componentgroups/",
        views.MaterialComponentGroupPublishedListView.as_view(),
        name="materialcomponentgroup-list",
    ),
    path(
        "componentgroups/user/",
        views.MaterialComponentGroupPrivateListView.as_view(),
        name="materialcomponentgroup-list-owned",
    ),
    path(
        "componentgroups/create/",
        views.MaterialComponentGroupCreateView.as_view(),
        name="materialcomponentgroup-create",
    ),
    path(
        "componentgroups/create/modal/",
        views.MaterialComponentGroupModalCreateView.as_view(),
        name="materialcomponentgroup-create-modal",
    ),
    path(
        "componentgroups/<int:pk>/",
        views.MaterialComponentGroupDetailView.as_view(),
        name="materialcomponentgroup-detail",
    ),
    path(
        "componentgroups/<int:pk>/modal/",
        views.MaterialComponentGroupModalDetailView.as_view(),
        name="materialcomponentgroup-detail-modal",
    ),
    path(
        "componentgroups/<int:pk>/update/",
        views.MaterialComponentGroupUpdateView.as_view(),
        name="materialcomponentgroup-update",
    ),
    path(
        "componentgroups/<int:pk>/update/modal/",
        views.MaterialComponentGroupModalUpdateView.as_view(),
        name="materialcomponentgroup-update-modal",
    ),
    path(
        "componentgroups/<int:pk>/delete/modal/",
        views.MaterialComponentGroupModalDeleteView.as_view(),
        name="materialcomponentgroup-delete-modal",
    ),
    path(
        "componentgroups/autocomplete/",
        views.MaterialComponentGroupAutocompleteView.as_view(),
        name="materialcomponentgroup-autocomplete",
    ),
    path(
        "properties/",
        views.MaterialPropertyPublishedListView.as_view(),
        name="materialproperty-list",
    ),
    path(
        "properties/user/",
        views.MaterialPropertyPrivateListView.as_view(),
        name="materialproperty-list-owned",
    ),
    path(
        "properties/create/",
        views.MaterialPropertyCreateView.as_view(),
        name="materialproperty-create",
    ),
    path(
        "properties/create/modal/",
        views.MaterialPropertyModalCreateView.as_view(),
        name="materialproperty-create-modal",
    ),
    path(
        "properties/<int:pk>/",
        views.MaterialPropertyDetailView.as_view(),
        name="materialproperty-detail",
    ),
    path(
        "properties/<int:pk>/modal/",
        views.MaterialPropertyModalDetailView.as_view(),
        name="materialproperty-detail-modal",
    ),
    path(
        "properties/<int:pk>/update/",
        views.MaterialPropertyUpdateView.as_view(),
        name="materialproperty-update",
    ),
    path(
        "properties/<int:pk>/update/modal/",
        views.MaterialPropertyModalUpdateView.as_view(),
        name="materialproperty-update-modal",
    ),
    path(
        "properties/<int:pk>/delete/modal/",
        views.MaterialPropertyModalDeleteView.as_view(),
        name="materialproperty-delete-modal",
    ),
    path(
        "properties/autocomplete/",
        views.MaterialPropertyAutocompleteView.as_view(),
        name="materialproperty-autocomplete",
    ),
    path(
        "property_values/<int:pk>/delete/modal/",
        views.MaterialPropertyValueModalDeleteView.as_view(),
        name="materialpropertyvalue-delete-modal",
    ),
    path(
        "compositions/create/",
        views.CompositionCreateView.as_view(),
        name="composition-create",
    ),
    path(
        "compositions/create/modal/",
        views.CompositionModalCreateView.as_view(),
        name="composition-create-modal",
    ),
    path(
        "compositions/<int:pk>/",
        views.CompositionDetailView.as_view(),
        name="composition-detail",
    ),
    path(
        "compositions/<int:pk>/modal/",
        views.CompositionModalDetailView.as_view(),
        name="composition-detail-modal",
    ),
    path(
        "compositions/<int:pk>/update/",
        views.CompositionUpdateView.as_view(),
        name="composition-update",
    ),
    path(
        "compositions/<int:pk>/delete/",
        views.CompositionModalDeleteView.as_view(),
        name="composition-delete-modal",
    ),
    path(
        "compositions/<int:pk>/add_component/",
        views.AddComponentView.as_view(),
        name="composition-add-component",
    ),
    path(
        "compositions/<int:pk>/order_up/",
        views.CompositionOrderUpView.as_view(),
        name="composition-order-up",
    ),
    path(
        "compositions/<int:pk>/order_down/",
        views.CompositionOrderDownView.as_view(),
        name="composition-order-down",
    ),
    path(
        "materialcomponentgroups/settings/<int:pk>/add_source/",
        views.AddSourceView.as_view(),
        name="add_source",
    ),
    path(
        "materialcomponentgroups/settings/<int:pk>/remove_seasonal_variation/<int:distribution_pk>/",
        views.RemoveSeasonalVariationView.as_view(),
        name="remove_seasonal_variation",
    ),
    path(
        "weightshares/<int:pk>/delete/",
        views.WeightShareModalDeleteView.as_view(),
        name="weightshare-delete-modal",
    ),
    path("api/", include(router.urls)),
]
