from django.urls import path

from . import views

urlpatterns = [
    path('', views.FeaturedMaterialListView.as_view(), name='featured_material_list'),
    path('list/', views.MaterialListView.as_view(), name='material-list'),
    path('create/', views.MaterialCreateView.as_view(), name='material-create'),
    path('create/modal/', views.MaterialModalCreateView.as_view(), name='material-create-modal'),
    path('<int:pk>/', views.MaterialDetailView.as_view(), name='material-detail'),
    path('<int:pk>/modal/', views.MaterialModalDetailView.as_view(), name='material-detail-modal'),
    path('<int:pk>/update/', views.MaterialUpdateView.as_view(), name='material-update'),
    path('<int:pk>/update/modal/', views.MaterialModalUpdateView.as_view(), name='material-update-modal'),
    path('<int:pk>/delete/', views.MaterialModalDeleteView.as_view(), name='material-delete-modal'),
    path('groups/', views.MaterialGroupListView.as_view(), name='material_group_list'),
    path('groups/create/', views.MaterialGroupCreateView.as_view(), name='material_group_create'),
    path('groups/create/modal/', views.MaterialGroupCreateView.as_view(), name='material_group_create_modal'),
    path('groups/<int:pk>/', views.MaterialGroupDetailView.as_view(), name='material_group_detail'),
    path('groups/<int:pk>/modal/', views.MaterialGroupModalDetailView.as_view(), name='material_group_detail_modal'),
    path('groups/<int:pk>/update/', views.MaterialGroupUpdateView.as_view(), name='material_group_update'),
    path('groups/<int:pk>/update/modal/', views.MaterialGroupModalUpdateView.as_view(),
         name='material_group_update_modal'),
    path('groups/<int:pk>/delete/modal/', views.MaterialGroupModalDeleteView.as_view(),
         name='material_group_delete_modal'),
    path('materials/settings/<int:pk>/', views.MaterialSettingsDetailView.as_view(), name='material_settings'),
    path('materials/settings/<int:pk>/add_component_group/', views.AddComponentGroupView.as_view(),
         name='material_add_component_group'),
    path('materials/settings/<int:pk>/delete/', views.MaterialSettingsDeleteView.as_view(), name='material_settings_delete'),
    path('materialcomponents/', views.MaterialComponentListView.as_view(), name='component_list'),
    path('materialcomponents/create/', views.MaterialComponentCreateView.as_view(), name='component_create'),
    path('materialcomponents/<int:pk>/', views.MaterialComponentDetailView.as_view(), name='component_detail'),
    path('materialcomponents/<int:pk>/update/', views.MaterialComponentUpdateView.as_view(),
         name='component_update'),
    path('materialcomponents/<int:pk>/delete/', views.MaterialComponentDeleteView.as_view(),
         name='component_delete'),
    path('materialcomponentgroups/', views.ComponentGroupListView.as_view(), name='material_component_group_list'),
    path('materialcomponentgroups/create/', views.ComponentGroupCreateView.as_view(),
         name='material_component_group_create'),
    path('materialcomponentgroups/<int:pk>/', views.ComponentGroupDetailView.as_view(),
         name='material_component_group_detail'),
    path('materialcomponentgroups/<int:pk>/update/', views.ComponentGroupUpdateView.as_view(),
         name='material_component_group_update'),
    path('compositionsets/<int:pk>/update/', views.CompositionSetModalUpdateView.as_view(),
         name='compositionset-update-modal'),
    path('materialcomponentgroups/<int:pk>/delete/', views.ComponentGroupDeleteView.as_view(),
         name='material_component_group_delete'),
    path('materialcomponentgroups/settings/<int:pk>/add_component/', views.AddComponentView.as_view(),
         name='add_component'),
    path('materialcomponentgroups/settings/<int:pk>/add_source/', views.AddSourceView.as_view(), name='add_source'),
    path('materialcomponentgroups/settings/<int:pk>/add_seasonal_variation/', views.AddSeasonalVariationView.as_view(),
         name='add_seasonal_variation'),
    path('materialcomponentgroups/settings/<int:pk>/remove_seasonal_variation/<int:distribution_pk>/',
         views.RemoveSeasonalVariationView.as_view(),
         name='remove_seasonal_variation'),
    path('materialcomponentgroups/settings/<int:pk>/remove_component/<int:component_pk>/',
         views.RemoveComponentView.as_view(), name='material_component_group_remove_component'),
    path('materialcomponentgroups/settings/<int:pk>/remove/', views.RemoveComponentGroupView.as_view(),
         name='material_component_group_remove'),
]
